"""Topology-first discovery of terminal cyclic methyl rotors."""

from __future__ import annotations

from collections import deque
from itertools import permutations

import numpy as np

from .models import CoordinateDefinition, PrimitiveRotor
from .phase import principal_periodic_delta
from .structure_generation import rotate_coordinates_about_axis


def _neighbors(connectivity, atom: int) -> tuple[int, ...]:
    return tuple(int(i) for i in np.flatnonzero(np.asarray(connectivity)[atom]))


def detect_equivalent_neighbor_groups(labels, connectivity, center: int):
    """Return topology-equivalent neighbors without using molecule-specific indices.

    The local signature is deliberately small and exact: element, degree, and the
    sorted elements attached to the candidate other than ``center``.  It is enough
    to establish the three identical terminal hydrogens of a methyl group while
    refusing chemically different substituents.
    """

    labels = tuple(str(label).upper() for label in labels)
    groups = {}
    for atom in _neighbors(connectivity, center):
        other_neighbors = tuple(
            sorted(
                labels[neighbor]
                for neighbor in _neighbors(connectivity, atom)
                if neighbor != center
            )
        )
        signature = (labels[atom], len(_neighbors(connectivity, atom)), other_neighbors)
        groups.setdefault(signature, []).append(int(atom))
    return tuple(
        tuple(sorted(atoms))
        for _, atoms in sorted(groups.items())
        if len(atoms) > 1
    )


def _component_after_cut(connectivity, start: int, cut: tuple[int, int]) -> tuple[int, ...]:
    cut_set = frozenset(cut)
    visited = {int(start)}
    queue = deque([int(start)])
    while queue:
        atom = queue.popleft()
        for neighbor in _neighbors(connectivity, atom):
            if frozenset((atom, neighbor)) == cut_set or neighbor in visited:
                continue
            visited.add(neighbor)
            queue.append(neighbor)
    return tuple(sorted(visited))


def _bond_is_in_ring(connectivity, atom_a: int, atom_b: int) -> bool:
    return atom_b in _component_after_cut(connectivity, atom_a, (atom_a, atom_b))


def _looks_like_carbonyl_carbon(labels, connectivity, coordinates, atom: int) -> bool:
    for neighbor in _neighbors(connectivity, atom):
        if str(labels[neighbor]).upper().startswith("O"):
            distance_bohr = float(np.linalg.norm(coordinates[neighbor] - coordinates[atom]))
            if distance_bohr < 2.75:  # 1.46 Angstrom; topology has no bond orders.
                return True
    return False


def _is_restricted_amide_axis(labels, connectivity, coordinates, attachment: int) -> bool:
    if not str(labels[attachment]).upper().startswith("N"):
        return False
    return any(
        str(labels[neighbor]).upper().startswith("C")
        and _looks_like_carbonyl_carbon(labels, connectivity, coordinates, neighbor)
        for neighbor in _neighbors(connectivity, attachment)
    )


def _threefold_geometry_is_plausible(coordinates, center: int, attachment: int, hydrogens) -> bool:
    center_xyz = coordinates[center]
    bond_lengths = np.array(
        [np.linalg.norm(coordinates[h] - center_xyz) for h in hydrogens], dtype=float
    )
    if np.ptp(bond_lengths) > 0.30:  # bohr, deliberately tolerant of an unoptimized input
        return False
    axis = coordinates[attachment] - center_xyz
    axis_norm = np.linalg.norm(axis)
    if axis_norm < 1.0e-10:
        return False
    axis /= axis_norm
    cosines = np.array(
        [np.dot(coordinates[h] - center_xyz, axis) / bond_lengths[i] for i, h in enumerate(hydrogens)]
    )
    return bool(np.ptp(cosines) < 0.30)


def rigid_symmetry_defect(coordinates, axis_atoms, moving_atoms, owned_atoms, order):
    """Distance between the exact atom permutation and a rigid rotation.

    The cyclic images used by the grouped construction relabel equivalent atoms,
    while the phase grid is generated by rigidly rotating the group about its
    axis.  The two coincide only when the group's own internal geometry carries
    the cyclic symmetry.  This returns the largest Cartesian mismatch over the
    non-identity operations, in bohr, so that a distorted group can be given a
    physically sampled phase grid instead of trusting its images.
    """

    coordinates = np.asarray(coordinates, dtype=float)
    owned = tuple(int(atom) for atom in owned_atoms)
    if order <= 1 or len(owned) < 2:
        return 0.0
    worst = 0.0
    for step in range(1, int(order)):
        rotated = rotate_coordinates_about_axis(
            coordinates,
            axis_atoms=axis_atoms,
            moving_atoms=moving_atoms,
            angle=step * 2.0 * np.pi / float(order),
        )
        best = None
        for candidate in permutations(owned):
            permutation = np.arange(len(coordinates), dtype=int)
            for target_atom, source_atom in zip(owned, candidate):
                permutation[target_atom] = source_atom
            errors = np.linalg.norm(
                coordinates[permutation][list(owned)] - rotated[list(owned)], axis=1
            )
            maximum = float(np.max(errors))
            if best is None or maximum < best:
                best = maximum
        worst = max(worst, best)
    return worst


def _oriented_torsion_rows(
    coordinate_definition,
    coordinate_value_function,
    coordinates,
    axis_atoms,
    moving_atoms,
    orientation_step,
):
    axis_key = frozenset(axis_atoms)
    torsion_rows = tuple(
        row_index
        for row_index, (kind, row) in enumerate(
            zip(coordinate_definition.row_types, coordinate_definition.rows)
        )
        if kind == "proper_torsion"
        and frozenset((row[1], row[2])) == axis_key
    )
    if not torsion_rows:
        return (), ()
    reference = np.asarray(coordinate_value_function(coordinates), dtype=float)
    perturbed = rotate_coordinates_about_axis(
        coordinates,
        axis_atoms=axis_atoms,
        moving_atoms=moving_atoms,
        angle=orientation_step,
    )
    changed = np.asarray(coordinate_value_function(perturbed), dtype=float)
    valid_rows = []
    orientations = []
    for row_index in torsion_rows:
        delta = principal_periodic_delta(changed[row_index] - reference[row_index])
        if abs(delta) < 0.25 * orientation_step:
            continue
        valid_rows.append(int(row_index))
        orientations.append(1 if delta > 0.0 else -1)
    return tuple(valid_rows), tuple(orientations)


def _terminal_methyl_atoms(labels, connectivity, center):
    if not str(labels[center]).upper().startswith("C"):
        return None
    neighbors = _neighbors(connectivity, center)
    hydrogens = tuple(
        atom for atom in neighbors if str(labels[atom]).upper().startswith("H")
    )
    heavy = tuple(atom for atom in neighbors if atom not in hydrogens)
    if len(hydrogens) != 3 or len(heavy) != 1 or len(neighbors) != 4:
        return None
    return tuple(sorted(hydrogens)), int(heavy[0])


class PrimitiveRotorDetector:
    """Detect terminal methyl and optional C-O group rotations from topology."""

    def __init__(
        self,
        excluded_axis_bonds=(),
        orientation_step=1.0e-4,
        detect_group_rotors=False,
    ):
        self.excluded_axis_bonds = {
            frozenset((int(a), int(b))) for a, b in excluded_axis_bonds
        }
        self.orientation_step = float(orientation_step)
        self.detect_group_rotors = bool(detect_group_rotors)

    def detect(
        self,
        molecule,
        coordinate_definition: CoordinateDefinition,
        coordinate_value_function,
    ) -> tuple[PrimitiveRotor, ...]:
        labels = tuple(str(label) for label in molecule.get_labels())
        connectivity = np.asarray(molecule.get_connectivity_matrix(), dtype=bool)
        coordinates = np.asarray(molecule.get_coordinates_in_bohr(), dtype=float)
        candidates = []
        for center, label in enumerate(labels):
            methyl = _terminal_methyl_atoms(labels, connectivity, center)
            if methyl is None:
                continue
            hydrogens, attachment = methyl
            axis_key = frozenset((attachment, center))
            if axis_key in self.excluded_axis_bonds:
                continue
            if _bond_is_in_ring(connectivity, attachment, center):
                continue
            if _is_restricted_amide_axis(
                labels, connectivity, coordinates, attachment
            ):
                continue

            moving_side = _component_after_cut(
                connectivity, center, (attachment, center)
            )
            expected_moving = tuple(sorted((center, *hydrogens)))
            if moving_side != expected_moving:
                continue
            if not _threefold_geometry_is_plausible(
                coordinates, center, attachment, hydrogens
            ):
                continue

            valid_rows, orientations = _oriented_torsion_rows(
                coordinate_definition,
                coordinate_value_function,
                coordinates,
                axis_atoms=(attachment, center),
                moving_atoms=moving_side,
                orientation_step=self.orientation_step,
            )
            if not valid_rows:
                continue

            equivalent_groups = detect_equivalent_neighbor_groups(
                labels, connectivity, center
            )
            hydrogen_group = tuple(sorted(hydrogens))
            if hydrogen_group not in equivalent_groups:
                continue

            rotor_id = (
                f"rotor.axis_{attachment}_{center}.moving_"
                + "_".join(str(atom) for atom in moving_side)
            )
            candidates.append(
                PrimitiveRotor(
                    rotor_id=rotor_id,
                    axis_atoms=(attachment, center),
                    moving_side_atoms=moving_side,
                    owned_atoms=tuple(sorted(hydrogens)),
                    torsion_rows=tuple(valid_rows),
                    signature_rows=tuple(valid_rows),
                    signature_row_types=("proper_torsion",) * len(valid_rows),
                    signature_row_scales=(1.0,) * len(valid_rows),
                    row_orientations=tuple(orientations),
                    symmetry_order=3,
                    symmetry_operation_ids=(f"{rotor_id}.c3+1", f"{rotor_id}.c3+2"),
                    motion_kind="terminal_methyl",
                    equivalent_atom_groups=(hydrogen_group,),
                    rigid_symmetry_defect_bohr=rigid_symmetry_defect(
                        coordinates,
                        axis_atoms=(attachment, center),
                        moving_atoms=moving_side,
                        owned_atoms=hydrogen_group,
                        order=3,
                    ),
                )
            )

        if self.detect_group_rotors:
            candidates.extend(
                self._detect_c_o_group_rotors(
                    labels,
                    connectivity,
                    coordinates,
                    coordinate_definition,
                    coordinate_value_function,
                )
            )

        return tuple(sorted(candidates, key=lambda rotor: rotor.rotor_id))

    def _detect_c_o_group_rotors(
        self,
        labels,
        connectivity,
        coordinates,
        coordinate_definition,
        coordinate_value_function,
    ):
        """Detect C-O-C(H3) substituent rotation about the non-methyl C-O bond."""

        candidates = []
        for oxygen, label in enumerate(labels):
            if not label.upper().startswith("O"):
                continue
            neighbors = _neighbors(connectivity, oxygen)
            if len(neighbors) != 2:
                continue
            for methyl_center in neighbors:
                methyl = _terminal_methyl_atoms(labels, connectivity, methyl_center)
                if methyl is None or methyl[1] != oxygen:
                    continue
                hydrogens, _ = methyl
                stationary = neighbors[0] if neighbors[1] == methyl_center else neighbors[1]
                if not labels[stationary].upper().startswith("C"):
                    continue
                axis = (int(stationary), int(oxygen))
                if frozenset(axis) in self.excluded_axis_bonds:
                    continue
                if _bond_is_in_ring(connectivity, *axis):
                    continue
                moving_side = _component_after_cut(connectivity, oxygen, axis)
                expected = tuple(sorted((oxygen, methyl_center, *hydrogens)))
                if moving_side != expected:
                    continue
                rows, orientations = _oriented_torsion_rows(
                    coordinate_definition,
                    coordinate_value_function,
                    coordinates,
                    axis_atoms=axis,
                    moving_atoms=moving_side,
                    orientation_step=self.orientation_step,
                )
                if not rows:
                    continue
                rotor_id = (
                    f"group_rotor.axis_{axis[0]}_{axis[1]}.moving_"
                    + "_".join(str(atom) for atom in moving_side)
                )
                candidates.append(
                    PrimitiveRotor(
                        rotor_id=rotor_id,
                        axis_atoms=axis,
                        moving_side_atoms=moving_side,
                        owned_atoms=tuple(
                            atom for atom in moving_side if atom != oxygen
                        ),
                        torsion_rows=rows,
                        signature_rows=rows,
                        signature_row_types=("proper_torsion",) * len(rows),
                        signature_row_scales=(1.0,) * len(rows),
                        row_orientations=orientations,
                        symmetry_order=1,
                        symmetry_operation_ids=(),
                        motion_kind="group_rotation",
                        equivalent_atom_groups=(),
                    )
                )
        return tuple(candidates)
