//
//  Tabula — generated by TabulaCxxCodegen. Do not edit by hand.
//  Nuclear-attraction kernel tables — early-contraction (Q-into-V)
//  form interpreted by the shared three-phase engine.
//

#ifndef TabulaNuclearAttractionTable_hpp
#define TabulaNuclearAttractionTable_hpp

#include <cstdint>

namespace tabula {  // tabula namespace

namespace detail {  // detail namespace

/// @brief A pointer view of one (l_a, l_c) nuclear-attraction table.
/// Expanded-V entries carry the seed order, the µ / γ-over-ζ powers,
/// and the lifted Q-monomial; the M rows are a pure-R_AC polynomial
/// (`component, evIndex-lo, evIndex-hi, R_AC x/y/z`, six bytes/row).
struct NuclearTable
{
    int l_a, l_c;
    int ev_count, max_order, component_count, m_row_count;
    const std::uint8_t *ev_order, *ev_mu_power, *ev_goz_power, *ev_qx, *ev_qy, *ev_qz;
    const std::int8_t *component_bra_m, *component_ket_m;
    const std::uint8_t *m_fields;
    const double *m_coef;
};

/// @brief The nuclear-attraction table for an (l_a, l_c) pair, l = 0 … 4.
auto nuclear_table(int l_a, int l_c) -> const NuclearTable&;

}  // namespace detail

}  // namespace tabula

#endif /* TabulaNuclearAttractionTable_hpp */
