//
//  Tabula — custom-recursion molecular-integral machinery.
//  Two-center overlap fused kernel.
//

#ifndef TabulaOverlapKernel_hpp
#define TabulaOverlapKernel_hpp

#include "TabulaKernelBlockData.hpp"

namespace tabula {  // tabula namespace

/// @brief The fused two-center overlap kernel.
///
/// For one `(l_a, l_c)` block it runs the whole overlap evaluation — the
/// primitive-pair weight, the seed ladder, the primitive-pair contraction,
/// the single-centre MD recursion, and the Cartesian-to-spherical assembly —
/// directly from the bra/ket basis-function blocks. It loops the bra
/// contracted GTOs `[bra_begin, bra_end)` on the outside and tiles the ket
/// contracted GTOs on the inside; every intermediate is held in a tile-local
/// scratch, and the primitive-pair data is computed on the fly. The
/// per-`(l_a, l_c)` routines are generated by `TabulaCxxCodegen`; this
/// dispatches on the angular-momentum pair. Covers `l = 0 … 4`.
///
/// @param l_a The bra angular momentum.
/// @param l_c The ket angular momentum.
/// @param bra The bra basis-function block data.
/// @param bra_begin The first bra contracted-GTO index of the task range.
/// @param bra_end The one-past-last bra contracted-GTO index of the range.
/// @param ket The ket basis-function block data.
/// @param spherical The output spherical block — `(2l_a+1)·(2l_c+1)` rows of
/// `cdim = (bra_end−bra_begin)·ket.ncgtos` values, row stride padded to a
/// multiple of 8, component-major. The contracted pair `(i, j)` is column
/// `(i−bra_begin)·ket.ncgtos + j`.
auto overlap_kernel(const int               l_a,
                    const int               l_c,
                    const KernelBlockData  &bra,
                    const int               bra_begin,
                    const int               bra_end,
                    const KernelBlockData  &ket,
                    double                 *spherical) -> void;

}  // namespace tabula

#endif /* TabulaOverlapKernel_hpp */
