//
//  Tabula — custom-recursion molecular-integral machinery.
//  Two-center Coulomb fused kernel.
//

#ifndef TabulaCoulombKernel_hpp
#define TabulaCoulombKernel_hpp

#include "TabulaKernelBlockData.hpp"

namespace tabula {  // tabula namespace

/// @brief The fused two-center Coulomb kernel — `(a|b) = ∫∫ χ_a r₁₂⁻¹ χ_c`.
///
/// Shares the overlap kernel's structure (primitive-pair weight, seed ladder,
/// primitive contraction, single-centre MD recursion, Cartesian-to-spherical
/// assembly) and differs in the level-0 seed: Coulomb seeds the ladder with
/// `(−2ρ)^m·(2π/ρ)·F_m(T)`, `T = ρr²`, where `F_m` is the Boys function. As
/// `F_m` is scalar, the Coulomb seed phase is not vectorized over the ket
/// tile. The per-`(l_a, l_c)` routines are generated by `TabulaCxxCodegen`;
/// this dispatches on the angular-momentum pair. Covers `l = 0 … 4`.
///
/// @param l_a The bra angular momentum.
/// @param l_c The ket angular momentum.
/// @param bra The bra basis-function block data.
/// @param bra_begin The first bra contracted-GTO index of the task range.
/// @param bra_end The one-past-last bra contracted-GTO index of the range.
/// @param ket The ket basis-function block data.
/// @param spherical The output spherical block — `(2l_a+1)·(2l_c+1)` rows of
/// `cdim = (bra_end−bra_begin)·ket.ncgtos` values, row stride padded to a
/// multiple of 8, component-major. The contracted pair `(i, j)` is column
/// `(i−bra_begin)·ket.ncgtos + j`.
auto coulomb_kernel(const int               l_a,
                    const int               l_c,
                    const KernelBlockData  &bra,
                    const int               bra_begin,
                    const int               bra_end,
                    const KernelBlockData  &ket,
                    double                 *spherical) -> void;

}  // namespace tabula

#endif /* TabulaCoulombKernel_hpp */
