//
//  Tabula — generated by TabulaCxxCodegen. Do not edit by hand.
//  Charge-dipole table data — (axis, l_a, l_c) = (0, 0, 0).
//

#include "TabulaChargeDipoleTable.hpp"

#include <cstdint>

namespace tabula {  // tabula namespace

namespace detail {  // detail namespace

namespace {  // unnamed namespace

static constexpr std::uint8_t ev_order_0_0_0[] = {
    1,
};
static constexpr std::uint8_t ev_mu_0_0_0[] = {
    0,
};
static constexpr std::uint8_t ev_goz_0_0_0[] = {
    0,
};
static constexpr std::uint8_t ev_qx_0_0_0[] = {
    1,
};
static constexpr std::uint8_t ev_qy_0_0_0[] = {
    0,
};
static constexpr std::uint8_t ev_qz_0_0_0[] = {
    0,
};
static constexpr std::int8_t comp_bra_0_0_0[] = {
    0,
};
static constexpr std::int8_t comp_ket_0_0_0[] = {
    0,
};
static constexpr std::uint8_t mfields_0_0_0[] = {
    0,0,0,0,0,0,
};
static constexpr std::uint16_t mcoefidx_0_0_0[] = {
    0,
};

}  // namespace

auto
chargedipole_table_0_0_0() -> const ChargeDipoleTable&
{
    static constexpr ChargeDipoleTable t{0, 0, 1, 1, 1, 1,
        ev_order_0_0_0, ev_mu_0_0_0, ev_goz_0_0_0, ev_qx_0_0_0, ev_qy_0_0_0, ev_qz_0_0_0,
        comp_bra_0_0_0, comp_ket_0_0_0, mfields_0_0_0, mcoefidx_0_0_0};
    return t;
}

}  // namespace detail

}  // namespace tabula
