//
//  Tabula — generated by TabulaCxxCodegen. Do not edit by hand.
//  Nuclear-attraction table data — (l_a, l_c) = (0, 3).
//

#include "TabulaNuclearAttractionTable.hpp"

#include <cstdint>

namespace tabula {  // tabula namespace

namespace detail {  // detail namespace

namespace {  // unnamed namespace

static constexpr std::uint8_t ev_order_0_3[] = {
    0,1,1,1,2,2,2,2,2,2,3,3,3,3,3,3,3,3,3,3,
};
static constexpr std::uint8_t ev_mu_0_3[] = {
    3,2,2,2,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,
};
static constexpr std::uint8_t ev_goz_0_3[] = {
    0,1,1,1,2,2,2,2,2,2,3,3,3,3,3,3,3,3,3,3,
};
static constexpr std::uint8_t ev_qx_0_3[] = {
    0,0,0,1,0,0,0,1,1,2,0,0,0,0,1,1,1,2,2,3,
};
static constexpr std::uint8_t ev_qy_0_3[] = {
    0,0,1,0,0,1,2,0,1,0,0,1,2,3,0,1,2,0,1,0,
};
static constexpr std::uint8_t ev_qz_0_3[] = {
    0,1,0,0,2,1,0,1,0,0,3,2,1,0,2,1,0,1,0,0,
};
static constexpr std::int8_t comp_bra_0_3[] = {
    0,0,0,0,0,0,0,
};
static constexpr std::int8_t comp_ket_0_3[] = {
    -3,-2,-1,0,1,2,3,
};
static constexpr std::uint32_t mfields_0_3[] = {
    25165824,9437184,16777472,1048832,8913280,8389376,525312,8389760,1664,2304,143130625,8913025,
    134742273,142606721,524929,8389505,134218753,1921,276824066,25165826,9437186,142606466,268435714,16777474,
    1048834,8913282,8389122,134218370,8389378,525314,8389762,1410,1666,2306,402653187,150994947,
    135266307,268435587,16777347,1048707,142606595,134742403,134218243,8389251,134218499,525187,134218883,1283,
    1539,2179,268959748,17301508,1572868,134742148,8913156,268435844,16777604,1048964,524804,525060,
    134218628,8389636,525444,1796,2052,2436,150994949,135266309,16777349,1048709,142606597,134742405,
    8389253,134218501,525189,134218885,1541,2181,17301510,1572870,8913158,16777606,1048966,525062,
    8389638,525446,2054,2438,
};
static constexpr std::uint16_t mcoefidx_0_3[] = {
    11,12,13,14,12,15,14,16,17,18,19,20,20,20,21,21,21,22,23,24,24,23,25,26,
    27,24,28,25,29,27,30,31,32,32,33,34,34,35,36,36,34,34,37,36,38,36,38,2,
    39,39,23,24,24,23,24,25,27,26,28,30,25,27,29,31,32,32,40,20,41,21,40,20,
    41,42,21,22,43,44,45,46,45,13,14,15,13,16,47,48,
};

}  // namespace

auto
nuclear_table_0_3() -> const NuclearTable&
{
    static constexpr NuclearTable t{0, 3, 20, 3, 7, 88,
        ev_order_0_3, ev_mu_0_3, ev_goz_0_3, ev_qx_0_3, ev_qy_0_3, ev_qz_0_3,
        comp_bra_0_3, comp_ket_0_3, mfields_0_3, mcoefidx_0_3};
    return t;
}

}  // namespace detail

}  // namespace tabula
