//
//  Tabula — generated by TabulaCxxCodegen. Do not edit by hand.
//  Nuclear-attraction table data — (l_a, l_c) = (0, 1).
//

#include "TabulaNuclearAttractionTable.hpp"

#include <cstdint>

namespace tabula {  // tabula namespace

namespace detail {  // detail namespace

namespace {  // unnamed namespace

static constexpr std::uint8_t ev_order_0_1[] = {
    0,1,1,1,
};
static constexpr std::uint8_t ev_mu_0_1[] = {
    1,0,0,0,
};
static constexpr std::uint8_t ev_goz_0_1[] = {
    0,1,1,1,
};
static constexpr std::uint8_t ev_qx_0_1[] = {
    0,0,0,1,
};
static constexpr std::uint8_t ev_qy_0_1[] = {
    0,0,1,0,
};
static constexpr std::uint8_t ev_qz_0_1[] = {
    0,1,0,0,
};
static constexpr std::int8_t comp_bra_0_1[] = {
    0,0,0,
};
static constexpr std::int8_t comp_ket_0_1[] = {
    -1,0,1,
};
static constexpr std::uint32_t mfields_0_1[] = {
    8388608,256,134217729,129,524290,386,
};
static constexpr std::uint16_t mcoefidx_0_1[] = {
    1,2,1,2,1,2,
};

}  // namespace

auto
nuclear_table_0_1() -> const NuclearTable&
{
    static constexpr NuclearTable t{0, 1, 4, 1, 3, 6,
        ev_order_0_1, ev_mu_0_1, ev_goz_0_1, ev_qx_0_1, ev_qy_0_1, ev_qz_0_1,
        comp_bra_0_1, comp_ket_0_1, mfields_0_1, mcoefidx_0_1};
    return t;
}

}  // namespace detail

}  // namespace tabula
