//
//  Tabula — generated by TabulaCxxCodegen. Do not edit by hand.
//  Two-center kinetic kernel dispatch.
//

#include "TabulaKineticKernel.hpp"

#include <vector>

#include "TabulaKineticKernelTable.hpp"

namespace tabula {  // tabula namespace

namespace detail {  // detail namespace

// the fused kernels' tile-local scratch — grow-only, thread-local
thread_local std::vector<double> g_kinetic_scratch;

}  // namespace detail

auto
kinetic_kernel(const int l_a, const int l_c, const KernelBlockData& bra, const int bra_begin, const int bra_end,
               const KernelBlockData& ket, double* spherical) -> void
{
    switch (l_a * 5 + l_c)
    {
        case 0: detail::kinetic_kernel_0_0(bra, bra_begin, bra_end, ket, spherical); break;
        case 1: detail::kinetic_kernel_0_1(bra, bra_begin, bra_end, ket, spherical); break;
        case 2: detail::kinetic_kernel_0_2(bra, bra_begin, bra_end, ket, spherical); break;
        case 3: detail::kinetic_kernel_0_3(bra, bra_begin, bra_end, ket, spherical); break;
        case 4: detail::kinetic_kernel_0_4(bra, bra_begin, bra_end, ket, spherical); break;
        case 5: detail::kinetic_kernel_1_0(bra, bra_begin, bra_end, ket, spherical); break;
        case 6: detail::kinetic_kernel_1_1(bra, bra_begin, bra_end, ket, spherical); break;
        case 7: detail::kinetic_kernel_1_2(bra, bra_begin, bra_end, ket, spherical); break;
        case 8: detail::kinetic_kernel_1_3(bra, bra_begin, bra_end, ket, spherical); break;
        case 9: detail::kinetic_kernel_1_4(bra, bra_begin, bra_end, ket, spherical); break;
        case 10: detail::kinetic_kernel_2_0(bra, bra_begin, bra_end, ket, spherical); break;
        case 11: detail::kinetic_kernel_2_1(bra, bra_begin, bra_end, ket, spherical); break;
        case 12: detail::kinetic_kernel_2_2(bra, bra_begin, bra_end, ket, spherical); break;
        case 13: detail::kinetic_kernel_2_3(bra, bra_begin, bra_end, ket, spherical); break;
        case 14: detail::kinetic_kernel_2_4(bra, bra_begin, bra_end, ket, spherical); break;
        case 15: detail::kinetic_kernel_3_0(bra, bra_begin, bra_end, ket, spherical); break;
        case 16: detail::kinetic_kernel_3_1(bra, bra_begin, bra_end, ket, spherical); break;
        case 17: detail::kinetic_kernel_3_2(bra, bra_begin, bra_end, ket, spherical); break;
        case 18: detail::kinetic_kernel_3_3(bra, bra_begin, bra_end, ket, spherical); break;
        case 19: detail::kinetic_kernel_3_4(bra, bra_begin, bra_end, ket, spherical); break;
        case 20: detail::kinetic_kernel_4_0(bra, bra_begin, bra_end, ket, spherical); break;
        case 21: detail::kinetic_kernel_4_1(bra, bra_begin, bra_end, ket, spherical); break;
        case 22: detail::kinetic_kernel_4_2(bra, bra_begin, bra_end, ket, spherical); break;
        case 23: detail::kinetic_kernel_4_3(bra, bra_begin, bra_end, ket, spherical); break;
        case 24: detail::kinetic_kernel_4_4(bra, bra_begin, bra_end, ket, spherical); break;
        default: break;
    }
}

}  // namespace tabula
