//
//  Tabula — generated by TabulaCxxCodegen. Do not edit by hand.
//  Nuclear-attraction table dispatch.
//

#include "TabulaNuclearAttractionTable.hpp"

namespace tabula {  // tabula namespace

namespace detail {  // detail namespace

auto nuclear_table_0_0() -> const NuclearTable&;
auto nuclear_table_0_1() -> const NuclearTable&;
auto nuclear_table_0_2() -> const NuclearTable&;
auto nuclear_table_0_3() -> const NuclearTable&;
auto nuclear_table_0_4() -> const NuclearTable&;
auto nuclear_table_1_0() -> const NuclearTable&;
auto nuclear_table_1_1() -> const NuclearTable&;
auto nuclear_table_1_2() -> const NuclearTable&;
auto nuclear_table_1_3() -> const NuclearTable&;
auto nuclear_table_1_4() -> const NuclearTable&;
auto nuclear_table_2_0() -> const NuclearTable&;
auto nuclear_table_2_1() -> const NuclearTable&;
auto nuclear_table_2_2() -> const NuclearTable&;
auto nuclear_table_2_3() -> const NuclearTable&;
auto nuclear_table_2_4() -> const NuclearTable&;
auto nuclear_table_3_0() -> const NuclearTable&;
auto nuclear_table_3_1() -> const NuclearTable&;
auto nuclear_table_3_2() -> const NuclearTable&;
auto nuclear_table_3_3() -> const NuclearTable&;
auto nuclear_table_3_4() -> const NuclearTable&;
auto nuclear_table_4_0() -> const NuclearTable&;
auto nuclear_table_4_1() -> const NuclearTable&;
auto nuclear_table_4_2() -> const NuclearTable&;
auto nuclear_table_4_3() -> const NuclearTable&;
auto nuclear_table_4_4() -> const NuclearTable&;

auto
nuclear_table(const int l_a, const int l_c) -> const NuclearTable&
{
    switch (l_a * 5 + l_c)
    {
        case 0: return nuclear_table_0_0();
        case 1: return nuclear_table_0_1();
        case 2: return nuclear_table_0_2();
        case 3: return nuclear_table_0_3();
        case 4: return nuclear_table_0_4();
        case 5: return nuclear_table_1_0();
        case 6: return nuclear_table_1_1();
        case 7: return nuclear_table_1_2();
        case 8: return nuclear_table_1_3();
        case 9: return nuclear_table_1_4();
        case 10: return nuclear_table_2_0();
        case 11: return nuclear_table_2_1();
        case 12: return nuclear_table_2_2();
        case 13: return nuclear_table_2_3();
        case 14: return nuclear_table_2_4();
        case 15: return nuclear_table_3_0();
        case 16: return nuclear_table_3_1();
        case 17: return nuclear_table_3_2();
        case 18: return nuclear_table_3_3();
        case 19: return nuclear_table_3_4();
        case 20: return nuclear_table_4_0();
        case 21: return nuclear_table_4_1();
        case 22: return nuclear_table_4_2();
        case 23: return nuclear_table_4_3();
        case 24: return nuclear_table_4_4();
        default: return nuclear_table_0_0();
    }
}

}  // namespace detail

}  // namespace tabula
