//
//  Tabula — generated by TabulaCxxCodegen. Do not edit by hand.
//  Two-center kinetic fused kernel — (l_a, l_c) = (3, 4).
//

#include "TabulaKineticKernel.hpp"

#include <cmath>
#include <cstddef>
#include <vector>

#include "MathConst.hpp"
#include "TabulaKineticKernelTable.hpp"

namespace tabula {  // tabula namespace

namespace detail {  // detail namespace

auto
kinetic_kernel_3_4(const KernelBlockData& bra, const int bra_begin, const int bra_end,
                          const KernelBlockData& ket, double* spherical) -> void
{
    const double fpi = mathconst::pi_value();
    const std::size_t cdim =
        static_cast<std::size_t>(bra_end - bra_begin) * static_cast<std::size_t>(ket.ncgtos);
    const auto stride = ((cdim + 7) / 8) * 8;
    constexpr std::size_t tile = 512;

    if (g_kinetic_scratch.size() < 330 * tile) g_kinetic_scratch.resize(330 * tile);
    auto* s = g_kinetic_scratch.data();

    double acx[tile];
    double acy[tile];
    double acz[tile];

    // the bra contracted GTOs on the outside; the ket contracted GTOs
    // tiled on the inside, the tile the SIMD axis
    for (int i = bra_begin; i < bra_end; i++)
    {
        const double bx = bra.x[i];
        const double by = bra.y[i];
        const double bz = bra.z[i];
        const std::size_t ij_base = static_cast<std::size_t>(i - bra_begin) * static_cast<std::size_t>(ket.ncgtos);

        for (int j0 = 0; j0 < ket.ncgtos; j0 += static_cast<int>(tile))
        {
            const std::size_t w =
                (j0 + static_cast<int>(tile) < ket.ncgtos) ? tile : static_cast<std::size_t>(ket.ncgtos - j0);

            // AC = A − C, per ket contracted GTO of the tile
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
            {
                acx[jj] = bx - ket.x[j0 + jj];
                acy[jj] = by - ket.y[j0 + jj];
                acz[jj] = bz - ket.z[j0 + jj];
            }

            // (1) the contracted seed ladder [0]^m
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++) s[0 + jj] = 0.0;
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++) s[512 + jj] = 0.0;
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++) s[1024 + jj] = 0.0;
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++) s[1536 + jj] = 0.0;
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++) s[2048 + jj] = 0.0;
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++) s[2560 + jj] = 0.0;
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++) s[3072 + jj] = 0.0;
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++) s[3584 + jj] = 0.0;
            for (int kb = 0; kb < bra.nprims; kb++)
            {
                const double a  = bra.exponents[static_cast<std::size_t>(kb) * bra.ncgtos + i];
                const double bn = bra.norms[static_cast<std::size_t>(kb) * bra.ncgtos + i];
                const double ia = 0.5 / a;
                for (int lk = 0; lk < ket.nprims; lk++)
                {
                    const double* ke = ket.exponents + static_cast<std::size_t>(lk) * ket.ncgtos + j0;
                    const double* kn = ket.norms + static_cast<std::size_t>(lk) * ket.ncgtos + j0;
#pragma omp simd
                    for (std::size_t jj = 0; jj < w; jj++)
                    {
                        const double g    = ke[jj];
                        const double ig   = -0.5 / g;
                        const double fe   = 1.0 / (a + g);
                        const double fz   = a * g * fe;
                        const double fact = fpi * fe;
                        const double r2   = acx[jj] * acx[jj] + acy[jj] * acy[jj] + acz[jj] * acz[jj];
                        const double wgt  = bn * kn[jj] * fact * std::sqrt(fact) * std::exp(-fz * r2);
                        double t = wgt * ia * ia * ia * ig * ig * ig * ig;
                        const double kt2 = 2.0 * fz * r2;
                        s[0 + jj] += t * fz * (3.0 - kt2);
                        const double f = -2.0 * a * g / (a + g);
                        t *= f;
                        s[512 + jj] += t * fz * (5.0 - kt2);
                        t *= f;
                        s[1024 + jj] += t * fz * (7.0 - kt2);
                        t *= f;
                        s[1536 + jj] += t * fz * (9.0 - kt2);
                        t *= f;
                        s[2048 + jj] += t * fz * (11.0 - kt2);
                        t *= f;
                        s[2560 + jj] += t * fz * (13.0 - kt2);
                        t *= f;
                        s[3072 + jj] += t * fz * (15.0 - kt2);
                        t *= f;
                        s[3584 + jj] += t * fz * (17.0 - kt2);
                    }
                }
            }

            // (2) the single-centre MD recursion [r]^0
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[4096 + jj] = acx[jj] * s[512 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[4608 + jj] = acx[jj] * s[1024 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[5120 + jj] = acx[jj] * s[1536 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[5632 + jj] = acx[jj] * s[2048 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[6144 + jj] = acx[jj] * s[2560 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[6656 + jj] = acx[jj] * s[3072 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[7168 + jj] = acx[jj] * s[3584 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[7680 + jj] = acy[jj] * s[512 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[8192 + jj] = acy[jj] * s[1024 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[8704 + jj] = acy[jj] * s[1536 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[9216 + jj] = acy[jj] * s[2048 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[9728 + jj] = acy[jj] * s[2560 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[10240 + jj] = acy[jj] * s[3072 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[10752 + jj] = acy[jj] * s[3584 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[11264 + jj] = acz[jj] * s[512 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[11776 + jj] = acz[jj] * s[1024 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[12288 + jj] = acz[jj] * s[1536 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[12800 + jj] = acz[jj] * s[2048 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[13312 + jj] = acz[jj] * s[2560 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[13824 + jj] = acz[jj] * s[3072 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[14336 + jj] = acz[jj] * s[3584 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[14848 + jj] = acx[jj] * s[4608 + jj] + 1.0 * s[512 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[15360 + jj] = acx[jj] * s[5120 + jj] + 1.0 * s[1024 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[15872 + jj] = acx[jj] * s[5632 + jj] + 1.0 * s[1536 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[16384 + jj] = acx[jj] * s[6144 + jj] + 1.0 * s[2048 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[16896 + jj] = acx[jj] * s[6656 + jj] + 1.0 * s[2560 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[17408 + jj] = acx[jj] * s[7168 + jj] + 1.0 * s[3072 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[17920 + jj] = acx[jj] * s[8192 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[18432 + jj] = acx[jj] * s[8704 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[18944 + jj] = acx[jj] * s[9216 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[19456 + jj] = acx[jj] * s[9728 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[19968 + jj] = acx[jj] * s[10240 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[20480 + jj] = acx[jj] * s[10752 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[20992 + jj] = acx[jj] * s[11776 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[21504 + jj] = acx[jj] * s[12288 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[22016 + jj] = acx[jj] * s[12800 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[22528 + jj] = acx[jj] * s[13312 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[23040 + jj] = acx[jj] * s[13824 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[23552 + jj] = acx[jj] * s[14336 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[24064 + jj] = acy[jj] * s[8192 + jj] + 1.0 * s[512 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[24576 + jj] = acy[jj] * s[8704 + jj] + 1.0 * s[1024 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[25088 + jj] = acy[jj] * s[9216 + jj] + 1.0 * s[1536 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[25600 + jj] = acy[jj] * s[9728 + jj] + 1.0 * s[2048 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[26112 + jj] = acy[jj] * s[10240 + jj] + 1.0 * s[2560 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[26624 + jj] = acy[jj] * s[10752 + jj] + 1.0 * s[3072 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[27136 + jj] = acy[jj] * s[11776 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[27648 + jj] = acy[jj] * s[12288 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[28160 + jj] = acy[jj] * s[12800 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[28672 + jj] = acy[jj] * s[13312 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[29184 + jj] = acy[jj] * s[13824 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[29696 + jj] = acy[jj] * s[14336 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[30208 + jj] = acz[jj] * s[11776 + jj] + 1.0 * s[512 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[30720 + jj] = acz[jj] * s[12288 + jj] + 1.0 * s[1024 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[31232 + jj] = acz[jj] * s[12800 + jj] + 1.0 * s[1536 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[31744 + jj] = acz[jj] * s[13312 + jj] + 1.0 * s[2048 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[32256 + jj] = acz[jj] * s[13824 + jj] + 1.0 * s[2560 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[32768 + jj] = acz[jj] * s[14336 + jj] + 1.0 * s[3072 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[33280 + jj] = acx[jj] * s[15360 + jj] + 2.0 * s[4608 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[33792 + jj] = acx[jj] * s[15872 + jj] + 2.0 * s[5120 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[34304 + jj] = acx[jj] * s[16384 + jj] + 2.0 * s[5632 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[34816 + jj] = acx[jj] * s[16896 + jj] + 2.0 * s[6144 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[35328 + jj] = acx[jj] * s[17408 + jj] + 2.0 * s[6656 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[35840 + jj] = acx[jj] * s[18432 + jj] + 1.0 * s[8192 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[36352 + jj] = acx[jj] * s[18944 + jj] + 1.0 * s[8704 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[36864 + jj] = acx[jj] * s[19456 + jj] + 1.0 * s[9216 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[37376 + jj] = acx[jj] * s[19968 + jj] + 1.0 * s[9728 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[37888 + jj] = acx[jj] * s[20480 + jj] + 1.0 * s[10240 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[38400 + jj] = acx[jj] * s[21504 + jj] + 1.0 * s[11776 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[38912 + jj] = acx[jj] * s[22016 + jj] + 1.0 * s[12288 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[39424 + jj] = acx[jj] * s[22528 + jj] + 1.0 * s[12800 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[39936 + jj] = acx[jj] * s[23040 + jj] + 1.0 * s[13312 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[40448 + jj] = acx[jj] * s[23552 + jj] + 1.0 * s[13824 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[40960 + jj] = acx[jj] * s[24576 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[41472 + jj] = acx[jj] * s[25088 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[41984 + jj] = acx[jj] * s[25600 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[42496 + jj] = acx[jj] * s[26112 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[43008 + jj] = acx[jj] * s[26624 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[43520 + jj] = acx[jj] * s[27648 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[44032 + jj] = acx[jj] * s[28160 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[44544 + jj] = acx[jj] * s[28672 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[45056 + jj] = acx[jj] * s[29184 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[45568 + jj] = acx[jj] * s[29696 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[46080 + jj] = acx[jj] * s[30720 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[46592 + jj] = acx[jj] * s[31232 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[47104 + jj] = acx[jj] * s[31744 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[47616 + jj] = acx[jj] * s[32256 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[48128 + jj] = acx[jj] * s[32768 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[48640 + jj] = acy[jj] * s[24576 + jj] + 2.0 * s[8192 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[49152 + jj] = acy[jj] * s[25088 + jj] + 2.0 * s[8704 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[49664 + jj] = acy[jj] * s[25600 + jj] + 2.0 * s[9216 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[50176 + jj] = acy[jj] * s[26112 + jj] + 2.0 * s[9728 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[50688 + jj] = acy[jj] * s[26624 + jj] + 2.0 * s[10240 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[51200 + jj] = acy[jj] * s[27648 + jj] + 1.0 * s[11776 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[51712 + jj] = acy[jj] * s[28160 + jj] + 1.0 * s[12288 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[52224 + jj] = acy[jj] * s[28672 + jj] + 1.0 * s[12800 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[52736 + jj] = acy[jj] * s[29184 + jj] + 1.0 * s[13312 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[53248 + jj] = acy[jj] * s[29696 + jj] + 1.0 * s[13824 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[53760 + jj] = acy[jj] * s[30720 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[54272 + jj] = acy[jj] * s[31232 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[54784 + jj] = acy[jj] * s[31744 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[55296 + jj] = acy[jj] * s[32256 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[55808 + jj] = acy[jj] * s[32768 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[56320 + jj] = acz[jj] * s[30720 + jj] + 2.0 * s[11776 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[56832 + jj] = acz[jj] * s[31232 + jj] + 2.0 * s[12288 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[57344 + jj] = acz[jj] * s[31744 + jj] + 2.0 * s[12800 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[57856 + jj] = acz[jj] * s[32256 + jj] + 2.0 * s[13312 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[58368 + jj] = acz[jj] * s[32768 + jj] + 2.0 * s[13824 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[58880 + jj] = acx[jj] * s[33792 + jj] + 3.0 * s[15360 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[59392 + jj] = acx[jj] * s[34304 + jj] + 3.0 * s[15872 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[59904 + jj] = acx[jj] * s[34816 + jj] + 3.0 * s[16384 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[60416 + jj] = acx[jj] * s[35328 + jj] + 3.0 * s[16896 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[60928 + jj] = acx[jj] * s[36352 + jj] + 2.0 * s[18432 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[61440 + jj] = acx[jj] * s[36864 + jj] + 2.0 * s[18944 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[61952 + jj] = acx[jj] * s[37376 + jj] + 2.0 * s[19456 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[62464 + jj] = acx[jj] * s[37888 + jj] + 2.0 * s[19968 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[62976 + jj] = acx[jj] * s[38912 + jj] + 2.0 * s[21504 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[63488 + jj] = acx[jj] * s[39424 + jj] + 2.0 * s[22016 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[64000 + jj] = acx[jj] * s[39936 + jj] + 2.0 * s[22528 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[64512 + jj] = acx[jj] * s[40448 + jj] + 2.0 * s[23040 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[65024 + jj] = acx[jj] * s[41472 + jj] + 1.0 * s[24576 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[65536 + jj] = acx[jj] * s[41984 + jj] + 1.0 * s[25088 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[66048 + jj] = acx[jj] * s[42496 + jj] + 1.0 * s[25600 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[66560 + jj] = acx[jj] * s[43008 + jj] + 1.0 * s[26112 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[67072 + jj] = acx[jj] * s[44032 + jj] + 1.0 * s[27648 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[67584 + jj] = acx[jj] * s[44544 + jj] + 1.0 * s[28160 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[68096 + jj] = acx[jj] * s[45056 + jj] + 1.0 * s[28672 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[68608 + jj] = acx[jj] * s[45568 + jj] + 1.0 * s[29184 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[69120 + jj] = acx[jj] * s[46592 + jj] + 1.0 * s[30720 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[69632 + jj] = acx[jj] * s[47104 + jj] + 1.0 * s[31232 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[70144 + jj] = acx[jj] * s[47616 + jj] + 1.0 * s[31744 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[70656 + jj] = acx[jj] * s[48128 + jj] + 1.0 * s[32256 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[71168 + jj] = acx[jj] * s[49152 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[71680 + jj] = acx[jj] * s[49664 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[72192 + jj] = acx[jj] * s[50176 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[72704 + jj] = acx[jj] * s[50688 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[73216 + jj] = acx[jj] * s[51712 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[73728 + jj] = acx[jj] * s[52224 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[74240 + jj] = acx[jj] * s[52736 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[74752 + jj] = acx[jj] * s[53248 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[75264 + jj] = acx[jj] * s[54272 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[75776 + jj] = acx[jj] * s[54784 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[76288 + jj] = acx[jj] * s[55296 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[76800 + jj] = acx[jj] * s[55808 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[77312 + jj] = acx[jj] * s[56832 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[77824 + jj] = acx[jj] * s[57344 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[78336 + jj] = acx[jj] * s[57856 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[78848 + jj] = acx[jj] * s[58368 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[79360 + jj] = acy[jj] * s[49152 + jj] + 3.0 * s[24576 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[79872 + jj] = acy[jj] * s[49664 + jj] + 3.0 * s[25088 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[80384 + jj] = acy[jj] * s[50176 + jj] + 3.0 * s[25600 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[80896 + jj] = acy[jj] * s[50688 + jj] + 3.0 * s[26112 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[81408 + jj] = acy[jj] * s[51712 + jj] + 2.0 * s[27648 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[81920 + jj] = acy[jj] * s[52224 + jj] + 2.0 * s[28160 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[82432 + jj] = acy[jj] * s[52736 + jj] + 2.0 * s[28672 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[82944 + jj] = acy[jj] * s[53248 + jj] + 2.0 * s[29184 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[83456 + jj] = acy[jj] * s[54272 + jj] + 1.0 * s[30720 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[83968 + jj] = acy[jj] * s[54784 + jj] + 1.0 * s[31232 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[84480 + jj] = acy[jj] * s[55296 + jj] + 1.0 * s[31744 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[84992 + jj] = acy[jj] * s[55808 + jj] + 1.0 * s[32256 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[85504 + jj] = acy[jj] * s[56832 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[86016 + jj] = acy[jj] * s[57344 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[86528 + jj] = acy[jj] * s[57856 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[87040 + jj] = acy[jj] * s[58368 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[87552 + jj] = acz[jj] * s[56832 + jj] + 3.0 * s[30720 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[88064 + jj] = acz[jj] * s[57344 + jj] + 3.0 * s[31232 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[88576 + jj] = acz[jj] * s[57856 + jj] + 3.0 * s[31744 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[89088 + jj] = acz[jj] * s[58368 + jj] + 3.0 * s[32256 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[89600 + jj] = acx[jj] * s[59392 + jj] + 4.0 * s[33792 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[90112 + jj] = acx[jj] * s[59904 + jj] + 4.0 * s[34304 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[90624 + jj] = acx[jj] * s[60416 + jj] + 4.0 * s[34816 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[91136 + jj] = acx[jj] * s[61440 + jj] + 3.0 * s[36352 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[91648 + jj] = acx[jj] * s[61952 + jj] + 3.0 * s[36864 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[92160 + jj] = acx[jj] * s[62464 + jj] + 3.0 * s[37376 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[92672 + jj] = acx[jj] * s[63488 + jj] + 3.0 * s[38912 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[93184 + jj] = acx[jj] * s[64000 + jj] + 3.0 * s[39424 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[93696 + jj] = acx[jj] * s[64512 + jj] + 3.0 * s[39936 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[94208 + jj] = acx[jj] * s[65536 + jj] + 2.0 * s[41472 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[94720 + jj] = acx[jj] * s[66048 + jj] + 2.0 * s[41984 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[95232 + jj] = acx[jj] * s[66560 + jj] + 2.0 * s[42496 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[95744 + jj] = acx[jj] * s[67584 + jj] + 2.0 * s[44032 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[96256 + jj] = acx[jj] * s[68096 + jj] + 2.0 * s[44544 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[96768 + jj] = acx[jj] * s[68608 + jj] + 2.0 * s[45056 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[97280 + jj] = acx[jj] * s[69632 + jj] + 2.0 * s[46592 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[97792 + jj] = acx[jj] * s[70144 + jj] + 2.0 * s[47104 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[98304 + jj] = acx[jj] * s[70656 + jj] + 2.0 * s[47616 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[98816 + jj] = acx[jj] * s[71680 + jj] + 1.0 * s[49152 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[99328 + jj] = acx[jj] * s[72192 + jj] + 1.0 * s[49664 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[99840 + jj] = acx[jj] * s[72704 + jj] + 1.0 * s[50176 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[100352 + jj] = acx[jj] * s[73728 + jj] + 1.0 * s[51712 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[100864 + jj] = acx[jj] * s[74240 + jj] + 1.0 * s[52224 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[101376 + jj] = acx[jj] * s[74752 + jj] + 1.0 * s[52736 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[101888 + jj] = acx[jj] * s[75776 + jj] + 1.0 * s[54272 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[102400 + jj] = acx[jj] * s[76288 + jj] + 1.0 * s[54784 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[102912 + jj] = acx[jj] * s[76800 + jj] + 1.0 * s[55296 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[103424 + jj] = acx[jj] * s[77824 + jj] + 1.0 * s[56832 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[103936 + jj] = acx[jj] * s[78336 + jj] + 1.0 * s[57344 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[104448 + jj] = acx[jj] * s[78848 + jj] + 1.0 * s[57856 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[104960 + jj] = acx[jj] * s[79872 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[105472 + jj] = acx[jj] * s[80384 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[105984 + jj] = acx[jj] * s[80896 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[106496 + jj] = acx[jj] * s[81920 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[107008 + jj] = acx[jj] * s[82432 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[107520 + jj] = acx[jj] * s[82944 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[108032 + jj] = acx[jj] * s[83968 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[108544 + jj] = acx[jj] * s[84480 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[109056 + jj] = acx[jj] * s[84992 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[109568 + jj] = acx[jj] * s[86016 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[110080 + jj] = acx[jj] * s[86528 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[110592 + jj] = acx[jj] * s[87040 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[111104 + jj] = acx[jj] * s[88064 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[111616 + jj] = acx[jj] * s[88576 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[112128 + jj] = acx[jj] * s[89088 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[112640 + jj] = acy[jj] * s[79872 + jj] + 4.0 * s[49152 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[113152 + jj] = acy[jj] * s[80384 + jj] + 4.0 * s[49664 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[113664 + jj] = acy[jj] * s[80896 + jj] + 4.0 * s[50176 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[114176 + jj] = acy[jj] * s[81920 + jj] + 3.0 * s[51712 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[114688 + jj] = acy[jj] * s[82432 + jj] + 3.0 * s[52224 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[115200 + jj] = acy[jj] * s[82944 + jj] + 3.0 * s[52736 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[115712 + jj] = acy[jj] * s[83968 + jj] + 2.0 * s[54272 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[116224 + jj] = acy[jj] * s[84480 + jj] + 2.0 * s[54784 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[116736 + jj] = acy[jj] * s[84992 + jj] + 2.0 * s[55296 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[117248 + jj] = acy[jj] * s[86016 + jj] + 1.0 * s[56832 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[117760 + jj] = acy[jj] * s[86528 + jj] + 1.0 * s[57344 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[118272 + jj] = acy[jj] * s[87040 + jj] + 1.0 * s[57856 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[118784 + jj] = acy[jj] * s[88064 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[119296 + jj] = acy[jj] * s[88576 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[119808 + jj] = acy[jj] * s[89088 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[120320 + jj] = acz[jj] * s[88064 + jj] + 4.0 * s[56832 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[120832 + jj] = acz[jj] * s[88576 + jj] + 4.0 * s[57344 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[121344 + jj] = acz[jj] * s[89088 + jj] + 4.0 * s[57856 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[121856 + jj] = acx[jj] * s[90112 + jj] + 5.0 * s[59392 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[122368 + jj] = acx[jj] * s[90624 + jj] + 5.0 * s[59904 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[122880 + jj] = acx[jj] * s[91648 + jj] + 4.0 * s[61440 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[123392 + jj] = acx[jj] * s[92160 + jj] + 4.0 * s[61952 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[123904 + jj] = acx[jj] * s[93184 + jj] + 4.0 * s[63488 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[124416 + jj] = acx[jj] * s[93696 + jj] + 4.0 * s[64000 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[124928 + jj] = acx[jj] * s[94720 + jj] + 3.0 * s[65536 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[125440 + jj] = acx[jj] * s[95232 + jj] + 3.0 * s[66048 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[125952 + jj] = acx[jj] * s[96256 + jj] + 3.0 * s[67584 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[126464 + jj] = acx[jj] * s[96768 + jj] + 3.0 * s[68096 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[126976 + jj] = acx[jj] * s[97792 + jj] + 3.0 * s[69632 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[127488 + jj] = acx[jj] * s[98304 + jj] + 3.0 * s[70144 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[128000 + jj] = acx[jj] * s[99328 + jj] + 2.0 * s[71680 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[128512 + jj] = acx[jj] * s[99840 + jj] + 2.0 * s[72192 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[129024 + jj] = acx[jj] * s[100864 + jj] + 2.0 * s[73728 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[129536 + jj] = acx[jj] * s[101376 + jj] + 2.0 * s[74240 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[130048 + jj] = acx[jj] * s[102400 + jj] + 2.0 * s[75776 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[130560 + jj] = acx[jj] * s[102912 + jj] + 2.0 * s[76288 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[131072 + jj] = acx[jj] * s[103936 + jj] + 2.0 * s[77824 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[131584 + jj] = acx[jj] * s[104448 + jj] + 2.0 * s[78336 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[132096 + jj] = acx[jj] * s[105472 + jj] + 1.0 * s[79872 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[132608 + jj] = acx[jj] * s[105984 + jj] + 1.0 * s[80384 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[133120 + jj] = acx[jj] * s[107008 + jj] + 1.0 * s[81920 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[133632 + jj] = acx[jj] * s[107520 + jj] + 1.0 * s[82432 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[134144 + jj] = acx[jj] * s[108544 + jj] + 1.0 * s[83968 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[134656 + jj] = acx[jj] * s[109056 + jj] + 1.0 * s[84480 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[135168 + jj] = acx[jj] * s[110080 + jj] + 1.0 * s[86016 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[135680 + jj] = acx[jj] * s[110592 + jj] + 1.0 * s[86528 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[136192 + jj] = acx[jj] * s[111616 + jj] + 1.0 * s[88064 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[136704 + jj] = acx[jj] * s[112128 + jj] + 1.0 * s[88576 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[137216 + jj] = acx[jj] * s[113152 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[137728 + jj] = acx[jj] * s[113664 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[138240 + jj] = acx[jj] * s[114688 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[138752 + jj] = acx[jj] * s[115200 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[139264 + jj] = acx[jj] * s[116224 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[139776 + jj] = acx[jj] * s[116736 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[140288 + jj] = acx[jj] * s[117760 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[140800 + jj] = acx[jj] * s[118272 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[141312 + jj] = acx[jj] * s[119296 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[141824 + jj] = acx[jj] * s[119808 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[142336 + jj] = acx[jj] * s[120832 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[142848 + jj] = acx[jj] * s[121344 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[143360 + jj] = acy[jj] * s[113152 + jj] + 5.0 * s[79872 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[143872 + jj] = acy[jj] * s[113664 + jj] + 5.0 * s[80384 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[144384 + jj] = acy[jj] * s[114688 + jj] + 4.0 * s[81920 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[144896 + jj] = acy[jj] * s[115200 + jj] + 4.0 * s[82432 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[145408 + jj] = acy[jj] * s[116224 + jj] + 3.0 * s[83968 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[145920 + jj] = acy[jj] * s[116736 + jj] + 3.0 * s[84480 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[146432 + jj] = acy[jj] * s[117760 + jj] + 2.0 * s[86016 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[146944 + jj] = acy[jj] * s[118272 + jj] + 2.0 * s[86528 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[147456 + jj] = acy[jj] * s[119296 + jj] + 1.0 * s[88064 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[147968 + jj] = acy[jj] * s[119808 + jj] + 1.0 * s[88576 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[148480 + jj] = acy[jj] * s[120832 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[148992 + jj] = acy[jj] * s[121344 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[149504 + jj] = acz[jj] * s[120832 + jj] + 5.0 * s[88064 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[150016 + jj] = acz[jj] * s[121344 + jj] + 5.0 * s[88576 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[150528 + jj] = acx[jj] * s[122368 + jj] + 6.0 * s[90112 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[151040 + jj] = acx[jj] * s[123392 + jj] + 5.0 * s[91648 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[151552 + jj] = acx[jj] * s[124416 + jj] + 5.0 * s[93184 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[152064 + jj] = acx[jj] * s[125440 + jj] + 4.0 * s[94720 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[152576 + jj] = acx[jj] * s[126464 + jj] + 4.0 * s[96256 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[153088 + jj] = acx[jj] * s[127488 + jj] + 4.0 * s[97792 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[153600 + jj] = acx[jj] * s[128512 + jj] + 3.0 * s[99328 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[154112 + jj] = acx[jj] * s[129536 + jj] + 3.0 * s[100864 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[154624 + jj] = acx[jj] * s[130560 + jj] + 3.0 * s[102400 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[155136 + jj] = acx[jj] * s[131584 + jj] + 3.0 * s[103936 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[155648 + jj] = acx[jj] * s[132608 + jj] + 2.0 * s[105472 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[156160 + jj] = acx[jj] * s[133632 + jj] + 2.0 * s[107008 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[156672 + jj] = acx[jj] * s[134656 + jj] + 2.0 * s[108544 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[157184 + jj] = acx[jj] * s[135680 + jj] + 2.0 * s[110080 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[157696 + jj] = acx[jj] * s[136704 + jj] + 2.0 * s[111616 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[158208 + jj] = acx[jj] * s[137728 + jj] + 1.0 * s[113152 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[158720 + jj] = acx[jj] * s[138752 + jj] + 1.0 * s[114688 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[159232 + jj] = acx[jj] * s[139776 + jj] + 1.0 * s[116224 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[159744 + jj] = acx[jj] * s[140800 + jj] + 1.0 * s[117760 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[160256 + jj] = acx[jj] * s[141824 + jj] + 1.0 * s[119296 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[160768 + jj] = acx[jj] * s[142848 + jj] + 1.0 * s[120832 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[161280 + jj] = acx[jj] * s[143872 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[161792 + jj] = acx[jj] * s[144896 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[162304 + jj] = acx[jj] * s[145920 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[162816 + jj] = acx[jj] * s[146944 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[163328 + jj] = acx[jj] * s[147968 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[163840 + jj] = acx[jj] * s[148992 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[164352 + jj] = acx[jj] * s[150016 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[164864 + jj] = acy[jj] * s[143872 + jj] + 6.0 * s[113152 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[165376 + jj] = acy[jj] * s[144896 + jj] + 5.0 * s[114688 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[165888 + jj] = acy[jj] * s[145920 + jj] + 4.0 * s[116224 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[166400 + jj] = acy[jj] * s[146944 + jj] + 3.0 * s[117760 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[166912 + jj] = acy[jj] * s[147968 + jj] + 2.0 * s[119296 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[167424 + jj] = acy[jj] * s[148992 + jj] + 1.0 * s[120832 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[167936 + jj] = acy[jj] * s[150016 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[168448 + jj] = acz[jj] * s[150016 + jj] + 6.0 * s[120832 + jj];

            // (3) the Cartesian-to-spherical assembly
            {
                double* out = spherical + 0 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 7.0156076002011405 * s[152064 + jj] + -9.354143466934854 * s[155648 + jj] + 2.3385358667337135 * s[161280 + jj];
            }
            {
                double* out = spherical + 1 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 14.882351124738321 * s[154112 + jj] + -9.921567416492215 * s[158720 + jj] + 1.6535945694153693 * s[165376 + jj];
            }
            {
                double* out = spherical + 2 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -2.6516504294495533 * s[152064 + jj] + -1.7677669529663689 * s[155648 + jj] + 15.90990257669732 * s[156672 + jj] + 0.8838834764831845 * s[161280 + jj] + -5.303300858899107 * s[162304 + jj];
            }
            {
                double* out = spherical + 3 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -5.625 * s[154112 + jj] + -3.75 * s[158720 + jj] + 7.500000000000001 * s[159744 + jj] + 1.8750000000000002 * s[165376 + jj] + -2.5000000000000004 * s[166400 + jj];
            }
            {
                double* out = spherical + 4 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 0.8893905919223567 * s[151040 + jj] + 1.482317653203928 * s[153600 + jj] + -7.115124735378854 * s[154624 + jj] + 0.29646353064078557 * s[158208 + jj] + -4.743416490252569 * s[159232 + jj] + 2.3717082451262845 * s[160256 + jj] + -0.29646353064078557 * s[164864 + jj] + 2.3717082451262845 * s[165888 + jj] + -0.7905694150420949 * s[166912 + jj];
            }
            {
                double* out = spherical + 5 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -5.625 * s[152576 + jj] + -3.75 * s[156160 + jj] + 7.500000000000001 * s[157184 + jj] + 1.8750000000000002 * s[161792 + jj] + -2.5000000000000004 * s[162816 + jj];
            }
            {
                double* out = spherical + 6 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -1.3258252147247767 * s[151040 + jj] + 0.4419417382415923 * s[153600 + jj] + 7.95495128834866 * s[154624 + jj] + 1.3258252147247767 * s[158208 + jj] + -10.606601717798213 * s[159232 + jj] + -0.4419417382415923 * s[164864 + jj] + 2.6516504294495533 * s[165888 + jj];
            }
            {
                double* out = spherical + 7 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 4.960783708246107 * s[152576 + jj] + -16.53594569415369 * s[156160 + jj] + 4.960783708246107 * s[161792 + jj];
            }
            {
                double* out = spherical + 8 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 1.7539019000502851 * s[151040 + jj] + -11.10804536698514 * s[153600 + jj] + 5.261705700150856 * s[158208 + jj] + -0.5846339666834284 * s[164864 + jj];
            }
            {
                double* out = spherical + 9 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 11.456439237389601 * s[154112 + jj] + -11.456439237389601 * s[158720 + jj];
            }
            {
                double* out = spherical + 10 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 24.302777619029474 * s[156672 + jj] + -8.100925873009826 * s[162304 + jj];
            }
            {
                double* out = spherical + 11 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -4.330127018922194 * s[154112 + jj] + -4.330127018922194 * s[158720 + jj] + 25.98076211353316 * s[159744 + jj];
            }
            {
                double* out = spherical + 12 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -9.185586535436919 * s[156672 + jj] + -9.185586535436919 * s[162304 + jj] + 12.247448713915892 * s[163328 + jj];
            }
            {
                double* out = spherical + 13 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 1.4523687548277815 * s[152576 + jj] + 2.904737509655563 * s[156160 + jj] + -11.618950038622252 * s[157184 + jj] + 1.4523687548277815 * s[161792 + jj] + -11.618950038622252 * s[162816 + jj] + 3.872983346207417 * s[163840 + jj];
            }
            {
                double* out = spherical + 14 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -9.185586535436919 * s[154624 + jj] + -9.185586535436919 * s[159232 + jj] + 12.247448713915892 * s[160256 + jj];
            }
            {
                double* out = spherical + 15 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -2.165063509461097 * s[152576 + jj] + 12.99038105676658 * s[157184 + jj] + 2.165063509461097 * s[161792 + jj] + -12.99038105676658 * s[162816 + jj];
            }
            {
                double* out = spherical + 16 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 8.100925873009826 * s[154624 + jj] + -24.302777619029474 * s[159232 + jj];
            }
            {
                double* out = spherical + 17 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 2.8641098093474002 * s[152576 + jj] + -17.1846588560844 * s[156160 + jj] + 2.8641098093474002 * s[161792 + jj];
            }
            {
                double* out = spherical + 18 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -1.8114220932736798 * s[152064 + jj] + 7.245688373094719 * s[156672 + jj] + 1.8114220932736798 * s[161280 + jj] + -7.245688373094719 * s[162304 + jj];
            }
            {
                double* out = spherical + 19 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -3.842606537234849 * s[154112 + jj] + -2.561737691489899 * s[158720 + jj] + 15.370426148939396 * s[159744 + jj] + 1.2808688457449497 * s[165376 + jj] + -5.123475382979799 * s[166400 + jj];
            }
            {
                double* out = spherical + 20 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 0.6846531968814576 * s[152064 + jj] + 1.3693063937629153 * s[155648 + jj] + -6.846531968814576 * s[156672 + jj] + 0.6846531968814576 * s[161280 + jj] + -6.846531968814576 * s[162304 + jj] + 16.431676725154983 * s[163328 + jj];
            }
            {
                double* out = spherical + 21 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 1.4523687548277813 * s[154112 + jj] + 2.9047375096555625 * s[158720 + jj] + -7.745966692414833 * s[159744 + jj] + 1.4523687548277813 * s[165376 + jj] + -7.745966692414833 * s[166400 + jj] + 7.745966692414833 * s[167424 + jj];
            }
            {
                double* out = spherical + 22 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -0.22963966338592293 * s[151040 + jj] + -0.6889189901577688 * s[153600 + jj] + 2.7556759606310752 * s[154624 + jj] + -0.6889189901577688 * s[158208 + jj] + 5.5113519212621505 * s[159232 + jj] + -7.960841664045328 * s[160256 + jj] + -0.22963966338592293 * s[164864 + jj] + 2.7556759606310752 * s[165888 + jj] + -7.960841664045328 * s[166912 + jj] + 2.449489742783178 * s[167936 + jj];
            }
            {
                double* out = spherical + 23 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 1.4523687548277813 * s[152576 + jj] + 2.9047375096555625 * s[156160 + jj] + -7.745966692414833 * s[157184 + jj] + 1.4523687548277813 * s[161792 + jj] + -7.745966692414833 * s[162816 + jj] + 7.745966692414833 * s[163840 + jj];
            }
            {
                double* out = spherical + 24 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 0.3423265984407288 * s[151040 + jj] + 0.3423265984407288 * s[153600 + jj] + -3.423265984407288 * s[154624 + jj] + -0.3423265984407288 * s[158208 + jj] + 8.215838362577491 * s[160256 + jj] + -0.3423265984407288 * s[164864 + jj] + 3.423265984407288 * s[165888 + jj] + -8.215838362577491 * s[166912 + jj];
            }
            {
                double* out = spherical + 25 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -1.2808688457449497 * s[152576 + jj] + 2.561737691489899 * s[156160 + jj] + 5.123475382979799 * s[157184 + jj] + 3.842606537234849 * s[161792 + jj] + -15.370426148939396 * s[162816 + jj];
            }
            {
                double* out = spherical + 26 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -0.45285552331841994 * s[151040 + jj] + 2.2642776165921 * s[153600 + jj] + 1.8114220932736798 * s[154624 + jj] + 2.2642776165921 * s[158208 + jj] + -10.868532559642079 * s[159232 + jj] + -0.45285552331841994 * s[164864 + jj] + 1.8114220932736798 * s[165888 + jj];
            }
            {
                double* out = spherical + 27 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -4.437059837324712 * s[152576 + jj] + 2.958039891549808 * s[157184 + jj] + 4.437059837324712 * s[161792 + jj] + -2.958039891549808 * s[162816 + jj];
            }
            {
                double* out = spherical + 28 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -9.41242529850835 * s[154624 + jj] + -6.274950199005566 * s[159232 + jj] + 6.274950199005566 * s[160256 + jj] + 3.137475099502783 * s[165888 + jj] + -2.091650066335189 * s[166912 + jj];
            }
            {
                double* out = spherical + 29 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 1.6770509831248424 * s[152576 + jj] + 3.3541019662496847 * s[156160 + jj] + -11.180339887498949 * s[157184 + jj] + 1.6770509831248424 * s[161792 + jj] + -11.180339887498949 * s[162816 + jj] + 6.708203932499369 * s[163840 + jj];
            }
            {
                double* out = spherical + 30 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 3.557562367689427 * s[154624 + jj] + 7.115124735378854 * s[159232 + jj] + -7.115124735378854 * s[160256 + jj] + 3.557562367689427 * s[165888 + jj] + -7.115124735378854 * s[166912 + jj] + 3.1622776601683795 * s[167936 + jj];
            }
            {
                double* out = spherical + 31 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -0.5625 * s[151552 + jj] + -1.6875 * s[154112 + jj] + 4.875 * s[155136 + jj] + -1.6875 * s[158720 + jj] + 9.75 * s[159744 + jj] + -4.5 * s[160768 + jj] + -0.5625 * s[165376 + jj] + 4.875 * s[166400 + jj] + -4.5 * s[167424 + jj] + 1.0 * s[168448 + jj];
            }
            {
                double* out = spherical + 32 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 3.557562367689427 * s[153088 + jj] + 7.115124735378854 * s[156672 + jj] + -7.115124735378854 * s[157696 + jj] + 3.557562367689427 * s[162304 + jj] + -7.115124735378854 * s[163328 + jj] + 3.1622776601683795 * s[164352 + jj];
            }
            {
                double* out = spherical + 33 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 0.8385254915624212 * s[151552 + jj] + 0.8385254915624212 * s[154112 + jj] + -5.5901699437494745 * s[155136 + jj] + -0.8385254915624212 * s[158720 + jj] + 3.3541019662496847 * s[160768 + jj] + -0.8385254915624212 * s[165376 + jj] + 5.5901699437494745 * s[166400 + jj] + -3.3541019662496847 * s[167424 + jj];
            }
            {
                double* out = spherical + 34 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -3.137475099502783 * s[153088 + jj] + 6.274950199005566 * s[156672 + jj] + 2.091650066335189 * s[157696 + jj] + 9.41242529850835 * s[162304 + jj] + -6.274950199005566 * s[163328 + jj];
            }
            {
                double* out = spherical + 35 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -1.109264959331178 * s[151552 + jj] + 5.54632479665589 * s[154112 + jj] + 0.739509972887452 * s[155136 + jj] + 5.54632479665589 * s[158720 + jj] + -4.437059837324712 * s[159744 + jj] + -1.109264959331178 * s[165376 + jj] + 0.739509972887452 * s[166400 + jj];
            }
            {
                double* out = spherical + 36 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -1.8114220932736798 * s[151040 + jj] + 7.245688373094719 * s[154624 + jj] + 1.8114220932736798 * s[158208 + jj] + -7.245688373094719 * s[159232 + jj];
            }
            {
                double* out = spherical + 37 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -3.842606537234849 * s[152576 + jj] + -2.561737691489899 * s[156160 + jj] + 15.370426148939396 * s[157184 + jj] + 1.2808688457449497 * s[161792 + jj] + -5.123475382979799 * s[162816 + jj];
            }
            {
                double* out = spherical + 38 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 0.6846531968814576 * s[151040 + jj] + 1.3693063937629153 * s[153600 + jj] + -6.846531968814576 * s[154624 + jj] + 0.6846531968814576 * s[158208 + jj] + -6.846531968814576 * s[159232 + jj] + 16.431676725154983 * s[160256 + jj];
            }
            {
                double* out = spherical + 39 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 1.4523687548277813 * s[152576 + jj] + 2.9047375096555625 * s[156160 + jj] + -7.745966692414833 * s[157184 + jj] + 1.4523687548277813 * s[161792 + jj] + -7.745966692414833 * s[162816 + jj] + 7.745966692414833 * s[163840 + jj];
            }
            {
                double* out = spherical + 40 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -0.22963966338592293 * s[150528 + jj] + -0.6889189901577688 * s[152064 + jj] + 2.7556759606310752 * s[153088 + jj] + -0.6889189901577688 * s[155648 + jj] + 5.5113519212621505 * s[156672 + jj] + -7.960841664045328 * s[157696 + jj] + -0.22963966338592293 * s[161280 + jj] + 2.7556759606310752 * s[162304 + jj] + -7.960841664045328 * s[163328 + jj] + 2.449489742783178 * s[164352 + jj];
            }
            {
                double* out = spherical + 41 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 1.4523687548277813 * s[151552 + jj] + 2.9047375096555625 * s[154112 + jj] + -7.745966692414833 * s[155136 + jj] + 1.4523687548277813 * s[158720 + jj] + -7.745966692414833 * s[159744 + jj] + 7.745966692414833 * s[160768 + jj];
            }
            {
                double* out = spherical + 42 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 0.3423265984407288 * s[150528 + jj] + 0.3423265984407288 * s[152064 + jj] + -3.423265984407288 * s[153088 + jj] + -0.3423265984407288 * s[155648 + jj] + 8.215838362577491 * s[157696 + jj] + -0.3423265984407288 * s[161280 + jj] + 3.423265984407288 * s[162304 + jj] + -8.215838362577491 * s[163328 + jj];
            }
            {
                double* out = spherical + 43 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -1.2808688457449497 * s[151552 + jj] + 2.561737691489899 * s[154112 + jj] + 5.123475382979799 * s[155136 + jj] + 3.842606537234849 * s[158720 + jj] + -15.370426148939396 * s[159744 + jj];
            }
            {
                double* out = spherical + 44 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -0.45285552331841994 * s[150528 + jj] + 2.2642776165921 * s[152064 + jj] + 1.8114220932736798 * s[153088 + jj] + 2.2642776165921 * s[155648 + jj] + -10.868532559642079 * s[156672 + jj] + -0.45285552331841994 * s[161280 + jj] + 1.8114220932736798 * s[162304 + jj];
            }
            {
                double* out = spherical + 45 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 5.7282196186948005 * s[152576 + jj] + -11.456439237389601 * s[156160 + jj] + 5.7282196186948005 * s[161792 + jj];
            }
            {
                double* out = spherical + 46 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 12.151388809514737 * s[154624 + jj] + -16.20185174601965 * s[159232 + jj] + 4.050462936504913 * s[165888 + jj];
            }
            {
                double* out = spherical + 47 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -2.165063509461097 * s[152576 + jj] + 12.99038105676658 * s[157184 + jj] + 2.165063509461097 * s[161792 + jj] + -12.99038105676658 * s[162816 + jj];
            }
            {
                double* out = spherical + 48 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -4.592793267718459 * s[154624 + jj] + 6.123724356957946 * s[160256 + jj] + 4.592793267718459 * s[165888 + jj] + -6.123724356957946 * s[166912 + jj];
            }
            {
                double* out = spherical + 49 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 0.7261843774138907 * s[151552 + jj] + 0.7261843774138907 * s[154112 + jj] + -5.809475019311126 * s[155136 + jj] + -0.7261843774138907 * s[158720 + jj] + 1.9364916731037085 * s[160768 + jj] + -0.7261843774138907 * s[165376 + jj] + 5.809475019311126 * s[166400 + jj] + -1.9364916731037085 * s[167424 + jj];
            }
            {
                double* out = spherical + 50 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -4.592793267718459 * s[153088 + jj] + 6.123724356957946 * s[157696 + jj] + 4.592793267718459 * s[162304 + jj] + -6.123724356957946 * s[163328 + jj];
            }
            {
                double* out = spherical + 51 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -1.0825317547305484 * s[151552 + jj] + 1.0825317547305484 * s[154112 + jj] + 6.49519052838329 * s[155136 + jj] + 1.0825317547305484 * s[158720 + jj] + -12.99038105676658 * s[159744 + jj] + -1.0825317547305484 * s[165376 + jj] + 6.49519052838329 * s[166400 + jj];
            }
            {
                double* out = spherical + 52 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 4.050462936504913 * s[153088 + jj] + -16.20185174601965 * s[156672 + jj] + 12.151388809514737 * s[162304 + jj];
            }
            {
                double* out = spherical + 53 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 1.4320549046737001 * s[151552 + jj] + -10.0243843327159 * s[154112 + jj] + 10.0243843327159 * s[158720 + jj] + -1.4320549046737001 * s[165376 + jj];
            }
            {
                double* out = spherical + 54 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 2.3385358667337135 * s[151040 + jj] + -9.354143466934854 * s[153600 + jj] + 7.0156076002011405 * s[158208 + jj];
            }
            {
                double* out = spherical + 55 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 4.960783708246107 * s[152576 + jj] + -16.53594569415369 * s[156160 + jj] + 4.960783708246107 * s[161792 + jj];
            }
            {
                double* out = spherical + 56 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -0.8838834764831845 * s[151040 + jj] + 1.7677669529663689 * s[153600 + jj] + 5.303300858899107 * s[154624 + jj] + 2.6516504294495533 * s[158208 + jj] + -15.90990257669732 * s[159232 + jj];
            }
            {
                double* out = spherical + 57 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -1.8750000000000002 * s[152576 + jj] + 3.75 * s[156160 + jj] + 2.5000000000000004 * s[157184 + jj] + 5.625 * s[161792 + jj] + -7.500000000000001 * s[162816 + jj];
            }
            {
                double* out = spherical + 58 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 0.29646353064078557 * s[150528 + jj] + -0.29646353064078557 * s[152064 + jj] + -2.3717082451262845 * s[153088 + jj] + -1.482317653203928 * s[155648 + jj] + 4.743416490252569 * s[156672 + jj] + 0.7905694150420949 * s[157696 + jj] + -0.8893905919223567 * s[161280 + jj] + 7.115124735378854 * s[162304 + jj] + -2.3717082451262845 * s[163328 + jj];
            }
            {
                double* out = spherical + 59 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -1.8750000000000002 * s[151552 + jj] + 3.75 * s[154112 + jj] + 2.5000000000000004 * s[155136 + jj] + 5.625 * s[158720 + jj] + -7.500000000000001 * s[159744 + jj];
            }
            {
                double* out = spherical + 60 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -0.4419417382415923 * s[150528 + jj] + 1.3258252147247767 * s[152064 + jj] + 2.6516504294495533 * s[153088 + jj] + 0.4419417382415923 * s[155648 + jj] + -10.606601717798213 * s[156672 + jj] + -1.3258252147247767 * s[161280 + jj] + 7.95495128834866 * s[162304 + jj];
            }
            {
                double* out = spherical + 61 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 1.6535945694153693 * s[151552 + jj] + -9.921567416492215 * s[154112 + jj] + 14.882351124738321 * s[158720 + jj];
            }
            {
                double* out = spherical + 62 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 0.5846339666834284 * s[150528 + jj] + -5.261705700150856 * s[152064 + jj] + 11.10804536698514 * s[155648 + jj] + -1.7539019000502851 * s[161280 + jj];
            }
        }
    }
}

}  // namespace detail

}  // namespace tabula
