//
//  Tabula — generated by TabulaCxxCodegen. Do not edit by hand.
//  Charge-dipole table data — (axis, l_a, l_c) = (2, 0, 1).
//

#include "TabulaChargeDipoleTable.hpp"

#include <cstdint>

namespace tabula {  // tabula namespace

namespace detail {  // detail namespace

namespace {  // unnamed namespace

static constexpr std::uint8_t ev_order_2_0_1[] = {
    1,1,2,2,2,
};
static constexpr std::uint8_t ev_mu_2_0_1[] = {
    0,1,0,0,0,
};
static constexpr std::uint8_t ev_goz_2_0_1[] = {
    1,0,1,1,1,
};
static constexpr std::uint8_t ev_qx_2_0_1[] = {
    0,0,0,0,1,
};
static constexpr std::uint8_t ev_qy_2_0_1[] = {
    0,0,0,1,0,
};
static constexpr std::uint8_t ev_qz_2_0_1[] = {
    0,1,2,1,1,
};
static constexpr std::int8_t comp_bra_2_0_1[] = {
    0,0,0,
};
static constexpr std::int8_t comp_ket_2_0_1[] = {
    -1,0,1,
};
static constexpr std::uint32_t mfields_2_0_1[] = {
    8388736,384,1,134217857,257,524418,514,
};
static constexpr std::uint16_t mcoefidx_2_0_1[] = {
    1,2,2,1,2,1,2,
};

}  // namespace

auto
chargedipole_table_2_0_1() -> const ChargeDipoleTable&
{
    static constexpr ChargeDipoleTable t{0, 1, 5, 2, 3, 7,
        ev_order_2_0_1, ev_mu_2_0_1, ev_goz_2_0_1, ev_qx_2_0_1, ev_qy_2_0_1, ev_qz_2_0_1,
        comp_bra_2_0_1, comp_ket_2_0_1, mfields_2_0_1, mcoefidx_2_0_1};
    return t;
}

}  // namespace detail

}  // namespace tabula
