//
//  Tabula — generated by TabulaCxxCodegen. Do not edit by hand.
//  Charge-dipole table data — (axis, l_a, l_c) = (0, 0, 2).
//

#include "TabulaChargeDipoleTable.hpp"

#include <cstdint>

namespace tabula {  // tabula namespace

namespace detail {  // detail namespace

namespace {  // unnamed namespace

static constexpr std::uint8_t ev_order_0_0_2[] = {
    1,1,2,2,2,2,2,2,3,3,3,3,3,3,
};
static constexpr std::uint8_t ev_mu_0_0_2[] = {
    1,2,0,0,0,1,1,1,0,0,0,0,0,0,
};
static constexpr std::uint8_t ev_goz_0_0_2[] = {
    1,0,2,2,2,1,1,1,2,2,2,2,2,2,
};
static constexpr std::uint8_t ev_qx_0_0_2[] = {
    0,1,0,0,1,1,1,2,1,1,1,2,2,3,
};
static constexpr std::uint8_t ev_qy_0_0_2[] = {
    0,0,0,1,0,0,1,0,0,1,2,0,1,0,
};
static constexpr std::uint8_t ev_qz_0_0_2[] = {
    0,0,1,0,0,1,0,0,2,1,0,1,0,0,
};
static constexpr std::int8_t comp_bra_0_0_2[] = {
    0,0,0,0,0,
};
static constexpr std::int8_t comp_ket_0_0_2[] = {
    -2,-1,0,1,2,
};
static constexpr std::uint32_t mfields_0_0_2[] = {
    8388608,8913024,384,525056,8389504,1536,142606465,8389249,134218497,1153,524290,268435586,
    16777346,1048706,514,134218370,8389378,525186,1026,1282,1666,134217731,134742147,259,
    524931,134218627,1411,524292,16777348,1048708,516,8389380,525188,1284,1668,
};
static constexpr std::uint16_t mcoefidx_0_0_2[] = {
    3,4,5,3,3,5,4,3,3,5,1,6,1,1,2,6,1,1,0,7,7,3,4,5,
    3,3,5,3,8,3,5,8,3,9,10,
};

}  // namespace

auto
chargedipole_table_0_0_2() -> const ChargeDipoleTable&
{
    static constexpr ChargeDipoleTable t{0, 2, 14, 3, 5, 35,
        ev_order_0_0_2, ev_mu_0_0_2, ev_goz_0_0_2, ev_qx_0_0_2, ev_qy_0_0_2, ev_qz_0_0_2,
        comp_bra_0_0_2, comp_ket_0_0_2, mfields_0_0_2, mcoefidx_0_0_2};
    return t;
}

}  // namespace detail

}  // namespace tabula
