//
//  Tabula — generated by TabulaCxxCodegen. Do not edit by hand.
//  Charge-dipole table data — (axis, l_a, l_c) = (2, 1, 1).
//

#include "TabulaChargeDipoleTable.hpp"

#include <cstdint>

namespace tabula {  // tabula namespace

namespace detail {  // detail namespace

namespace {  // unnamed namespace

static constexpr std::uint8_t ev_order_2_1_1[] = {
    1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,3,3,3,3,3,3,3,3,3,3,3,3,
};
static constexpr std::uint8_t ev_mu_2_1_1[] = {
    1,1,1,2,0,0,0,0,0,0,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,
};
static constexpr std::uint8_t ev_goz_2_1_1[] = {
    0,0,1,0,1,1,1,2,2,2,0,0,0,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,
};
static constexpr std::uint8_t ev_qx_2_1_1[] = {
    0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,1,0,0,0,1,1,2,0,0,0,1,1,2,
};
static constexpr std::uint8_t ev_qy_2_1_1[] = {
    0,0,0,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,2,0,1,0,0,1,2,0,1,0,
};
static constexpr std::uint8_t ev_qz_2_1_1[] = {
    0,1,0,1,1,0,0,1,0,0,2,1,1,2,1,1,3,2,1,2,1,1,3,2,1,2,1,1,
};
static constexpr std::int8_t comp_bra_2_1_1[] = {
    -1,-1,-1,0,0,0,1,1,1,
};
static constexpr std::int8_t comp_ket_2_1_1[] = {
    -1,0,1,-1,0,1,-1,0,1,
};
static constexpr std::uint32_t mfields_2_1_1[] = {
    128,16777600,512,896,8390016,8390400,2304,3072,8388865,142606721,641,1025,
    134219137,8390273,134219521,2177,2945,8913282,525698,526082,8390530,2562,3330,8388611,
    8388867,142606723,643,1027,8389891,8390275,134219523,2179,2947,134217732,132,134217988,
    268435844,516,900,134219012,134219396,2052,2820,524293,524549,134742405,773,1157,
    525573,525957,134219653,2437,3205,8913286,8390150,526086,8390534,2566,3334,524551,
    134742407,775,1159,134219271,525959,134219655,2439,3207,136,1048968,520,904,
    525832,526216,2696,3464,
};
static constexpr std::uint16_t mcoefidx_2_1_1[] = {
    1,6,2,0,1,6,2,0,129,6,2,0,1,129,129,2,0,6,1,129,129,2,0,1,
    129,6,2,0,1,129,129,2,0,1,1,6,6,107,37,1,6,2,0,1,129,6,2,0,
    1,129,129,2,0,6,1,129,129,2,0,129,6,2,0,1,129,129,2,0,1,6,2,0,
    1,6,2,0,
};

}  // namespace

auto
chargedipole_table_2_1_1() -> const ChargeDipoleTable&
{
    static constexpr ChargeDipoleTable t{1, 1, 28, 3, 9, 76,
        ev_order_2_1_1, ev_mu_2_1_1, ev_goz_2_1_1, ev_qx_2_1_1, ev_qy_2_1_1, ev_qz_2_1_1,
        comp_bra_2_1_1, comp_ket_2_1_1, mfields_2_1_1, mcoefidx_2_1_1};
    return t;
}

}  // namespace detail

}  // namespace tabula
