//
//  Tabula — generated by TabulaCxxCodegen. Do not edit by hand.
//  Nuclear-attraction table data — (l_a, l_c) = (0, 2).
//

#include "TabulaNuclearAttractionTable.hpp"

#include <cstdint>

namespace tabula {  // tabula namespace

namespace detail {  // detail namespace

namespace {  // unnamed namespace

static constexpr std::uint8_t ev_order_0_2[] = {
    0,1,1,1,2,2,2,2,2,2,
};
static constexpr std::uint8_t ev_mu_0_2[] = {
    2,1,1,1,0,0,0,0,0,0,
};
static constexpr std::uint8_t ev_goz_0_2[] = {
    0,1,1,1,2,2,2,2,2,2,
};
static constexpr std::uint8_t ev_qx_0_2[] = {
    0,0,0,1,0,0,0,1,1,2,
};
static constexpr std::uint8_t ev_qy_0_2[] = {
    0,0,1,0,0,1,2,0,1,0,
};
static constexpr std::uint8_t ev_qz_0_2[] = {
    0,1,0,0,2,1,0,1,0,0,
};
static constexpr std::int8_t comp_bra_0_2[] = {
    0,0,0,0,0,
};
static constexpr std::int8_t comp_ket_0_2[] = {
    -2,-1,0,1,2,
};
static constexpr std::uint8_t mfields_0_2[] = {
    0,0,0,1,1,0,0,2,0,1,0,0,0,3,0,0,1,0,0,8,0,0,0,0,1,0,0,0,1,1,1,1,0,0,1,0,
    1,2,0,0,0,1,1,5,0,0,0,0,2,0,0,0,0,2,2,0,0,0,2,0,2,0,0,2,0,0,2,1,0,0,0,1,
    2,2,0,0,1,0,2,3,0,1,0,0,2,4,0,0,0,0,2,6,0,0,0,0,2,9,0,0,0,0,3,0,0,1,0,1,
    3,1,0,1,0,0,3,3,0,0,0,1,3,7,0,0,0,0,4,0,0,0,2,0,4,0,0,2,0,0,4,2,0,0,1,0,
    4,3,0,1,0,0,4,6,0,0,0,0,4,9,0,0,0,0,
};
static constexpr std::uint16_t mcoefidx_0_2[] = {
    3,4,4,5,3,4,4,5,6,1,1,6,1,1,0,7,7,3,4,4,5,8,4,8,
    4,9,10,
};

}  // namespace

auto
nuclear_table_0_2() -> const NuclearTable&
{
    static constexpr NuclearTable t{0, 2, 10, 2, 5, 27,
        ev_order_0_2, ev_mu_0_2, ev_goz_0_2, ev_qx_0_2, ev_qy_0_2, ev_qz_0_2,
        comp_bra_0_2, comp_ket_0_2, mfields_0_2, mcoefidx_0_2};
    return t;
}

}  // namespace detail

}  // namespace tabula
