//
//  Tabula — generated by TabulaCxxCodegen. Do not edit by hand.
//  Charge-dipole kernel tables — the nuclear-attraction M·V form with
//  the ∇_Q axis shift, one table per Cartesian field axis.
//

#ifndef TabulaChargeDipoleTable_hpp
#define TabulaChargeDipoleTable_hpp

#include <cstdint>

namespace tabula {  // tabula namespace

namespace detail {  // detail namespace

/// @brief A pointer view of one (axis, l_a, l_c) charge-dipole table —
/// the same early-contraction M·V shape as the nuclear-attraction table.
struct ChargeDipoleTable
{
    int l_a, l_c;
    int ev_count, max_order, component_count, m_row_count;
    const std::uint8_t *ev_order, *ev_mu_power, *ev_goz_power, *ev_qx, *ev_qy, *ev_qz;
    const std::int8_t *component_bra_m, *component_ket_m;
    const std::uint8_t *m_fields;
    const std::uint16_t *m_coef_idx;
};

/// @brief The charge-dipole table for a field axis (0=x,1=y,2=z) and an
/// (l_a, l_c) pair, l = 0 … 4.
auto chargedipole_table(int axis, int l_a, int l_c) -> const ChargeDipoleTable&;

/// @brief The shared coefficient dictionary the M rows index into.
auto chargedipole_coef_dict() -> const double*;

}  // namespace detail

}  // namespace tabula

#endif /* TabulaChargeDipoleTable_hpp */
