//
//  Tabula — generated by TabulaCxxCodegen. Do not edit by hand.
//  Two-center kinetic fused kernel — (l_a, l_c) = (4, 0).
//

#include "TabulaKineticKernel.hpp"

#include <cmath>
#include <cstddef>
#include <vector>

#include "MathConst.hpp"
#include "TabulaKineticKernelTable.hpp"

namespace tabula {  // tabula namespace

namespace detail {  // detail namespace

auto
kinetic_kernel_4_0(const KernelBlockData& bra, const int bra_begin, const int bra_end,
                          const KernelBlockData& ket, double* spherical) -> void
{
    const double fpi = mathconst::pi_value();
    const std::size_t cdim =
        static_cast<std::size_t>(bra_end - bra_begin) * static_cast<std::size_t>(ket.ncgtos);
    const auto stride = ((cdim + 7) / 8) * 8;
    constexpr std::size_t tile = 512;

    if (g_kinetic_scratch.size() < 70 * tile) g_kinetic_scratch.resize(70 * tile);
    auto* s = g_kinetic_scratch.data();

    double acx[tile];
    double acy[tile];
    double acz[tile];

    // the bra contracted GTOs on the outside; the ket contracted GTOs
    // tiled on the inside, the tile the SIMD axis
    for (int i = bra_begin; i < bra_end; i++)
    {
        const double bx = bra.x[i];
        const double by = bra.y[i];
        const double bz = bra.z[i];
        const std::size_t ij_base = static_cast<std::size_t>(i - bra_begin) * static_cast<std::size_t>(ket.ncgtos);

        for (int j0 = 0; j0 < ket.ncgtos; j0 += static_cast<int>(tile))
        {
            const std::size_t w =
                (j0 + static_cast<int>(tile) < ket.ncgtos) ? tile : static_cast<std::size_t>(ket.ncgtos - j0);

            // AC = A − C, per ket contracted GTO of the tile
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
            {
                acx[jj] = bx - ket.x[j0 + jj];
                acy[jj] = by - ket.y[j0 + jj];
                acz[jj] = bz - ket.z[j0 + jj];
            }

            // (1) the contracted seed ladder [0]^m
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++) s[0 + jj] = 0.0;
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++) s[512 + jj] = 0.0;
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++) s[1024 + jj] = 0.0;
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++) s[1536 + jj] = 0.0;
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++) s[2048 + jj] = 0.0;
            for (int kb = 0; kb < bra.nprims; kb++)
            {
                const double a  = bra.exponents[static_cast<std::size_t>(kb) * bra.ncgtos + i];
                const double bn = bra.norms[static_cast<std::size_t>(kb) * bra.ncgtos + i];
                const double ia = 0.5 / a;
                for (int lk = 0; lk < ket.nprims; lk++)
                {
                    const double* ke = ket.exponents + static_cast<std::size_t>(lk) * ket.ncgtos + j0;
                    const double* kn = ket.norms + static_cast<std::size_t>(lk) * ket.ncgtos + j0;
#pragma omp simd
                    for (std::size_t jj = 0; jj < w; jj++)
                    {
                        const double g    = ke[jj];
                        const double ig   = -0.5 / g;
                        const double fe   = 1.0 / (a + g);
                        const double fz   = a * g * fe;
                        const double fact = fpi * fe;
                        const double r2   = acx[jj] * acx[jj] + acy[jj] * acy[jj] + acz[jj] * acz[jj];
                        const double wgt  = bn * kn[jj] * fact * std::sqrt(fact) * std::exp(-fz * r2);
                        double t = wgt * ia * ia * ia * ia;
                        const double kt2 = 2.0 * fz * r2;
                        s[0 + jj] += t * fz * (3.0 - kt2);
                        const double f = -2.0 * a * g / (a + g);
                        t *= f;
                        s[512 + jj] += t * fz * (5.0 - kt2);
                        t *= f;
                        s[1024 + jj] += t * fz * (7.0 - kt2);
                        t *= f;
                        s[1536 + jj] += t * fz * (9.0 - kt2);
                        t *= f;
                        s[2048 + jj] += t * fz * (11.0 - kt2);
                    }
                }
            }

            // (2) the single-centre MD recursion [r]^0
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[2560 + jj] = acx[jj] * s[512 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[3072 + jj] = acx[jj] * s[1024 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[3584 + jj] = acx[jj] * s[1536 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[4096 + jj] = acx[jj] * s[2048 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[4608 + jj] = acy[jj] * s[512 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[5120 + jj] = acy[jj] * s[1024 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[5632 + jj] = acy[jj] * s[1536 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[6144 + jj] = acy[jj] * s[2048 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[6656 + jj] = acz[jj] * s[512 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[7168 + jj] = acz[jj] * s[1024 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[7680 + jj] = acz[jj] * s[1536 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[8192 + jj] = acz[jj] * s[2048 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[8704 + jj] = acx[jj] * s[3072 + jj] + 1.0 * s[512 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[9216 + jj] = acx[jj] * s[3584 + jj] + 1.0 * s[1024 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[9728 + jj] = acx[jj] * s[4096 + jj] + 1.0 * s[1536 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[10240 + jj] = acx[jj] * s[5120 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[10752 + jj] = acx[jj] * s[5632 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[11264 + jj] = acx[jj] * s[6144 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[11776 + jj] = acx[jj] * s[7168 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[12288 + jj] = acx[jj] * s[7680 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[12800 + jj] = acx[jj] * s[8192 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[13312 + jj] = acy[jj] * s[5120 + jj] + 1.0 * s[512 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[13824 + jj] = acy[jj] * s[5632 + jj] + 1.0 * s[1024 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[14336 + jj] = acy[jj] * s[6144 + jj] + 1.0 * s[1536 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[14848 + jj] = acy[jj] * s[7168 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[15360 + jj] = acy[jj] * s[7680 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[15872 + jj] = acy[jj] * s[8192 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[16384 + jj] = acz[jj] * s[7168 + jj] + 1.0 * s[512 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[16896 + jj] = acz[jj] * s[7680 + jj] + 1.0 * s[1024 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[17408 + jj] = acz[jj] * s[8192 + jj] + 1.0 * s[1536 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[17920 + jj] = acx[jj] * s[9216 + jj] + 2.0 * s[3072 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[18432 + jj] = acx[jj] * s[9728 + jj] + 2.0 * s[3584 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[18944 + jj] = acx[jj] * s[10752 + jj] + 1.0 * s[5120 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[19456 + jj] = acx[jj] * s[11264 + jj] + 1.0 * s[5632 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[19968 + jj] = acx[jj] * s[12288 + jj] + 1.0 * s[7168 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[20480 + jj] = acx[jj] * s[12800 + jj] + 1.0 * s[7680 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[20992 + jj] = acx[jj] * s[13824 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[21504 + jj] = acx[jj] * s[14336 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[22016 + jj] = acx[jj] * s[15360 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[22528 + jj] = acx[jj] * s[15872 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[23040 + jj] = acx[jj] * s[16896 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[23552 + jj] = acx[jj] * s[17408 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[24064 + jj] = acy[jj] * s[13824 + jj] + 2.0 * s[5120 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[24576 + jj] = acy[jj] * s[14336 + jj] + 2.0 * s[5632 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[25088 + jj] = acy[jj] * s[15360 + jj] + 1.0 * s[7168 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[25600 + jj] = acy[jj] * s[15872 + jj] + 1.0 * s[7680 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[26112 + jj] = acy[jj] * s[16896 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[26624 + jj] = acy[jj] * s[17408 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[27136 + jj] = acz[jj] * s[16896 + jj] + 2.0 * s[7168 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[27648 + jj] = acz[jj] * s[17408 + jj] + 2.0 * s[7680 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[28160 + jj] = acx[jj] * s[18432 + jj] + 3.0 * s[9216 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[28672 + jj] = acx[jj] * s[19456 + jj] + 2.0 * s[10752 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[29184 + jj] = acx[jj] * s[20480 + jj] + 2.0 * s[12288 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[29696 + jj] = acx[jj] * s[21504 + jj] + 1.0 * s[13824 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[30208 + jj] = acx[jj] * s[22528 + jj] + 1.0 * s[15360 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[30720 + jj] = acx[jj] * s[23552 + jj] + 1.0 * s[16896 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[31232 + jj] = acx[jj] * s[24576 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[31744 + jj] = acx[jj] * s[25600 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[32256 + jj] = acx[jj] * s[26624 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[32768 + jj] = acx[jj] * s[27648 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[33280 + jj] = acy[jj] * s[24576 + jj] + 3.0 * s[13824 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[33792 + jj] = acy[jj] * s[25600 + jj] + 2.0 * s[15360 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[34304 + jj] = acy[jj] * s[26624 + jj] + 1.0 * s[16896 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[34816 + jj] = acy[jj] * s[27648 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[35328 + jj] = acz[jj] * s[27648 + jj] + 3.0 * s[16896 + jj];

            // (3) the Cartesian-to-spherical assembly
            {
                double* out = spherical + 0 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 2.958039891549808 * s[28672 + jj] + -2.958039891549808 * s[31232 + jj];
            }
            {
                double* out = spherical + 1 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 6.274950199005566 * s[30208 + jj] + -2.091650066335189 * s[33792 + jj];
            }
            {
                double* out = spherical + 2 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -1.118033988749895 * s[28672 + jj] + -1.118033988749895 * s[31232 + jj] + 6.708203932499369 * s[32256 + jj];
            }
            {
                double* out = spherical + 3 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -2.3717082451262845 * s[30208 + jj] + -2.3717082451262845 * s[33792 + jj] + 3.1622776601683795 * s[34816 + jj];
            }
            {
                double* out = spherical + 4 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 0.375 * s[28160 + jj] + 0.75 * s[29696 + jj] + -3.0 * s[30720 + jj] + 0.375 * s[33280 + jj] + -3.0 * s[34304 + jj] + 1.0 * s[35328 + jj];
            }
            {
                double* out = spherical + 5 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -2.3717082451262845 * s[29184 + jj] + -2.3717082451262845 * s[31744 + jj] + 3.1622776601683795 * s[32768 + jj];
            }
            {
                double* out = spherical + 6 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -0.5590169943749475 * s[28160 + jj] + 3.3541019662496847 * s[30720 + jj] + 0.5590169943749475 * s[33280 + jj] + -3.3541019662496847 * s[34304 + jj];
            }
            {
                double* out = spherical + 7 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 2.091650066335189 * s[29184 + jj] + -6.274950199005566 * s[31744 + jj];
            }
            {
                double* out = spherical + 8 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 0.739509972887452 * s[28160 + jj] + -4.437059837324712 * s[29696 + jj] + 0.739509972887452 * s[33280 + jj];
            }
        }
    }
}

}  // namespace detail

}  // namespace tabula
