//
//  Tabula — generated by TabulaCxxCodegen. Do not edit by hand.
//  Nuclear-attraction table data — (l_a, l_c) = (0, 2).
//

#include "TabulaNuclearAttractionTable.hpp"

#include <cstdint>

namespace tabula {  // tabula namespace

namespace detail {  // detail namespace

namespace {  // unnamed namespace

static constexpr std::uint8_t ev_order_0_2[] = {
    0,1,1,1,2,2,2,2,2,2,
};
static constexpr std::uint8_t ev_mu_0_2[] = {
    2,1,1,1,0,0,0,0,0,0,
};
static constexpr std::uint8_t ev_goz_0_2[] = {
    0,1,1,1,2,2,2,2,2,2,
};
static constexpr std::uint8_t ev_qx_0_2[] = {
    0,0,0,1,0,0,0,1,1,2,
};
static constexpr std::uint8_t ev_qy_0_2[] = {
    0,0,1,0,0,1,2,0,1,0,
};
static constexpr std::uint8_t ev_qz_0_2[] = {
    0,1,0,0,2,1,0,1,0,0,
};
static constexpr std::int8_t comp_bra_0_2[] = {
    0,0,0,0,0,
};
static constexpr std::int8_t comp_ket_0_2[] = {
    -2,-1,0,1,2,
};
static constexpr std::uint32_t mfields_0_2[] = {
    8912896,524544,8388992,1024,142606337,8388737,134217985,641,268435458,16777218,1048578,134217858,
    8388866,524674,514,770,1154,134742019,524419,134218115,899,16777220,1048580,8388868,
    524676,772,1156,
};
static constexpr std::uint16_t mcoefidx_0_2[] = {
    3,4,4,5,3,4,4,5,6,1,1,6,1,1,0,7,7,3,4,4,5,8,4,8,
    4,9,10,
};

}  // namespace

auto
nuclear_table_0_2() -> const NuclearTable&
{
    static constexpr NuclearTable t{0, 2, 10, 2, 5, 27,
        ev_order_0_2, ev_mu_0_2, ev_goz_0_2, ev_qx_0_2, ev_qy_0_2, ev_qz_0_2,
        comp_bra_0_2, comp_ket_0_2, mfields_0_2, mcoefidx_0_2};
    return t;
}

}  // namespace detail

}  // namespace tabula
