//
//  Tabula — generated by TabulaCxxCodegen. Do not edit by hand.
//  Nuclear-attraction table data — (l_a, l_c) = (1, 0).
//

#include "TabulaNuclearAttractionTable.hpp"

#include <cstdint>

namespace tabula {  // tabula namespace

namespace detail {  // detail namespace

namespace {  // unnamed namespace

static constexpr std::uint8_t ev_order_1_0[] = {
    0,1,1,1,1,1,1,
};
static constexpr std::uint8_t ev_mu_1_0[] = {
    1,0,0,0,0,0,0,
};
static constexpr std::uint8_t ev_goz_1_0[] = {
    0,0,0,0,1,1,1,
};
static constexpr std::uint8_t ev_qx_1_0[] = {
    0,0,0,1,0,0,1,
};
static constexpr std::uint8_t ev_qy_1_0[] = {
    0,0,1,0,0,1,0,
};
static constexpr std::uint8_t ev_qz_1_0[] = {
    0,1,0,0,1,0,0,
};
static constexpr std::int8_t comp_bra_1_0[] = {
    -1,0,1,
};
static constexpr std::int8_t comp_ket_1_0[] = {
    0,0,0,
};
static constexpr std::uint8_t mfields_1_0[] = {
    0,0,0,0,1,0,0,2,0,0,0,0,0,5,0,0,0,0,1,0,0,0,0,1,1,1,0,0,0,0,1,4,0,0,0,0,
    2,0,0,1,0,0,2,3,0,0,0,0,2,6,0,0,0,0,
};
static constexpr double mcoef_1_0[] = {
    -2.0,1.0,-1.0,-2.0,1.0,-1.0,-2.0,1.0,
    -1.0,
};

}  // namespace

auto
nuclear_table_1_0() -> const NuclearTable&
{
    static constexpr NuclearTable t{1, 0, 7, 1, 3, 9,
        ev_order_1_0, ev_mu_1_0, ev_goz_1_0, ev_qx_1_0, ev_qy_1_0, ev_qz_1_0,
        comp_bra_1_0, comp_ket_1_0, mfields_1_0, mcoef_1_0};
    return t;
}

}  // namespace detail

}  // namespace tabula
