//
//  Tabula — generated by TabulaCxxCodegen. Do not edit by hand.
//  Charge-dipole table data — (axis, l_a, l_c) = (1, 1, 1).
//

#include "TabulaChargeDipoleTable.hpp"

#include <cstdint>

namespace tabula {  // tabula namespace

namespace detail {  // detail namespace

namespace {  // unnamed namespace

static constexpr std::uint8_t ev_order_1_1_1[] = {
    1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,3,3,3,3,3,3,3,3,3,3,3,3,
};
static constexpr std::uint8_t ev_mu_1_1_1[] = {
    1,1,1,2,0,0,0,0,0,0,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,
};
static constexpr std::uint8_t ev_goz_1_1_1[] = {
    0,0,1,0,1,1,1,2,2,2,0,0,0,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,
};
static constexpr std::uint8_t ev_qx_1_1_1[] = {
    0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,1,0,0,0,1,1,2,0,0,0,1,1,2,
};
static constexpr std::uint8_t ev_qy_1_1_1[] = {
    0,1,0,1,0,1,0,0,1,0,1,2,1,1,2,1,1,2,3,1,2,1,1,2,3,1,2,1,
};
static constexpr std::uint8_t ev_qz_1_1_1[] = {
    0,0,0,0,1,0,0,1,0,0,1,0,0,1,0,0,2,1,0,1,0,0,2,1,0,1,0,0,
};
static constexpr std::int8_t comp_bra_1_1_1[] = {
    -1,-1,-1,0,0,0,1,1,1,
};
static constexpr std::int8_t comp_ket_1_1_1[] = {
    -1,0,1,-1,0,1,-1,0,1,
};
static constexpr std::uint32_t mfields_1_1_1[] = {
    8388608,128,8388864,16777600,640,1024,8390016,8390400,2304,3072,134217729,134217985,
    142606721,513,897,134219137,8390273,134219521,2177,2945,524290,524546,8913282,770,
    1154,525698,526082,8390530,2562,3330,134217987,142606723,515,899,8389891,8390275,
    134219523,2179,2947,132,268435844,644,1028,134219012,134219396,2052,2820,134742405,
    525573,525957,134219653,2437,3205,524550,8913286,774,1158,8390150,526086,8390534,
    2566,3334,134742407,134219271,525959,134219655,2439,3207,136,1048968,648,1032,
    525832,526216,2696,3464,
};
static constexpr std::uint16_t mcoefidx_1_1_1[] = {
    1,1,6,6,107,37,1,6,2,0,1,129,6,2,0,1,129,129,2,0,1,129,6,2,
    0,1,129,129,2,0,129,6,2,0,1,129,129,2,0,1,6,2,0,1,6,2,0,6,
    1,129,129,2,0,129,6,2,0,1,129,129,2,0,6,1,129,129,2,0,1,6,2,0,
    1,6,2,0,
};

}  // namespace

auto
chargedipole_table_1_1_1() -> const ChargeDipoleTable&
{
    static constexpr ChargeDipoleTable t{1, 1, 28, 3, 9, 76,
        ev_order_1_1_1, ev_mu_1_1_1, ev_goz_1_1_1, ev_qx_1_1_1, ev_qy_1_1_1, ev_qz_1_1_1,
        comp_bra_1_1_1, comp_ket_1_1_1, mfields_1_1_1, mcoefidx_1_1_1};
    return t;
}

}  // namespace detail

}  // namespace tabula
