//
//  Tabula — generated by TabulaCxxCodegen. Do not edit by hand.
//  Two-center overlap fused kernel — (l_a, l_c) = (3, 2).
//

#include "TabulaOverlapKernel.hpp"

#include <cmath>
#include <cstddef>
#include <vector>

#include "MathConst.hpp"
#include "TabulaOverlapKernelTable.hpp"

namespace tabula {  // tabula namespace

namespace detail {  // detail namespace

auto
overlap_kernel_3_2(const OverlapBlockData& bra, const int bra_begin, const int bra_end,
                          const OverlapBlockData& ket, double* spherical) -> void
{
    const double fpi = mathconst::pi_value();
    const std::size_t cdim =
        static_cast<std::size_t>(bra_end - bra_begin) * static_cast<std::size_t>(ket.ncgtos);
    const auto stride = ((cdim + 7) / 8) * 8;
    constexpr std::size_t tile = 512;

    if (g_kernel_scratch.size() < 126 * tile) g_kernel_scratch.resize(126 * tile);
    auto* s = g_kernel_scratch.data();

    double acx[tile];
    double acy[tile];
    double acz[tile];

    // the bra contracted GTOs on the outside; the ket contracted GTOs
    // tiled on the inside, the tile the SIMD axis
    for (int i = bra_begin; i < bra_end; i++)
    {
        const double bx = bra.x[i];
        const double by = bra.y[i];
        const double bz = bra.z[i];
        const std::size_t ij_base = static_cast<std::size_t>(i - bra_begin) * static_cast<std::size_t>(ket.ncgtos);

        for (int j0 = 0; j0 < ket.ncgtos; j0 += static_cast<int>(tile))
        {
            const std::size_t w =
                (j0 + static_cast<int>(tile) < ket.ncgtos) ? tile : static_cast<std::size_t>(ket.ncgtos - j0);

            // AC = A − C, per ket contracted GTO of the tile
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
            {
                acx[jj] = bx - ket.x[j0 + jj];
                acy[jj] = by - ket.y[j0 + jj];
                acz[jj] = bz - ket.z[j0 + jj];
            }

            // (1) the contracted seed ladder [0]^m
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++) s[0 + jj] = 0.0;
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++) s[512 + jj] = 0.0;
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++) s[1024 + jj] = 0.0;
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++) s[1536 + jj] = 0.0;
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++) s[2048 + jj] = 0.0;
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++) s[2560 + jj] = 0.0;
            for (int kb = 0; kb < bra.nprims; kb++)
            {
                const double a  = bra.exponents[static_cast<std::size_t>(kb) * bra.ncgtos + i];
                const double bn = bra.norms[static_cast<std::size_t>(kb) * bra.ncgtos + i];
                const double ia = 0.5 / a;
                for (int lk = 0; lk < ket.nprims; lk++)
                {
                    const double* ke = ket.exponents + static_cast<std::size_t>(lk) * ket.ncgtos + j0;
                    const double* kn = ket.norms + static_cast<std::size_t>(lk) * ket.ncgtos + j0;
#pragma omp simd
                    for (std::size_t jj = 0; jj < w; jj++)
                    {
                        const double g    = ke[jj];
                        const double ig   = -0.5 / g;
                        const double fe   = 1.0 / (a + g);
                        const double fz   = a * g * fe;
                        const double fact = fpi * fe;
                        const double r2   = acx[jj] * acx[jj] + acy[jj] * acy[jj] + acz[jj] * acz[jj];
                        const double wgt  = bn * kn[jj] * fact * std::sqrt(fact) * std::exp(-fz * r2);
                        double t = wgt * ia * ia * ia * ig * ig;
                        s[0 + jj] += t;
                        const double f = -2.0 * a * g / (a + g);
                        t *= f;
                        s[512 + jj] += t;
                        t *= f;
                        s[1024 + jj] += t;
                        t *= f;
                        s[1536 + jj] += t;
                        t *= f;
                        s[2048 + jj] += t;
                        t *= f;
                        s[2560 + jj] += t;
                    }
                }
            }

            // (2) the single-centre MD recursion [r]^0
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[3072 + jj] = acx[jj] * s[512 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[3584 + jj] = acx[jj] * s[1024 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[4096 + jj] = acx[jj] * s[1536 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[4608 + jj] = acx[jj] * s[2048 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[5120 + jj] = acx[jj] * s[2560 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[5632 + jj] = acy[jj] * s[512 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[6144 + jj] = acy[jj] * s[1024 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[6656 + jj] = acy[jj] * s[1536 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[7168 + jj] = acy[jj] * s[2048 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[7680 + jj] = acy[jj] * s[2560 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[8192 + jj] = acz[jj] * s[512 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[8704 + jj] = acz[jj] * s[1024 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[9216 + jj] = acz[jj] * s[1536 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[9728 + jj] = acz[jj] * s[2048 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[10240 + jj] = acz[jj] * s[2560 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[10752 + jj] = acx[jj] * s[3584 + jj] + 1.0 * s[512 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[11264 + jj] = acx[jj] * s[4096 + jj] + 1.0 * s[1024 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[11776 + jj] = acx[jj] * s[4608 + jj] + 1.0 * s[1536 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[12288 + jj] = acx[jj] * s[5120 + jj] + 1.0 * s[2048 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[12800 + jj] = acx[jj] * s[6144 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[13312 + jj] = acx[jj] * s[6656 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[13824 + jj] = acx[jj] * s[7168 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[14336 + jj] = acx[jj] * s[7680 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[14848 + jj] = acx[jj] * s[8704 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[15360 + jj] = acx[jj] * s[9216 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[15872 + jj] = acx[jj] * s[9728 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[16384 + jj] = acx[jj] * s[10240 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[16896 + jj] = acy[jj] * s[6144 + jj] + 1.0 * s[512 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[17408 + jj] = acy[jj] * s[6656 + jj] + 1.0 * s[1024 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[17920 + jj] = acy[jj] * s[7168 + jj] + 1.0 * s[1536 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[18432 + jj] = acy[jj] * s[7680 + jj] + 1.0 * s[2048 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[18944 + jj] = acy[jj] * s[8704 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[19456 + jj] = acy[jj] * s[9216 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[19968 + jj] = acy[jj] * s[9728 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[20480 + jj] = acy[jj] * s[10240 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[20992 + jj] = acz[jj] * s[8704 + jj] + 1.0 * s[512 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[21504 + jj] = acz[jj] * s[9216 + jj] + 1.0 * s[1024 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[22016 + jj] = acz[jj] * s[9728 + jj] + 1.0 * s[1536 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[22528 + jj] = acz[jj] * s[10240 + jj] + 1.0 * s[2048 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[23040 + jj] = acx[jj] * s[11264 + jj] + 2.0 * s[3584 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[23552 + jj] = acx[jj] * s[11776 + jj] + 2.0 * s[4096 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[24064 + jj] = acx[jj] * s[12288 + jj] + 2.0 * s[4608 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[24576 + jj] = acx[jj] * s[13312 + jj] + 1.0 * s[6144 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[25088 + jj] = acx[jj] * s[13824 + jj] + 1.0 * s[6656 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[25600 + jj] = acx[jj] * s[14336 + jj] + 1.0 * s[7168 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[26112 + jj] = acx[jj] * s[15360 + jj] + 1.0 * s[8704 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[26624 + jj] = acx[jj] * s[15872 + jj] + 1.0 * s[9216 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[27136 + jj] = acx[jj] * s[16384 + jj] + 1.0 * s[9728 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[27648 + jj] = acx[jj] * s[17408 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[28160 + jj] = acx[jj] * s[17920 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[28672 + jj] = acx[jj] * s[18432 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[29184 + jj] = acx[jj] * s[19456 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[29696 + jj] = acx[jj] * s[19968 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[30208 + jj] = acx[jj] * s[20480 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[30720 + jj] = acx[jj] * s[21504 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[31232 + jj] = acx[jj] * s[22016 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[31744 + jj] = acx[jj] * s[22528 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[32256 + jj] = acy[jj] * s[17408 + jj] + 2.0 * s[6144 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[32768 + jj] = acy[jj] * s[17920 + jj] + 2.0 * s[6656 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[33280 + jj] = acy[jj] * s[18432 + jj] + 2.0 * s[7168 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[33792 + jj] = acy[jj] * s[19456 + jj] + 1.0 * s[8704 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[34304 + jj] = acy[jj] * s[19968 + jj] + 1.0 * s[9216 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[34816 + jj] = acy[jj] * s[20480 + jj] + 1.0 * s[9728 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[35328 + jj] = acy[jj] * s[21504 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[35840 + jj] = acy[jj] * s[22016 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[36352 + jj] = acy[jj] * s[22528 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[36864 + jj] = acz[jj] * s[21504 + jj] + 2.0 * s[8704 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[37376 + jj] = acz[jj] * s[22016 + jj] + 2.0 * s[9216 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[37888 + jj] = acz[jj] * s[22528 + jj] + 2.0 * s[9728 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[38400 + jj] = acx[jj] * s[23552 + jj] + 3.0 * s[11264 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[38912 + jj] = acx[jj] * s[24064 + jj] + 3.0 * s[11776 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[39424 + jj] = acx[jj] * s[25088 + jj] + 2.0 * s[13312 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[39936 + jj] = acx[jj] * s[25600 + jj] + 2.0 * s[13824 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[40448 + jj] = acx[jj] * s[26624 + jj] + 2.0 * s[15360 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[40960 + jj] = acx[jj] * s[27136 + jj] + 2.0 * s[15872 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[41472 + jj] = acx[jj] * s[28160 + jj] + 1.0 * s[17408 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[41984 + jj] = acx[jj] * s[28672 + jj] + 1.0 * s[17920 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[42496 + jj] = acx[jj] * s[29696 + jj] + 1.0 * s[19456 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[43008 + jj] = acx[jj] * s[30208 + jj] + 1.0 * s[19968 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[43520 + jj] = acx[jj] * s[31232 + jj] + 1.0 * s[21504 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[44032 + jj] = acx[jj] * s[31744 + jj] + 1.0 * s[22016 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[44544 + jj] = acx[jj] * s[32768 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[45056 + jj] = acx[jj] * s[33280 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[45568 + jj] = acx[jj] * s[34304 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[46080 + jj] = acx[jj] * s[34816 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[46592 + jj] = acx[jj] * s[35840 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[47104 + jj] = acx[jj] * s[36352 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[47616 + jj] = acx[jj] * s[37376 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[48128 + jj] = acx[jj] * s[37888 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[48640 + jj] = acy[jj] * s[32768 + jj] + 3.0 * s[17408 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[49152 + jj] = acy[jj] * s[33280 + jj] + 3.0 * s[17920 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[49664 + jj] = acy[jj] * s[34304 + jj] + 2.0 * s[19456 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[50176 + jj] = acy[jj] * s[34816 + jj] + 2.0 * s[19968 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[50688 + jj] = acy[jj] * s[35840 + jj] + 1.0 * s[21504 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[51200 + jj] = acy[jj] * s[36352 + jj] + 1.0 * s[22016 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[51712 + jj] = acy[jj] * s[37376 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[52224 + jj] = acy[jj] * s[37888 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[52736 + jj] = acz[jj] * s[37376 + jj] + 3.0 * s[21504 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[53248 + jj] = acz[jj] * s[37888 + jj] + 3.0 * s[22016 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[53760 + jj] = acx[jj] * s[38912 + jj] + 4.0 * s[23552 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[54272 + jj] = acx[jj] * s[39936 + jj] + 3.0 * s[25088 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[54784 + jj] = acx[jj] * s[40960 + jj] + 3.0 * s[26624 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[55296 + jj] = acx[jj] * s[41984 + jj] + 2.0 * s[28160 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[55808 + jj] = acx[jj] * s[43008 + jj] + 2.0 * s[29696 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[56320 + jj] = acx[jj] * s[44032 + jj] + 2.0 * s[31232 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[56832 + jj] = acx[jj] * s[45056 + jj] + 1.0 * s[32768 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[57344 + jj] = acx[jj] * s[46080 + jj] + 1.0 * s[34304 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[57856 + jj] = acx[jj] * s[47104 + jj] + 1.0 * s[35840 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[58368 + jj] = acx[jj] * s[48128 + jj] + 1.0 * s[37376 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[58880 + jj] = acx[jj] * s[49152 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[59392 + jj] = acx[jj] * s[50176 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[59904 + jj] = acx[jj] * s[51200 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[60416 + jj] = acx[jj] * s[52224 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[60928 + jj] = acx[jj] * s[53248 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[61440 + jj] = acy[jj] * s[49152 + jj] + 4.0 * s[32768 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[61952 + jj] = acy[jj] * s[50176 + jj] + 3.0 * s[34304 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[62464 + jj] = acy[jj] * s[51200 + jj] + 2.0 * s[35840 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[62976 + jj] = acy[jj] * s[52224 + jj] + 1.0 * s[37376 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[63488 + jj] = acy[jj] * s[53248 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[64000 + jj] = acz[jj] * s[53248 + jj] + 4.0 * s[37376 + jj];

            // (3) the Cartesian-to-spherical assembly
            {
                double* out = spherical + 0 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 4.107919181288746 * s[55296 + jj] + -1.3693063937629153 * s[58880 + jj];
            }
            {
                double* out = spherical + 1 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 4.107919181288746 * s[57344 + jj] + -1.3693063937629153 * s[61952 + jj];
            }
            {
                double* out = spherical + 2 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -1.1858541225631423 * s[54272 + jj] + -0.7905694150420948 * s[56832 + jj] + 2.3717082451262845 * s[57856 + jj] + 0.39528470752104744 * s[61440 + jj] + -0.7905694150420949 * s[62464 + jj];
            }
            {
                double* out = spherical + 3 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 4.107919181288746 * s[55808 + jj] + -1.3693063937629153 * s[59392 + jj];
            }
            {
                double* out = spherical + 4 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 2.053959590644373 * s[54272 + jj] + -2.7386127875258306 * s[56832 + jj] + 0.6846531968814576 * s[61440 + jj];
            }
            {
                double* out = spherical + 5 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 6.7082039324993685 * s[57344 + jj];
            }
            {
                double* out = spherical + 6 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 6.7082039324993685 * s[59904 + jj];
            }
            {
                double* out = spherical + 7 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -1.9364916731037085 * s[55808 + jj] + -1.9364916731037085 * s[59392 + jj] + 3.872983346207417 * s[60416 + jj];
            }
            {
                double* out = spherical + 8 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 6.7082039324993685 * s[57856 + jj];
            }
            {
                double* out = spherical + 9 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 3.3541019662496843 * s[55808 + jj] + -3.3541019662496843 * s[59392 + jj];
            }
            {
                double* out = spherical + 10 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -1.0606601717798212 * s[55296 + jj] + -1.0606601717798212 * s[58880 + jj] + 4.242640687119285 * s[59904 + jj];
            }
            {
                double* out = spherical + 11 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -1.0606601717798212 * s[57344 + jj] + -1.0606601717798212 * s[61952 + jj] + 4.242640687119285 * s[62976 + jj];
            }
            {
                double* out = spherical + 12 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 0.30618621784789724 * s[54272 + jj] + 0.6123724356957945 * s[56832 + jj] + -1.8371173070873834 * s[57856 + jj] + 0.30618621784789724 * s[61440 + jj] + -1.8371173070873834 * s[62464 + jj] + 2.449489742783178 * s[63488 + jj];
            }
            {
                double* out = spherical + 13 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -1.0606601717798212 * s[55808 + jj] + -1.0606601717798212 * s[59392 + jj] + 4.242640687119285 * s[60416 + jj];
            }
            {
                double* out = spherical + 14 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -0.5303300858899106 * s[54272 + jj] + 2.1213203435596424 * s[57856 + jj] + 0.5303300858899106 * s[61440 + jj] + -2.1213203435596424 * s[62464 + jj];
            }
            {
                double* out = spherical + 15 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -2.598076211353316 * s[55808 + jj] + -2.598076211353316 * s[59392 + jj] + 1.7320508075688772 * s[60416 + jj];
            }
            {
                double* out = spherical + 16 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -2.598076211353316 * s[57856 + jj] + -2.598076211353316 * s[62464 + jj] + 1.7320508075688772 * s[63488 + jj];
            }
            {
                double* out = spherical + 17 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 0.75 * s[54784 + jj] + 1.5 * s[57344 + jj] + -2.0 * s[58368 + jj] + 0.75 * s[61952 + jj] + -2.0 * s[62976 + jj] + 1.0 * s[64000 + jj];
            }
            {
                double* out = spherical + 18 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -2.598076211353316 * s[56320 + jj] + -2.598076211353316 * s[59904 + jj] + 1.7320508075688772 * s[60928 + jj];
            }
            {
                double* out = spherical + 19 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -1.299038105676658 * s[54784 + jj] + 0.8660254037844386 * s[58368 + jj] + 1.299038105676658 * s[61952 + jj] + -0.8660254037844386 * s[62976 + jj];
            }
            {
                double* out = spherical + 20 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -1.0606601717798212 * s[54272 + jj] + -1.0606601717798212 * s[56832 + jj] + 4.242640687119285 * s[57856 + jj];
            }
            {
                double* out = spherical + 21 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -1.0606601717798212 * s[55808 + jj] + -1.0606601717798212 * s[59392 + jj] + 4.242640687119285 * s[60416 + jj];
            }
            {
                double* out = spherical + 22 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 0.30618621784789724 * s[53760 + jj] + 0.6123724356957945 * s[55296 + jj] + -1.8371173070873834 * s[56320 + jj] + 0.30618621784789724 * s[58880 + jj] + -1.8371173070873834 * s[59904 + jj] + 2.449489742783178 * s[60928 + jj];
            }
            {
                double* out = spherical + 23 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -1.0606601717798212 * s[54784 + jj] + -1.0606601717798212 * s[57344 + jj] + 4.242640687119285 * s[58368 + jj];
            }
            {
                double* out = spherical + 24 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -0.5303300858899106 * s[53760 + jj] + 2.1213203435596424 * s[56320 + jj] + 0.5303300858899106 * s[58880 + jj] + -2.1213203435596424 * s[59904 + jj];
            }
            {
                double* out = spherical + 25 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 3.3541019662496843 * s[55808 + jj] + -3.3541019662496843 * s[59392 + jj];
            }
            {
                double* out = spherical + 26 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 3.3541019662496843 * s[57856 + jj] + -3.3541019662496843 * s[62464 + jj];
            }
            {
                double* out = spherical + 27 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -0.9682458365518543 * s[54784 + jj] + 1.9364916731037085 * s[58368 + jj] + 0.9682458365518543 * s[61952 + jj] + -1.9364916731037085 * s[62976 + jj];
            }
            {
                double* out = spherical + 28 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 3.3541019662496843 * s[56320 + jj] + -3.3541019662496843 * s[59904 + jj];
            }
            {
                double* out = spherical + 29 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 1.6770509831248421 * s[54784 + jj] + -3.3541019662496843 * s[57344 + jj] + 1.6770509831248421 * s[61952 + jj];
            }
            {
                double* out = spherical + 30 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 1.3693063937629153 * s[54272 + jj] + -4.107919181288746 * s[56832 + jj];
            }
            {
                double* out = spherical + 31 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 1.3693063937629153 * s[55808 + jj] + -4.107919181288746 * s[59392 + jj];
            }
            {
                double* out = spherical + 32 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -0.39528470752104744 * s[53760 + jj] + 0.7905694150420948 * s[55296 + jj] + 0.7905694150420949 * s[56320 + jj] + 1.1858541225631423 * s[58880 + jj] + -2.3717082451262845 * s[59904 + jj];
            }
            {
                double* out = spherical + 33 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 1.3693063937629153 * s[54784 + jj] + -4.107919181288746 * s[57344 + jj];
            }
            {
                double* out = spherical + 34 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 0.6846531968814576 * s[53760 + jj] + -2.7386127875258306 * s[55296 + jj] + 2.053959590644373 * s[58880 + jj];
            }
        }
    }
}

}  // namespace detail

}  // namespace tabula
