//
//  Tabula — generated by TabulaCxxCodegen. Do not edit by hand.
//  Two-center overlap fused kernel — (l_a, l_c) = (3, 0).
//

#include "TabulaOverlapKernel.hpp"

#include <cmath>
#include <cstddef>
#include <vector>

#include "MathConst.hpp"
#include "TabulaOverlapKernelTable.hpp"

namespace tabula {  // tabula namespace

namespace detail {  // detail namespace

auto
overlap_kernel_3_0(const KernelBlockData& bra, const int bra_begin, const int bra_end,
                          const KernelBlockData& ket, double* spherical) -> void
{
    const double fpi = mathconst::pi_value();
    const std::size_t cdim =
        static_cast<std::size_t>(bra_end - bra_begin) * static_cast<std::size_t>(ket.ncgtos);
    const auto stride = ((cdim + 7) / 8) * 8;
    constexpr std::size_t tile = 512;

    if (g_overlap_scratch.size() < 35 * tile) g_overlap_scratch.resize(35 * tile);
    auto* s = g_overlap_scratch.data();

    double acx[tile];
    double acy[tile];
    double acz[tile];

    // the bra contracted GTOs on the outside; the ket contracted GTOs
    // tiled on the inside, the tile the SIMD axis
    for (int i = bra_begin; i < bra_end; i++)
    {
        const double bx = bra.x[i];
        const double by = bra.y[i];
        const double bz = bra.z[i];
        const std::size_t ij_base = static_cast<std::size_t>(i - bra_begin) * static_cast<std::size_t>(ket.ncgtos);

        for (int j0 = 0; j0 < ket.ncgtos; j0 += static_cast<int>(tile))
        {
            const std::size_t w =
                (j0 + static_cast<int>(tile) < ket.ncgtos) ? tile : static_cast<std::size_t>(ket.ncgtos - j0);

            // AC = A − C, per ket contracted GTO of the tile
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
            {
                acx[jj] = bx - ket.x[j0 + jj];
                acy[jj] = by - ket.y[j0 + jj];
                acz[jj] = bz - ket.z[j0 + jj];
            }

            // (1) the contracted seed ladder [0]^m
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++) s[0 + jj] = 0.0;
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++) s[512 + jj] = 0.0;
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++) s[1024 + jj] = 0.0;
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++) s[1536 + jj] = 0.0;
            for (int kb = 0; kb < bra.nprims; kb++)
            {
                const double a  = bra.exponents[static_cast<std::size_t>(kb) * bra.ncgtos + i];
                const double bn = bra.norms[static_cast<std::size_t>(kb) * bra.ncgtos + i];
                const double ia = 0.5 / a;
                for (int lk = 0; lk < ket.nprims; lk++)
                {
                    const double* ke = ket.exponents + static_cast<std::size_t>(lk) * ket.ncgtos + j0;
                    const double* kn = ket.norms + static_cast<std::size_t>(lk) * ket.ncgtos + j0;
#pragma omp simd
                    for (std::size_t jj = 0; jj < w; jj++)
                    {
                        const double g    = ke[jj];
                        const double ig   = -0.5 / g;
                        const double fe   = 1.0 / (a + g);
                        const double fz   = a * g * fe;
                        const double fact = fpi * fe;
                        const double r2   = acx[jj] * acx[jj] + acy[jj] * acy[jj] + acz[jj] * acz[jj];
                        const double wgt  = bn * kn[jj] * fact * std::sqrt(fact) * std::exp(-fz * r2);
                        double t = wgt * ia * ia * ia;
                        s[0 + jj] += t;
                        const double f = -2.0 * a * g / (a + g);
                        t *= f;
                        s[512 + jj] += t;
                        t *= f;
                        s[1024 + jj] += t;
                        t *= f;
                        s[1536 + jj] += t;
                    }
                }
            }

            // (2) the single-centre MD recursion [r]^0
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[2048 + jj] = acx[jj] * s[512 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[2560 + jj] = acx[jj] * s[1024 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[3072 + jj] = acx[jj] * s[1536 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[3584 + jj] = acy[jj] * s[512 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[4096 + jj] = acy[jj] * s[1024 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[4608 + jj] = acy[jj] * s[1536 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[5120 + jj] = acz[jj] * s[512 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[5632 + jj] = acz[jj] * s[1024 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[6144 + jj] = acz[jj] * s[1536 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[6656 + jj] = acx[jj] * s[2560 + jj] + 1.0 * s[512 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[7168 + jj] = acx[jj] * s[3072 + jj] + 1.0 * s[1024 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[7680 + jj] = acx[jj] * s[4096 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[8192 + jj] = acx[jj] * s[4608 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[8704 + jj] = acx[jj] * s[5632 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[9216 + jj] = acx[jj] * s[6144 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[9728 + jj] = acy[jj] * s[4096 + jj] + 1.0 * s[512 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[10240 + jj] = acy[jj] * s[4608 + jj] + 1.0 * s[1024 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[10752 + jj] = acy[jj] * s[5632 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[11264 + jj] = acy[jj] * s[6144 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[11776 + jj] = acz[jj] * s[5632 + jj] + 1.0 * s[512 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[12288 + jj] = acz[jj] * s[6144 + jj] + 1.0 * s[1024 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[12800 + jj] = acx[jj] * s[7168 + jj] + 2.0 * s[2560 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[13312 + jj] = acx[jj] * s[8192 + jj] + 1.0 * s[4096 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[13824 + jj] = acx[jj] * s[9216 + jj] + 1.0 * s[5632 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[14336 + jj] = acx[jj] * s[10240 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[14848 + jj] = acx[jj] * s[11264 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[15360 + jj] = acx[jj] * s[12288 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[15872 + jj] = acy[jj] * s[10240 + jj] + 2.0 * s[4096 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[16384 + jj] = acy[jj] * s[11264 + jj] + 1.0 * s[5632 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[16896 + jj] = acy[jj] * s[12288 + jj];
#pragma omp simd
            for (std::size_t jj = 0; jj < w; jj++)
                s[17408 + jj] = acz[jj] * s[12288 + jj] + 2.0 * s[5632 + jj];

            // (3) the Cartesian-to-spherical assembly
            {
                double* out = spherical + 0 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 2.3717082451262845 * s[13312 + jj] + -0.7905694150420949 * s[15872 + jj];
            }
            {
                double* out = spherical + 1 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 3.872983346207417 * s[14848 + jj];
            }
            {
                double* out = spherical + 2 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -0.6123724356957945 * s[13312 + jj] + -0.6123724356957945 * s[15872 + jj] + 2.449489742783178 * s[16896 + jj];
            }
            {
                double* out = spherical + 3 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -1.5 * s[13824 + jj] + -1.5 * s[16384 + jj] + 1.0 * s[17408 + jj];
            }
            {
                double* out = spherical + 4 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = -0.6123724356957945 * s[12800 + jj] + -0.6123724356957945 * s[14336 + jj] + 2.449489742783178 * s[15360 + jj];
            }
            {
                double* out = spherical + 5 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 1.9364916731037085 * s[13824 + jj] + -1.9364916731037085 * s[16384 + jj];
            }
            {
                double* out = spherical + 6 * stride + ij_base + static_cast<std::size_t>(j0);
#pragma omp simd
                for (std::size_t jj = 0; jj < w; jj++) out[jj] = 0.7905694150420949 * s[12800 + jj] + -2.3717082451262845 * s[14336 + jj];
            }
        }
    }
}

}  // namespace detail

}  // namespace tabula
