//
//  Tabula — custom-recursion molecular-integral machinery.
//  Two-center overlap Cartesian-to-spherical assembly.
//

#ifndef TabulaOverlapTransform_hpp
#define TabulaOverlapTransform_hpp

#include <cstddef>

namespace tabula {  // tabula namespace

/// @brief Assembles the spherical two-center overlap block from the
/// single-centre MD-recursion terms `[r]^0` — step (d) of the late-contraction
/// recursion, the Cartesian-to-spherical transform.
///
/// The per-`(l_a, l_c)` routines are generated by `TabulaCxxCodegen` from the
/// real-solid-harmonic Cartesian expansions (`RealSolidHarmonic`); this
/// dispatches on the angular-momentum pair. Covers `l = 0 … 4`.
///
/// @param l_a The bra angular momentum.
/// @param l_c The ket angular momentum.
/// @param rterms The MD-recursion terms `[r]^0` — `(L+1)(L+2)/2` rows
/// (`L = l_a + l_c`) of `cdim` values, row stride padded to a multiple of 8.
/// @param cdim The number of contracted pairs.
/// @param spherical The output spherical block — `(2l_a+1)·(2l_c+1)` rows of
/// `cdim` values, same row-stride padding, component-major (the bra component
/// outermost, each `m` running `−l … l`).
auto overlap_transform(const int          l_a,
                       const int          l_c,
                       const double      *rterms,
                       const std::size_t  cdim,
                       double            *spherical) -> void;

}  // namespace tabula

#endif /* TabulaOverlapTransform_hpp */
