//
//  Tabula — custom-recursion molecular-integral machinery.
//  Two-center overlap fused kernel.
//

#ifndef TabulaOverlapKernel_hpp
#define TabulaOverlapKernel_hpp

#include <cstddef>

namespace tabula {  // tabula namespace

/// @brief The fused two-center overlap kernel.
///
/// For one `(l_a, l_c)` block it runs the whole late-contraction overlap
/// evaluation — the seed ladder, the primitive-pair contraction, the
/// single-centre MD recursion, and the Cartesian-to-spherical assembly — over
/// tiles of contracted pairs, with every intermediate held in a tile-local
/// scratch rather than a `cdim`-sized buffer. The per-`(l_a, l_c)` routines
/// are generated by `TabulaCxxCodegen`; this dispatches on the
/// angular-momentum pair. Covers `l = 0 … 4`.
///
/// @param l_a The bra angular momentum.
/// @param l_c The ket angular momentum.
/// @param bra_exp The primitive-pair bra exponents (primitive-pair-major,
/// `pp·cdim + ij`).
/// @param ket_exp The primitive-pair ket exponents.
/// @param weights The primitive-pair weights — the normalization and overlap
/// factors folded into one, the contraction coefficients premultiplied in.
/// @param ac_x The x components of `AC = A − C`, one per contracted pair.
/// @param ac_y The y components of `AC`.
/// @param ac_z The z components of `AC`.
/// @param cdim The number of contracted pairs.
/// @param nppairs The number of primitive pairs per contracted pair.
/// @param spherical The output spherical block — `(2l_a+1)·(2l_c+1)` rows of
/// `cdim` values, row stride padded to a multiple of 8, component-major.
auto overlap_kernel(const int          l_a,
                    const int          l_c,
                    const double      *bra_exp,
                    const double      *ket_exp,
                    const double      *weights,
                    const double      *ac_x,
                    const double      *ac_y,
                    const double      *ac_z,
                    const std::size_t  cdim,
                    const int          nppairs,
                    double            *spherical) -> void;

}  // namespace tabula

#endif /* TabulaOverlapKernel_hpp */
