if(NOT DEFINED ENV{CXXFLAGS})
  if(CMAKE_CXX_COMPILER_ID MATCHES Clang)
    if(WIN32) # clang-cl
      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /Wall /EHsc /bigobj -Xclang -Wno-c++98-compat")
      set(CMAKE_CXX_FLAGS_RELEASE "/O2")
      set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "/O2")
      set(CMAKE_CXX_FLAGS_DEBUG "/Od")
    else()
      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Wno-padded -Wno-c++98-compat -Wno-unknown-pragmas -Woverloaded-virtual -Wwrite-strings -fcolor-diagnostics")
      set(CMAKE_CXX_FLAGS_RELEASE "-O3 -DNDEBUG")
      set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O3 -g3 -DDEBUG -glldb -fno-limit-debug-info")
      set(CMAKE_CXX_FLAGS_DEBUG "-O0 -g3 -DDEBUG -glldb -fno-limit-debug-info")
    endif()
  endif()
endif()
