//
//                                   VELOXCHEM
//              ----------------------------------------------------
//                          An Electronic Structure Code
//
//  SPDX-License-Identifier: BSD-3-Clause
//
//  Copyright 2018-2025 VeloxChem developers
//
//  Redistribution and use in source and binary forms, with or without modification,
//  are permitted provided that the following conditions are met:
//
//  1. Redistributions of source code must retain the above copyright notice, this
//     list of conditions and the following disclaimer.
//  2. Redistributions in binary form must reproduce the above copyright notice,
//     this list of conditions and the following disclaimer in the documentation
//     and/or other materials provided with the distribution.
//  3. Neither the name of the copyright holder nor the names of its contributors
//     may be used to endorse or promote products derived from this software without
//     specific prior written permission.
//
//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
//  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
//  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
//  DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
//  FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
//  DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
//  SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
//  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
//  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
//  OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef EriCoulombHessianSSXX_hpp
#define EriCoulombHessianSSXX_hpp

#include <cstdint>

#include "GpuConstants.hpp"

namespace gpu {  // gpu namespace

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombHessianSSSS_II_0(double*         hess_xy,
                               const uint32_t  hess_cart_ind_0,
                               const uint32_t  hess_cart_ind_1,
                               const double    prefac_coulomb,
                               const double*   s_prim_info,
                               const uint32_t  s_prim_count,
                               const double*   ss_mat_D_local,
                               const double*   ss_mat_D,
                               const double*   ss_mat_Q_local,
                               const double*   ss_mat_Q,
                               const uint32_t* ss_first_inds_local,
                               const uint32_t* ss_second_inds_local,
                               const double*   ss_pair_data_local,
                               const uint32_t  ss_prim_pair_count_local,
                               const uint32_t* ss_first_inds,
                               const uint32_t* ss_second_inds,
                               const double*   ss_pair_data,
                               const uint32_t  ss_prim_pair_count,
                               const uint32_t* prim_cart_ao_to_atom_inds,
                               const double*   boys_func_table,
                               const double*   boys_func_ft,
                               const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombHessianSSSS_JJ_0(double*         hess_xy,
                               const uint32_t  hess_cart_ind_0,
                               const uint32_t  hess_cart_ind_1,
                               const double    prefac_coulomb,
                               const double*   s_prim_info,
                               const uint32_t  s_prim_count,
                               const double*   ss_mat_D_local,
                               const double*   ss_mat_D,
                               const double*   ss_mat_Q_local,
                               const double*   ss_mat_Q,
                               const uint32_t* ss_first_inds_local,
                               const uint32_t* ss_second_inds_local,
                               const double*   ss_pair_data_local,
                               const uint32_t  ss_prim_pair_count_local,
                               const uint32_t* ss_first_inds,
                               const uint32_t* ss_second_inds,
                               const double*   ss_pair_data,
                               const uint32_t  ss_prim_pair_count,
                               const uint32_t* prim_cart_ao_to_atom_inds,
                               const double*   boys_func_table,
                               const double*   boys_func_ft,
                               const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombHessianSSSS_IJ_0(double*         hess_xy,
                               double*         hess_yx,
                               const uint32_t  hess_cart_ind_0,
                               const uint32_t  hess_cart_ind_1,
                               const double    prefac_coulomb,
                               const double*   s_prim_info,
                               const uint32_t  s_prim_count,
                               const double*   ss_mat_D_local,
                               const double*   ss_mat_D,
                               const double*   ss_mat_Q_local,
                               const double*   ss_mat_Q,
                               const uint32_t* ss_first_inds_local,
                               const uint32_t* ss_second_inds_local,
                               const double*   ss_pair_data_local,
                               const uint32_t  ss_prim_pair_count_local,
                               const uint32_t* ss_first_inds,
                               const uint32_t* ss_second_inds,
                               const double*   ss_pair_data,
                               const uint32_t  ss_prim_pair_count,
                               const uint32_t* prim_cart_ao_to_atom_inds,
                               const uint32_t  natoms,
                               const double*   boys_func_table,
                               const double*   boys_func_ft,
                               const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombHessianSSSS_IK_0(double*         hess_xy,
                               double*         hess_yx,
                               const uint32_t  hess_cart_ind_0,
                               const uint32_t  hess_cart_ind_1,
                               const double    prefac_coulomb,
                               const double*   s_prim_info,
                               const uint32_t  s_prim_count,
                               const double*   ss_mat_D_local,
                               const double*   ss_mat_D,
                               const double*   ss_mat_Q_local,
                               const double*   ss_mat_Q,
                               const uint32_t* ss_first_inds_local,
                               const uint32_t* ss_second_inds_local,
                               const double*   ss_pair_data_local,
                               const uint32_t  ss_prim_pair_count_local,
                               const uint32_t* ss_first_inds,
                               const uint32_t* ss_second_inds,
                               const double*   ss_pair_data,
                               const uint32_t  ss_prim_pair_count,
                               const uint32_t* prim_cart_ao_to_atom_inds,
                               const uint32_t  natoms,
                               const uint32_t* d_kl_inds_for_atom_k,
                               const uint32_t* d_kl_counts_for_atom_k,
                               const uint32_t* d_kl_displs_for_atom_k,
                               const double*   boys_func_table,
                               const double*   boys_func_ft,
                               const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombHessianSSSS_JK_0(double*         hess_xy,
                               double*         hess_yx,
                               const uint32_t  hess_cart_ind_0,
                               const uint32_t  hess_cart_ind_1,
                               const double    prefac_coulomb,
                               const double*   s_prim_info,
                               const uint32_t  s_prim_count,
                               const double*   ss_mat_D_local,
                               const double*   ss_mat_D,
                               const double*   ss_mat_Q_local,
                               const double*   ss_mat_Q,
                               const uint32_t* ss_first_inds_local,
                               const uint32_t* ss_second_inds_local,
                               const double*   ss_pair_data_local,
                               const uint32_t  ss_prim_pair_count_local,
                               const uint32_t* ss_first_inds,
                               const uint32_t* ss_second_inds,
                               const double*   ss_pair_data,
                               const uint32_t  ss_prim_pair_count,
                               const uint32_t* prim_cart_ao_to_atom_inds,
                               const uint32_t  natoms,
                               const uint32_t* d_kl_inds_for_atom_k,
                               const uint32_t* d_kl_counts_for_atom_k,
                               const uint32_t* d_kl_displs_for_atom_k,
                               const double*   boys_func_table,
                               const double*   boys_func_ft,
                               const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombHessianSSSS_IL_0(double*         hess_xy,
                               double*         hess_yx,
                               const uint32_t  hess_cart_ind_0,
                               const uint32_t  hess_cart_ind_1,
                               const double    prefac_coulomb,
                               const double*   s_prim_info,
                               const uint32_t  s_prim_count,
                               const double*   ss_mat_D_local,
                               const double*   ss_mat_D,
                               const double*   ss_mat_Q_local,
                               const double*   ss_mat_Q,
                               const uint32_t* ss_first_inds_local,
                               const uint32_t* ss_second_inds_local,
                               const double*   ss_pair_data_local,
                               const uint32_t  ss_prim_pair_count_local,
                               const uint32_t* ss_first_inds,
                               const uint32_t* ss_second_inds,
                               const double*   ss_pair_data,
                               const uint32_t  ss_prim_pair_count,
                               const uint32_t* prim_cart_ao_to_atom_inds,
                               const uint32_t  natoms,
                               const uint32_t* d_kl_inds_for_atom_l,
                               const uint32_t* d_kl_counts_for_atom_l,
                               const uint32_t* d_kl_displs_for_atom_l,
                               const double*   boys_func_table,
                               const double*   boys_func_ft,
                               const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombHessianSSSS_JL_0(double*         hess_xy,
                               double*         hess_yx,
                               const uint32_t  hess_cart_ind_0,
                               const uint32_t  hess_cart_ind_1,
                               const double    prefac_coulomb,
                               const double*   s_prim_info,
                               const uint32_t  s_prim_count,
                               const double*   ss_mat_D_local,
                               const double*   ss_mat_D,
                               const double*   ss_mat_Q_local,
                               const double*   ss_mat_Q,
                               const uint32_t* ss_first_inds_local,
                               const uint32_t* ss_second_inds_local,
                               const double*   ss_pair_data_local,
                               const uint32_t  ss_prim_pair_count_local,
                               const uint32_t* ss_first_inds,
                               const uint32_t* ss_second_inds,
                               const double*   ss_pair_data,
                               const uint32_t  ss_prim_pair_count,
                               const uint32_t* prim_cart_ao_to_atom_inds,
                               const uint32_t  natoms,
                               const uint32_t* d_kl_inds_for_atom_l,
                               const uint32_t* d_kl_counts_for_atom_l,
                               const uint32_t* d_kl_displs_for_atom_l,
                               const double*   boys_func_table,
                               const double*   boys_func_ft,
                               const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombHessianSSSP_II_0(double*         hess_xy,
                               const uint32_t  hess_cart_ind_0,
                               const uint32_t  hess_cart_ind_1,
                               const double    prefac_coulomb,
                               const double*   s_prim_info,
                               const uint32_t  s_prim_count,
                               const double*   p_prim_info,
                               const uint32_t  p_prim_count,
                               const double*   ss_mat_D_local,
                               const double*   sp_mat_D,
                               const double*   ss_mat_Q_local,
                               const double*   sp_mat_Q,
                               const uint32_t* ss_first_inds_local,
                               const uint32_t* ss_second_inds_local,
                               const double*   ss_pair_data_local,
                               const uint32_t  ss_prim_pair_count_local,
                               const uint32_t* sp_first_inds,
                               const uint32_t* sp_second_inds,
                               const double*   sp_pair_data,
                               const uint32_t  sp_prim_pair_count,
                               const uint32_t* prim_cart_ao_to_atom_inds,
                               const double*   boys_func_table,
                               const double*   boys_func_ft,
                               const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombHessianSSSP_JJ_0(double*         hess_xy,
                               const uint32_t  hess_cart_ind_0,
                               const uint32_t  hess_cart_ind_1,
                               const double    prefac_coulomb,
                               const double*   s_prim_info,
                               const uint32_t  s_prim_count,
                               const double*   p_prim_info,
                               const uint32_t  p_prim_count,
                               const double*   ss_mat_D_local,
                               const double*   sp_mat_D,
                               const double*   ss_mat_Q_local,
                               const double*   sp_mat_Q,
                               const uint32_t* ss_first_inds_local,
                               const uint32_t* ss_second_inds_local,
                               const double*   ss_pair_data_local,
                               const uint32_t  ss_prim_pair_count_local,
                               const uint32_t* sp_first_inds,
                               const uint32_t* sp_second_inds,
                               const double*   sp_pair_data,
                               const uint32_t  sp_prim_pair_count,
                               const uint32_t* prim_cart_ao_to_atom_inds,
                               const double*   boys_func_table,
                               const double*   boys_func_ft,
                               const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombHessianSSSP_IJ_0(double*         hess_xy,
                               double*         hess_yx,
                               const uint32_t  hess_cart_ind_0,
                               const uint32_t  hess_cart_ind_1,
                               const double    prefac_coulomb,
                               const double*   s_prim_info,
                               const uint32_t  s_prim_count,
                               const double*   p_prim_info,
                               const uint32_t  p_prim_count,
                               const double*   ss_mat_D_local,
                               const double*   sp_mat_D,
                               const double*   ss_mat_Q_local,
                               const double*   sp_mat_Q,
                               const uint32_t* ss_first_inds_local,
                               const uint32_t* ss_second_inds_local,
                               const double*   ss_pair_data_local,
                               const uint32_t  ss_prim_pair_count_local,
                               const uint32_t* sp_first_inds,
                               const uint32_t* sp_second_inds,
                               const double*   sp_pair_data,
                               const uint32_t  sp_prim_pair_count,
                               const uint32_t* prim_cart_ao_to_atom_inds,
                               const uint32_t  natoms,
                               const double*   boys_func_table,
                               const double*   boys_func_ft,
                               const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombHessianSSSP_IK_0(double*         hess_xy,
                               double*         hess_yx,
                               const uint32_t  hess_cart_ind_0,
                               const uint32_t  hess_cart_ind_1,
                               const double    prefac_coulomb,
                               const double*   s_prim_info,
                               const uint32_t  s_prim_count,
                               const double*   p_prim_info,
                               const uint32_t  p_prim_count,
                               const double*   ss_mat_D_local,
                               const double*   sp_mat_D,
                               const double*   ss_mat_Q_local,
                               const double*   sp_mat_Q,
                               const uint32_t* ss_first_inds_local,
                               const uint32_t* ss_second_inds_local,
                               const double*   ss_pair_data_local,
                               const uint32_t  ss_prim_pair_count_local,
                               const uint32_t* sp_first_inds,
                               const uint32_t* sp_second_inds,
                               const double*   sp_pair_data,
                               const uint32_t  sp_prim_pair_count,
                               const uint32_t* prim_cart_ao_to_atom_inds,
                               const uint32_t  natoms,
                               const uint32_t* d_kl_inds_for_atom_k,
                               const uint32_t* d_kl_counts_for_atom_k,
                               const uint32_t* d_kl_displs_for_atom_k,
                               const double*   boys_func_table,
                               const double*   boys_func_ft,
                               const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombHessianSSSP_JK_0(double*         hess_xy,
                               double*         hess_yx,
                               const uint32_t  hess_cart_ind_0,
                               const uint32_t  hess_cart_ind_1,
                               const double    prefac_coulomb,
                               const double*   s_prim_info,
                               const uint32_t  s_prim_count,
                               const double*   p_prim_info,
                               const uint32_t  p_prim_count,
                               const double*   ss_mat_D_local,
                               const double*   sp_mat_D,
                               const double*   ss_mat_Q_local,
                               const double*   sp_mat_Q,
                               const uint32_t* ss_first_inds_local,
                               const uint32_t* ss_second_inds_local,
                               const double*   ss_pair_data_local,
                               const uint32_t  ss_prim_pair_count_local,
                               const uint32_t* sp_first_inds,
                               const uint32_t* sp_second_inds,
                               const double*   sp_pair_data,
                               const uint32_t  sp_prim_pair_count,
                               const uint32_t* prim_cart_ao_to_atom_inds,
                               const uint32_t  natoms,
                               const uint32_t* d_kl_inds_for_atom_k,
                               const uint32_t* d_kl_counts_for_atom_k,
                               const uint32_t* d_kl_displs_for_atom_k,
                               const double*   boys_func_table,
                               const double*   boys_func_ft,
                               const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombHessianSSSP_IL_0(double*         hess_xy,
                               double*         hess_yx,
                               const uint32_t  hess_cart_ind_0,
                               const uint32_t  hess_cart_ind_1,
                               const double    prefac_coulomb,
                               const double*   s_prim_info,
                               const uint32_t  s_prim_count,
                               const double*   p_prim_info,
                               const uint32_t  p_prim_count,
                               const double*   ss_mat_D_local,
                               const double*   sp_mat_D,
                               const double*   ss_mat_Q_local,
                               const double*   sp_mat_Q,
                               const uint32_t* ss_first_inds_local,
                               const uint32_t* ss_second_inds_local,
                               const double*   ss_pair_data_local,
                               const uint32_t  ss_prim_pair_count_local,
                               const uint32_t* sp_first_inds,
                               const uint32_t* sp_second_inds,
                               const double*   sp_pair_data,
                               const uint32_t  sp_prim_pair_count,
                               const uint32_t* prim_cart_ao_to_atom_inds,
                               const uint32_t  natoms,
                               const uint32_t* d_kl_inds_for_atom_l,
                               const uint32_t* d_kl_counts_for_atom_l,
                               const uint32_t* d_kl_displs_for_atom_l,
                               const double*   boys_func_table,
                               const double*   boys_func_ft,
                               const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombHessianSSSP_JL_0(double*         hess_xy,
                               double*         hess_yx,
                               const uint32_t  hess_cart_ind_0,
                               const uint32_t  hess_cart_ind_1,
                               const double    prefac_coulomb,
                               const double*   s_prim_info,
                               const uint32_t  s_prim_count,
                               const double*   p_prim_info,
                               const uint32_t  p_prim_count,
                               const double*   ss_mat_D_local,
                               const double*   sp_mat_D,
                               const double*   ss_mat_Q_local,
                               const double*   sp_mat_Q,
                               const uint32_t* ss_first_inds_local,
                               const uint32_t* ss_second_inds_local,
                               const double*   ss_pair_data_local,
                               const uint32_t  ss_prim_pair_count_local,
                               const uint32_t* sp_first_inds,
                               const uint32_t* sp_second_inds,
                               const double*   sp_pair_data,
                               const uint32_t  sp_prim_pair_count,
                               const uint32_t* prim_cart_ao_to_atom_inds,
                               const uint32_t  natoms,
                               const uint32_t* d_kl_inds_for_atom_l,
                               const uint32_t* d_kl_counts_for_atom_l,
                               const uint32_t* d_kl_displs_for_atom_l,
                               const double*   boys_func_table,
                               const double*   boys_func_ft,
                               const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombHessianSSSD_II_0(double*         hess_xy,
                               const uint32_t  hess_cart_ind_0,
                               const uint32_t  hess_cart_ind_1,
                               const double    prefac_coulomb,
                               const double*   s_prim_info,
                               const uint32_t  s_prim_count,
                               const double*   d_prim_info,
                               const uint32_t  d_prim_count,
                               const double*   ss_mat_D_local,
                               const double*   sd_mat_D,
                               const double*   ss_mat_Q_local,
                               const double*   sd_mat_Q,
                               const uint32_t* ss_first_inds_local,
                               const uint32_t* ss_second_inds_local,
                               const double*   ss_pair_data_local,
                               const uint32_t  ss_prim_pair_count_local,
                               const uint32_t* sd_first_inds,
                               const uint32_t* sd_second_inds,
                               const double*   sd_pair_data,
                               const uint32_t  sd_prim_pair_count,
                               const uint32_t* prim_cart_ao_to_atom_inds,
                               const double*   boys_func_table,
                               const double*   boys_func_ft,
                               const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombHessianSSSD_JJ_0(double*         hess_xy,
                               const uint32_t  hess_cart_ind_0,
                               const uint32_t  hess_cart_ind_1,
                               const double    prefac_coulomb,
                               const double*   s_prim_info,
                               const uint32_t  s_prim_count,
                               const double*   d_prim_info,
                               const uint32_t  d_prim_count,
                               const double*   ss_mat_D_local,
                               const double*   sd_mat_D,
                               const double*   ss_mat_Q_local,
                               const double*   sd_mat_Q,
                               const uint32_t* ss_first_inds_local,
                               const uint32_t* ss_second_inds_local,
                               const double*   ss_pair_data_local,
                               const uint32_t  ss_prim_pair_count_local,
                               const uint32_t* sd_first_inds,
                               const uint32_t* sd_second_inds,
                               const double*   sd_pair_data,
                               const uint32_t  sd_prim_pair_count,
                               const uint32_t* prim_cart_ao_to_atom_inds,
                               const double*   boys_func_table,
                               const double*   boys_func_ft,
                               const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombHessianSSSD_IJ_0(double*         hess_xy,
                               double*         hess_yx,
                               const uint32_t  hess_cart_ind_0,
                               const uint32_t  hess_cart_ind_1,
                               const double    prefac_coulomb,
                               const double*   s_prim_info,
                               const uint32_t  s_prim_count,
                               const double*   d_prim_info,
                               const uint32_t  d_prim_count,
                               const double*   ss_mat_D_local,
                               const double*   sd_mat_D,
                               const double*   ss_mat_Q_local,
                               const double*   sd_mat_Q,
                               const uint32_t* ss_first_inds_local,
                               const uint32_t* ss_second_inds_local,
                               const double*   ss_pair_data_local,
                               const uint32_t  ss_prim_pair_count_local,
                               const uint32_t* sd_first_inds,
                               const uint32_t* sd_second_inds,
                               const double*   sd_pair_data,
                               const uint32_t  sd_prim_pair_count,
                               const uint32_t* prim_cart_ao_to_atom_inds,
                               const uint32_t  natoms,
                               const double*   boys_func_table,
                               const double*   boys_func_ft,
                               const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombHessianSSSD_IK_0(double*         hess_xy,
                               double*         hess_yx,
                               const uint32_t  hess_cart_ind_0,
                               const uint32_t  hess_cart_ind_1,
                               const double    prefac_coulomb,
                               const double*   s_prim_info,
                               const uint32_t  s_prim_count,
                               const double*   d_prim_info,
                               const uint32_t  d_prim_count,
                               const double*   ss_mat_D_local,
                               const double*   sd_mat_D,
                               const double*   ss_mat_Q_local,
                               const double*   sd_mat_Q,
                               const uint32_t* ss_first_inds_local,
                               const uint32_t* ss_second_inds_local,
                               const double*   ss_pair_data_local,
                               const uint32_t  ss_prim_pair_count_local,
                               const uint32_t* sd_first_inds,
                               const uint32_t* sd_second_inds,
                               const double*   sd_pair_data,
                               const uint32_t  sd_prim_pair_count,
                               const uint32_t* prim_cart_ao_to_atom_inds,
                               const uint32_t  natoms,
                               const uint32_t* d_kl_inds_for_atom_k,
                               const uint32_t* d_kl_counts_for_atom_k,
                               const uint32_t* d_kl_displs_for_atom_k,
                               const double*   boys_func_table,
                               const double*   boys_func_ft,
                               const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombHessianSSSD_JK_0(double*         hess_xy,
                               double*         hess_yx,
                               const uint32_t  hess_cart_ind_0,
                               const uint32_t  hess_cart_ind_1,
                               const double    prefac_coulomb,
                               const double*   s_prim_info,
                               const uint32_t  s_prim_count,
                               const double*   d_prim_info,
                               const uint32_t  d_prim_count,
                               const double*   ss_mat_D_local,
                               const double*   sd_mat_D,
                               const double*   ss_mat_Q_local,
                               const double*   sd_mat_Q,
                               const uint32_t* ss_first_inds_local,
                               const uint32_t* ss_second_inds_local,
                               const double*   ss_pair_data_local,
                               const uint32_t  ss_prim_pair_count_local,
                               const uint32_t* sd_first_inds,
                               const uint32_t* sd_second_inds,
                               const double*   sd_pair_data,
                               const uint32_t  sd_prim_pair_count,
                               const uint32_t* prim_cart_ao_to_atom_inds,
                               const uint32_t  natoms,
                               const uint32_t* d_kl_inds_for_atom_k,
                               const uint32_t* d_kl_counts_for_atom_k,
                               const uint32_t* d_kl_displs_for_atom_k,
                               const double*   boys_func_table,
                               const double*   boys_func_ft,
                               const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombHessianSSSD_IL_0(double*         hess_xy,
                               double*         hess_yx,
                               const uint32_t  hess_cart_ind_0,
                               const uint32_t  hess_cart_ind_1,
                               const double    prefac_coulomb,
                               const double*   s_prim_info,
                               const uint32_t  s_prim_count,
                               const double*   d_prim_info,
                               const uint32_t  d_prim_count,
                               const double*   ss_mat_D_local,
                               const double*   sd_mat_D,
                               const double*   ss_mat_Q_local,
                               const double*   sd_mat_Q,
                               const uint32_t* ss_first_inds_local,
                               const uint32_t* ss_second_inds_local,
                               const double*   ss_pair_data_local,
                               const uint32_t  ss_prim_pair_count_local,
                               const uint32_t* sd_first_inds,
                               const uint32_t* sd_second_inds,
                               const double*   sd_pair_data,
                               const uint32_t  sd_prim_pair_count,
                               const uint32_t* prim_cart_ao_to_atom_inds,
                               const uint32_t  natoms,
                               const uint32_t* d_kl_inds_for_atom_l,
                               const uint32_t* d_kl_counts_for_atom_l,
                               const uint32_t* d_kl_displs_for_atom_l,
                               const double*   boys_func_table,
                               const double*   boys_func_ft,
                               const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombHessianSSSD_JL_0(double*         hess_xy,
                               double*         hess_yx,
                               const uint32_t  hess_cart_ind_0,
                               const uint32_t  hess_cart_ind_1,
                               const double    prefac_coulomb,
                               const double*   s_prim_info,
                               const uint32_t  s_prim_count,
                               const double*   d_prim_info,
                               const uint32_t  d_prim_count,
                               const double*   ss_mat_D_local,
                               const double*   sd_mat_D,
                               const double*   ss_mat_Q_local,
                               const double*   sd_mat_Q,
                               const uint32_t* ss_first_inds_local,
                               const uint32_t* ss_second_inds_local,
                               const double*   ss_pair_data_local,
                               const uint32_t  ss_prim_pair_count_local,
                               const uint32_t* sd_first_inds,
                               const uint32_t* sd_second_inds,
                               const double*   sd_pair_data,
                               const uint32_t  sd_prim_pair_count,
                               const uint32_t* prim_cart_ao_to_atom_inds,
                               const uint32_t  natoms,
                               const uint32_t* d_kl_inds_for_atom_l,
                               const uint32_t* d_kl_counts_for_atom_l,
                               const uint32_t* d_kl_displs_for_atom_l,
                               const double*   boys_func_table,
                               const double*   boys_func_ft,
                               const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombHessianSSPP_II_0(double*         hess_xy,
                               const uint32_t  hess_cart_ind_0,
                               const uint32_t  hess_cart_ind_1,
                               const double    prefac_coulomb,
                               const double*   s_prim_info,
                               const uint32_t  s_prim_count,
                               const double*   p_prim_info,
                               const uint32_t  p_prim_count,
                               const double*   ss_mat_D_local,
                               const double*   pp_mat_D,
                               const double*   ss_mat_Q_local,
                               const double*   pp_mat_Q,
                               const uint32_t* ss_first_inds_local,
                               const uint32_t* ss_second_inds_local,
                               const double*   ss_pair_data_local,
                               const uint32_t  ss_prim_pair_count_local,
                               const uint32_t* pp_first_inds,
                               const uint32_t* pp_second_inds,
                               const double*   pp_pair_data,
                               const uint32_t  pp_prim_pair_count,
                               const uint32_t* prim_cart_ao_to_atom_inds,
                               const double*   boys_func_table,
                               const double*   boys_func_ft,
                               const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombHessianSSPP_JJ_0(double*         hess_xy,
                               const uint32_t  hess_cart_ind_0,
                               const uint32_t  hess_cart_ind_1,
                               const double    prefac_coulomb,
                               const double*   s_prim_info,
                               const uint32_t  s_prim_count,
                               const double*   p_prim_info,
                               const uint32_t  p_prim_count,
                               const double*   ss_mat_D_local,
                               const double*   pp_mat_D,
                               const double*   ss_mat_Q_local,
                               const double*   pp_mat_Q,
                               const uint32_t* ss_first_inds_local,
                               const uint32_t* ss_second_inds_local,
                               const double*   ss_pair_data_local,
                               const uint32_t  ss_prim_pair_count_local,
                               const uint32_t* pp_first_inds,
                               const uint32_t* pp_second_inds,
                               const double*   pp_pair_data,
                               const uint32_t  pp_prim_pair_count,
                               const uint32_t* prim_cart_ao_to_atom_inds,
                               const double*   boys_func_table,
                               const double*   boys_func_ft,
                               const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombHessianSSPP_IJ_0(double*         hess_xy,
                               double*         hess_yx,
                               const uint32_t  hess_cart_ind_0,
                               const uint32_t  hess_cart_ind_1,
                               const double    prefac_coulomb,
                               const double*   s_prim_info,
                               const uint32_t  s_prim_count,
                               const double*   p_prim_info,
                               const uint32_t  p_prim_count,
                               const double*   ss_mat_D_local,
                               const double*   pp_mat_D,
                               const double*   ss_mat_Q_local,
                               const double*   pp_mat_Q,
                               const uint32_t* ss_first_inds_local,
                               const uint32_t* ss_second_inds_local,
                               const double*   ss_pair_data_local,
                               const uint32_t  ss_prim_pair_count_local,
                               const uint32_t* pp_first_inds,
                               const uint32_t* pp_second_inds,
                               const double*   pp_pair_data,
                               const uint32_t  pp_prim_pair_count,
                               const uint32_t* prim_cart_ao_to_atom_inds,
                               const uint32_t  natoms,
                               const double*   boys_func_table,
                               const double*   boys_func_ft,
                               const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombHessianSSPP_IK_0(double*         hess_xy,
                               double*         hess_yx,
                               const uint32_t  hess_cart_ind_0,
                               const uint32_t  hess_cart_ind_1,
                               const double    prefac_coulomb,
                               const double*   s_prim_info,
                               const uint32_t  s_prim_count,
                               const double*   p_prim_info,
                               const uint32_t  p_prim_count,
                               const double*   ss_mat_D_local,
                               const double*   pp_mat_D,
                               const double*   ss_mat_Q_local,
                               const double*   pp_mat_Q,
                               const uint32_t* ss_first_inds_local,
                               const uint32_t* ss_second_inds_local,
                               const double*   ss_pair_data_local,
                               const uint32_t  ss_prim_pair_count_local,
                               const uint32_t* pp_first_inds,
                               const uint32_t* pp_second_inds,
                               const double*   pp_pair_data,
                               const uint32_t  pp_prim_pair_count,
                               const uint32_t* prim_cart_ao_to_atom_inds,
                               const uint32_t  natoms,
                               const uint32_t* d_kl_inds_for_atom_k,
                               const uint32_t* d_kl_counts_for_atom_k,
                               const uint32_t* d_kl_displs_for_atom_k,
                               const double*   boys_func_table,
                               const double*   boys_func_ft,
                               const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombHessianSSPP_JK_0(double*         hess_xy,
                               double*         hess_yx,
                               const uint32_t  hess_cart_ind_0,
                               const uint32_t  hess_cart_ind_1,
                               const double    prefac_coulomb,
                               const double*   s_prim_info,
                               const uint32_t  s_prim_count,
                               const double*   p_prim_info,
                               const uint32_t  p_prim_count,
                               const double*   ss_mat_D_local,
                               const double*   pp_mat_D,
                               const double*   ss_mat_Q_local,
                               const double*   pp_mat_Q,
                               const uint32_t* ss_first_inds_local,
                               const uint32_t* ss_second_inds_local,
                               const double*   ss_pair_data_local,
                               const uint32_t  ss_prim_pair_count_local,
                               const uint32_t* pp_first_inds,
                               const uint32_t* pp_second_inds,
                               const double*   pp_pair_data,
                               const uint32_t  pp_prim_pair_count,
                               const uint32_t* prim_cart_ao_to_atom_inds,
                               const uint32_t  natoms,
                               const uint32_t* d_kl_inds_for_atom_k,
                               const uint32_t* d_kl_counts_for_atom_k,
                               const uint32_t* d_kl_displs_for_atom_k,
                               const double*   boys_func_table,
                               const double*   boys_func_ft,
                               const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombHessianSSPP_IL_0(double*         hess_xy,
                               double*         hess_yx,
                               const uint32_t  hess_cart_ind_0,
                               const uint32_t  hess_cart_ind_1,
                               const double    prefac_coulomb,
                               const double*   s_prim_info,
                               const uint32_t  s_prim_count,
                               const double*   p_prim_info,
                               const uint32_t  p_prim_count,
                               const double*   ss_mat_D_local,
                               const double*   pp_mat_D,
                               const double*   ss_mat_Q_local,
                               const double*   pp_mat_Q,
                               const uint32_t* ss_first_inds_local,
                               const uint32_t* ss_second_inds_local,
                               const double*   ss_pair_data_local,
                               const uint32_t  ss_prim_pair_count_local,
                               const uint32_t* pp_first_inds,
                               const uint32_t* pp_second_inds,
                               const double*   pp_pair_data,
                               const uint32_t  pp_prim_pair_count,
                               const uint32_t* prim_cart_ao_to_atom_inds,
                               const uint32_t  natoms,
                               const uint32_t* d_kl_inds_for_atom_l,
                               const uint32_t* d_kl_counts_for_atom_l,
                               const uint32_t* d_kl_displs_for_atom_l,
                               const double*   boys_func_table,
                               const double*   boys_func_ft,
                               const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombHessianSSPP_JL_0(double*         hess_xy,
                               double*         hess_yx,
                               const uint32_t  hess_cart_ind_0,
                               const uint32_t  hess_cart_ind_1,
                               const double    prefac_coulomb,
                               const double*   s_prim_info,
                               const uint32_t  s_prim_count,
                               const double*   p_prim_info,
                               const uint32_t  p_prim_count,
                               const double*   ss_mat_D_local,
                               const double*   pp_mat_D,
                               const double*   ss_mat_Q_local,
                               const double*   pp_mat_Q,
                               const uint32_t* ss_first_inds_local,
                               const uint32_t* ss_second_inds_local,
                               const double*   ss_pair_data_local,
                               const uint32_t  ss_prim_pair_count_local,
                               const uint32_t* pp_first_inds,
                               const uint32_t* pp_second_inds,
                               const double*   pp_pair_data,
                               const uint32_t  pp_prim_pair_count,
                               const uint32_t* prim_cart_ao_to_atom_inds,
                               const uint32_t  natoms,
                               const uint32_t* d_kl_inds_for_atom_l,
                               const uint32_t* d_kl_counts_for_atom_l,
                               const uint32_t* d_kl_displs_for_atom_l,
                               const double*   boys_func_table,
                               const double*   boys_func_ft,
                               const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombHessianSSPD_II_0(double*         hess_xy,
                               const uint32_t  hess_cart_ind_0,
                               const uint32_t  hess_cart_ind_1,
                               const double    prefac_coulomb,
                               const double*   s_prim_info,
                               const uint32_t  s_prim_count,
                               const double*   p_prim_info,
                               const uint32_t  p_prim_count,
                               const double*   d_prim_info,
                               const uint32_t  d_prim_count,
                               const double*   ss_mat_D_local,
                               const double*   pd_mat_D,
                               const double*   ss_mat_Q_local,
                               const double*   pd_mat_Q,
                               const uint32_t* ss_first_inds_local,
                               const uint32_t* ss_second_inds_local,
                               const double*   ss_pair_data_local,
                               const uint32_t  ss_prim_pair_count_local,
                               const uint32_t* pd_first_inds,
                               const uint32_t* pd_second_inds,
                               const double*   pd_pair_data,
                               const uint32_t  pd_prim_pair_count,
                               const uint32_t* prim_cart_ao_to_atom_inds,
                               const double*   boys_func_table,
                               const double*   boys_func_ft,
                               const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombHessianSSPD_JJ_0(double*         hess_xy,
                               const uint32_t  hess_cart_ind_0,
                               const uint32_t  hess_cart_ind_1,
                               const double    prefac_coulomb,
                               const double*   s_prim_info,
                               const uint32_t  s_prim_count,
                               const double*   p_prim_info,
                               const uint32_t  p_prim_count,
                               const double*   d_prim_info,
                               const uint32_t  d_prim_count,
                               const double*   ss_mat_D_local,
                               const double*   pd_mat_D,
                               const double*   ss_mat_Q_local,
                               const double*   pd_mat_Q,
                               const uint32_t* ss_first_inds_local,
                               const uint32_t* ss_second_inds_local,
                               const double*   ss_pair_data_local,
                               const uint32_t  ss_prim_pair_count_local,
                               const uint32_t* pd_first_inds,
                               const uint32_t* pd_second_inds,
                               const double*   pd_pair_data,
                               const uint32_t  pd_prim_pair_count,
                               const uint32_t* prim_cart_ao_to_atom_inds,
                               const double*   boys_func_table,
                               const double*   boys_func_ft,
                               const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombHessianSSPD_IJ_0(double*         hess_xy,
                               double*         hess_yx,
                               const uint32_t  hess_cart_ind_0,
                               const uint32_t  hess_cart_ind_1,
                               const double    prefac_coulomb,
                               const double*   s_prim_info,
                               const uint32_t  s_prim_count,
                               const double*   p_prim_info,
                               const uint32_t  p_prim_count,
                               const double*   d_prim_info,
                               const uint32_t  d_prim_count,
                               const double*   ss_mat_D_local,
                               const double*   pd_mat_D,
                               const double*   ss_mat_Q_local,
                               const double*   pd_mat_Q,
                               const uint32_t* ss_first_inds_local,
                               const uint32_t* ss_second_inds_local,
                               const double*   ss_pair_data_local,
                               const uint32_t  ss_prim_pair_count_local,
                               const uint32_t* pd_first_inds,
                               const uint32_t* pd_second_inds,
                               const double*   pd_pair_data,
                               const uint32_t  pd_prim_pair_count,
                               const uint32_t* prim_cart_ao_to_atom_inds,
                               const uint32_t  natoms,
                               const double*   boys_func_table,
                               const double*   boys_func_ft,
                               const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombHessianSSPD_IK_0(double*         hess_xy,
                               double*         hess_yx,
                               const uint32_t  hess_cart_ind_0,
                               const uint32_t  hess_cart_ind_1,
                               const double    prefac_coulomb,
                               const double*   s_prim_info,
                               const uint32_t  s_prim_count,
                               const double*   p_prim_info,
                               const uint32_t  p_prim_count,
                               const double*   d_prim_info,
                               const uint32_t  d_prim_count,
                               const double*   ss_mat_D_local,
                               const double*   pd_mat_D,
                               const double*   ss_mat_Q_local,
                               const double*   pd_mat_Q,
                               const uint32_t* ss_first_inds_local,
                               const uint32_t* ss_second_inds_local,
                               const double*   ss_pair_data_local,
                               const uint32_t  ss_prim_pair_count_local,
                               const uint32_t* pd_first_inds,
                               const uint32_t* pd_second_inds,
                               const double*   pd_pair_data,
                               const uint32_t  pd_prim_pair_count,
                               const uint32_t* prim_cart_ao_to_atom_inds,
                               const uint32_t  natoms,
                               const uint32_t* d_kl_inds_for_atom_k,
                               const uint32_t* d_kl_counts_for_atom_k,
                               const uint32_t* d_kl_displs_for_atom_k,
                               const double*   boys_func_table,
                               const double*   boys_func_ft,
                               const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombHessianSSPD_JK_0(double*         hess_xy,
                               double*         hess_yx,
                               const uint32_t  hess_cart_ind_0,
                               const uint32_t  hess_cart_ind_1,
                               const double    prefac_coulomb,
                               const double*   s_prim_info,
                               const uint32_t  s_prim_count,
                               const double*   p_prim_info,
                               const uint32_t  p_prim_count,
                               const double*   d_prim_info,
                               const uint32_t  d_prim_count,
                               const double*   ss_mat_D_local,
                               const double*   pd_mat_D,
                               const double*   ss_mat_Q_local,
                               const double*   pd_mat_Q,
                               const uint32_t* ss_first_inds_local,
                               const uint32_t* ss_second_inds_local,
                               const double*   ss_pair_data_local,
                               const uint32_t  ss_prim_pair_count_local,
                               const uint32_t* pd_first_inds,
                               const uint32_t* pd_second_inds,
                               const double*   pd_pair_data,
                               const uint32_t  pd_prim_pair_count,
                               const uint32_t* prim_cart_ao_to_atom_inds,
                               const uint32_t  natoms,
                               const uint32_t* d_kl_inds_for_atom_k,
                               const uint32_t* d_kl_counts_for_atom_k,
                               const uint32_t* d_kl_displs_for_atom_k,
                               const double*   boys_func_table,
                               const double*   boys_func_ft,
                               const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombHessianSSPD_IL_0(double*         hess_xy,
                               double*         hess_yx,
                               const uint32_t  hess_cart_ind_0,
                               const uint32_t  hess_cart_ind_1,
                               const double    prefac_coulomb,
                               const double*   s_prim_info,
                               const uint32_t  s_prim_count,
                               const double*   p_prim_info,
                               const uint32_t  p_prim_count,
                               const double*   d_prim_info,
                               const uint32_t  d_prim_count,
                               const double*   ss_mat_D_local,
                               const double*   pd_mat_D,
                               const double*   ss_mat_Q_local,
                               const double*   pd_mat_Q,
                               const uint32_t* ss_first_inds_local,
                               const uint32_t* ss_second_inds_local,
                               const double*   ss_pair_data_local,
                               const uint32_t  ss_prim_pair_count_local,
                               const uint32_t* pd_first_inds,
                               const uint32_t* pd_second_inds,
                               const double*   pd_pair_data,
                               const uint32_t  pd_prim_pair_count,
                               const uint32_t* prim_cart_ao_to_atom_inds,
                               const uint32_t  natoms,
                               const uint32_t* d_kl_inds_for_atom_l,
                               const uint32_t* d_kl_counts_for_atom_l,
                               const uint32_t* d_kl_displs_for_atom_l,
                               const double*   boys_func_table,
                               const double*   boys_func_ft,
                               const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombHessianSSPD_JL_0(double*         hess_xy,
                               double*         hess_yx,
                               const uint32_t  hess_cart_ind_0,
                               const uint32_t  hess_cart_ind_1,
                               const double    prefac_coulomb,
                               const double*   s_prim_info,
                               const uint32_t  s_prim_count,
                               const double*   p_prim_info,
                               const uint32_t  p_prim_count,
                               const double*   d_prim_info,
                               const uint32_t  d_prim_count,
                               const double*   ss_mat_D_local,
                               const double*   pd_mat_D,
                               const double*   ss_mat_Q_local,
                               const double*   pd_mat_Q,
                               const uint32_t* ss_first_inds_local,
                               const uint32_t* ss_second_inds_local,
                               const double*   ss_pair_data_local,
                               const uint32_t  ss_prim_pair_count_local,
                               const uint32_t* pd_first_inds,
                               const uint32_t* pd_second_inds,
                               const double*   pd_pair_data,
                               const uint32_t  pd_prim_pair_count,
                               const uint32_t* prim_cart_ao_to_atom_inds,
                               const uint32_t  natoms,
                               const uint32_t* d_kl_inds_for_atom_l,
                               const uint32_t* d_kl_counts_for_atom_l,
                               const uint32_t* d_kl_displs_for_atom_l,
                               const double*   boys_func_table,
                               const double*   boys_func_ft,
                               const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombHessianSSDD_II_0(double*         hess_xy,
                               const uint32_t  hess_cart_ind_0,
                               const uint32_t  hess_cart_ind_1,
                               const double    prefac_coulomb,
                               const double*   s_prim_info,
                               const uint32_t  s_prim_count,
                               const double*   d_prim_info,
                               const uint32_t  d_prim_count,
                               const double*   ss_mat_D_local,
                               const double*   dd_mat_D,
                               const double*   ss_mat_Q_local,
                               const double*   dd_mat_Q,
                               const uint32_t* ss_first_inds_local,
                               const uint32_t* ss_second_inds_local,
                               const double*   ss_pair_data_local,
                               const uint32_t  ss_prim_pair_count_local,
                               const uint32_t* dd_first_inds,
                               const uint32_t* dd_second_inds,
                               const double*   dd_pair_data,
                               const uint32_t  dd_prim_pair_count,
                               const uint32_t* prim_cart_ao_to_atom_inds,
                               const double*   boys_func_table,
                               const double*   boys_func_ft,
                               const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombHessianSSDD_JJ_0(double*         hess_xy,
                               const uint32_t  hess_cart_ind_0,
                               const uint32_t  hess_cart_ind_1,
                               const double    prefac_coulomb,
                               const double*   s_prim_info,
                               const uint32_t  s_prim_count,
                               const double*   d_prim_info,
                               const uint32_t  d_prim_count,
                               const double*   ss_mat_D_local,
                               const double*   dd_mat_D,
                               const double*   ss_mat_Q_local,
                               const double*   dd_mat_Q,
                               const uint32_t* ss_first_inds_local,
                               const uint32_t* ss_second_inds_local,
                               const double*   ss_pair_data_local,
                               const uint32_t  ss_prim_pair_count_local,
                               const uint32_t* dd_first_inds,
                               const uint32_t* dd_second_inds,
                               const double*   dd_pair_data,
                               const uint32_t  dd_prim_pair_count,
                               const uint32_t* prim_cart_ao_to_atom_inds,
                               const double*   boys_func_table,
                               const double*   boys_func_ft,
                               const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombHessianSSDD_IJ_0(double*         hess_xy,
                               double*         hess_yx,
                               const uint32_t  hess_cart_ind_0,
                               const uint32_t  hess_cart_ind_1,
                               const double    prefac_coulomb,
                               const double*   s_prim_info,
                               const uint32_t  s_prim_count,
                               const double*   d_prim_info,
                               const uint32_t  d_prim_count,
                               const double*   ss_mat_D_local,
                               const double*   dd_mat_D,
                               const double*   ss_mat_Q_local,
                               const double*   dd_mat_Q,
                               const uint32_t* ss_first_inds_local,
                               const uint32_t* ss_second_inds_local,
                               const double*   ss_pair_data_local,
                               const uint32_t  ss_prim_pair_count_local,
                               const uint32_t* dd_first_inds,
                               const uint32_t* dd_second_inds,
                               const double*   dd_pair_data,
                               const uint32_t  dd_prim_pair_count,
                               const uint32_t* prim_cart_ao_to_atom_inds,
                               const uint32_t  natoms,
                               const double*   boys_func_table,
                               const double*   boys_func_ft,
                               const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombHessianSSDD_IK_0(double*         hess_xy,
                               double*         hess_yx,
                               const uint32_t  hess_cart_ind_0,
                               const uint32_t  hess_cart_ind_1,
                               const double    prefac_coulomb,
                               const double*   s_prim_info,
                               const uint32_t  s_prim_count,
                               const double*   d_prim_info,
                               const uint32_t  d_prim_count,
                               const double*   ss_mat_D_local,
                               const double*   dd_mat_D,
                               const double*   ss_mat_Q_local,
                               const double*   dd_mat_Q,
                               const uint32_t* ss_first_inds_local,
                               const uint32_t* ss_second_inds_local,
                               const double*   ss_pair_data_local,
                               const uint32_t  ss_prim_pair_count_local,
                               const uint32_t* dd_first_inds,
                               const uint32_t* dd_second_inds,
                               const double*   dd_pair_data,
                               const uint32_t  dd_prim_pair_count,
                               const uint32_t* prim_cart_ao_to_atom_inds,
                               const uint32_t  natoms,
                               const uint32_t* d_kl_inds_for_atom_k,
                               const uint32_t* d_kl_counts_for_atom_k,
                               const uint32_t* d_kl_displs_for_atom_k,
                               const double*   boys_func_table,
                               const double*   boys_func_ft,
                               const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombHessianSSDD_JK_0(double*         hess_xy,
                               double*         hess_yx,
                               const uint32_t  hess_cart_ind_0,
                               const uint32_t  hess_cart_ind_1,
                               const double    prefac_coulomb,
                               const double*   s_prim_info,
                               const uint32_t  s_prim_count,
                               const double*   d_prim_info,
                               const uint32_t  d_prim_count,
                               const double*   ss_mat_D_local,
                               const double*   dd_mat_D,
                               const double*   ss_mat_Q_local,
                               const double*   dd_mat_Q,
                               const uint32_t* ss_first_inds_local,
                               const uint32_t* ss_second_inds_local,
                               const double*   ss_pair_data_local,
                               const uint32_t  ss_prim_pair_count_local,
                               const uint32_t* dd_first_inds,
                               const uint32_t* dd_second_inds,
                               const double*   dd_pair_data,
                               const uint32_t  dd_prim_pair_count,
                               const uint32_t* prim_cart_ao_to_atom_inds,
                               const uint32_t  natoms,
                               const uint32_t* d_kl_inds_for_atom_k,
                               const uint32_t* d_kl_counts_for_atom_k,
                               const uint32_t* d_kl_displs_for_atom_k,
                               const double*   boys_func_table,
                               const double*   boys_func_ft,
                               const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombHessianSSDD_IL_0(double*         hess_xy,
                               double*         hess_yx,
                               const uint32_t  hess_cart_ind_0,
                               const uint32_t  hess_cart_ind_1,
                               const double    prefac_coulomb,
                               const double*   s_prim_info,
                               const uint32_t  s_prim_count,
                               const double*   d_prim_info,
                               const uint32_t  d_prim_count,
                               const double*   ss_mat_D_local,
                               const double*   dd_mat_D,
                               const double*   ss_mat_Q_local,
                               const double*   dd_mat_Q,
                               const uint32_t* ss_first_inds_local,
                               const uint32_t* ss_second_inds_local,
                               const double*   ss_pair_data_local,
                               const uint32_t  ss_prim_pair_count_local,
                               const uint32_t* dd_first_inds,
                               const uint32_t* dd_second_inds,
                               const double*   dd_pair_data,
                               const uint32_t  dd_prim_pair_count,
                               const uint32_t* prim_cart_ao_to_atom_inds,
                               const uint32_t  natoms,
                               const uint32_t* d_kl_inds_for_atom_l,
                               const uint32_t* d_kl_counts_for_atom_l,
                               const uint32_t* d_kl_displs_for_atom_l,
                               const double*   boys_func_table,
                               const double*   boys_func_ft,
                               const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombHessianSSDD_JL_0(double*         hess_xy,
                               double*         hess_yx,
                               const uint32_t  hess_cart_ind_0,
                               const uint32_t  hess_cart_ind_1,
                               const double    prefac_coulomb,
                               const double*   s_prim_info,
                               const uint32_t  s_prim_count,
                               const double*   d_prim_info,
                               const uint32_t  d_prim_count,
                               const double*   ss_mat_D_local,
                               const double*   dd_mat_D,
                               const double*   ss_mat_Q_local,
                               const double*   dd_mat_Q,
                               const uint32_t* ss_first_inds_local,
                               const uint32_t* ss_second_inds_local,
                               const double*   ss_pair_data_local,
                               const uint32_t  ss_prim_pair_count_local,
                               const uint32_t* dd_first_inds,
                               const uint32_t* dd_second_inds,
                               const double*   dd_pair_data,
                               const uint32_t  dd_prim_pair_count,
                               const uint32_t* prim_cart_ao_to_atom_inds,
                               const uint32_t  natoms,
                               const uint32_t* d_kl_inds_for_atom_l,
                               const uint32_t* d_kl_counts_for_atom_l,
                               const uint32_t* d_kl_displs_for_atom_l,
                               const double*   boys_func_table,
                               const double*   boys_func_ft,
                               const double    eri_threshold);

}  // namespace gpu

#endif
