//
//                              VELOXCHEM
//         ----------------------------------------------------
//                     An Electronic Structure Code
//
//  Copyright © 2018-2023 by VeloxChem developers. All rights reserved.
//  Contact: https://veloxchem.org/contact
//
//  SPDX-License-Identifier: LGPL-3.0-or-later
//
//  This file is part of VeloxChem.
//
//  VeloxChem is free software: you can redistribute it and/or modify it under
//  the terms of the GNU Lesser General Public License as published by the Free
//  Software Foundation, either version 3 of the License, or (at your option)
//  any later version.
//
//  VeloxChem is distributed in the hope that it will be useful, but WITHOUT
//  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
//  FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
//  License for more details.
//
//  You should have received a copy of the GNU Lesser General Public License
//  along with VeloxChem. If not, see <https://www.gnu.org/licenses/>.

#ifndef EriCoulombExchange_hpp
#define EriCoulombExchange_hpp

#include <cstdint>

namespace gpu {  // gpu namespace

__global__ void
zeroData(double* d_data, const uint32_t n);

__global__ void
computeCoulombFockSSSS(double*         mat_J,
                       const double*   s_prim_info,
                       const uint32_t  s_prim_count,
                       const double*   mat_D,
                       const double*   mat_Q_local,
                       const double*   mat_Q,
                       const uint32_t* first_inds_local,
                       const uint32_t* second_inds_local,
                       const uint32_t  ss_prim_pair_count_local,
                       const uint32_t* first_inds,
                       const uint32_t* second_inds,
                       const uint32_t  ss_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft);

__global__ void
computeCoulombFockSSSP(double*         mat_J,
                       const double*   s_prim_info,
                       const uint32_t  s_prim_count,
                       const double*   p_prim_info,
                       const uint32_t  p_prim_count,
                       const double*   sp_mat_D,
                       const double*   ss_mat_Q_local,
                       const double*   sp_mat_Q,
                       const uint32_t* ss_first_inds_local,
                       const uint32_t* ss_second_inds_local,
                       const uint32_t  ss_prim_pair_count_local,
                       const uint32_t* sp_first_inds,
                       const uint32_t* sp_second_inds,
                       const uint32_t  sp_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft);

__global__ void
computeCoulombFockSSSD(double*         mat_J,
                       const double*   s_prim_info,
                       const uint32_t  s_prim_count,
                       const double*   d_prim_info,
                       const uint32_t  d_prim_count,
                       const double*   sd_mat_D,
                       const double*   ss_mat_Q_local,
                       const double*   sd_mat_Q,
                       const uint32_t* ss_first_inds_local,
                       const uint32_t* ss_second_inds_local,
                       const uint32_t  ss_prim_pair_count_local,
                       const uint32_t* sd_first_inds,
                       const uint32_t* sd_second_inds,
                       const uint32_t  sd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft);

__global__ void
computeCoulombFockSSPP(double*         mat_J,
                       const double*   s_prim_info,
                       const uint32_t  s_prim_count,
                       const double*   p_prim_info,
                       const uint32_t  p_prim_count,
                       const double*   pp_mat_D,
                       const double*   ss_mat_Q_local,
                       const double*   pp_mat_Q,
                       const uint32_t* ss_first_inds_local,
                       const uint32_t* ss_second_inds_local,
                       const uint32_t  ss_prim_pair_count_local,
                       const uint32_t* pp_first_inds,
                       const uint32_t* pp_second_inds,
                       const uint32_t  pp_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft);

__global__ void
computeCoulombFockSSPD(double*         mat_J,
                       const double*   s_prim_info,
                       const uint32_t  s_prim_count,
                       const double*   p_prim_info,
                       const uint32_t  p_prim_count,
                       const double*   d_prim_info,
                       const uint32_t  d_prim_count,
                       const double*   pd_mat_D,
                       const double*   ss_mat_Q_local,
                       const double*   pd_mat_Q,
                       const uint32_t* ss_first_inds_local,
                       const uint32_t* ss_second_inds_local,
                       const uint32_t  ss_prim_pair_count_local,
                       const uint32_t* pd_first_inds,
                       const uint32_t* pd_second_inds,
                       const uint32_t  pd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft);

__global__ void
computeCoulombFockSSDD(double*         mat_J,
                       const double*   s_prim_info,
                       const uint32_t  s_prim_count,
                       const double*   d_prim_info,
                       const uint32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   ss_mat_Q_local,
                       const double*   dd_mat_Q,
                       const uint32_t* ss_first_inds_local,
                       const uint32_t* ss_second_inds_local,
                       const uint32_t  ss_prim_pair_count_local,
                       const uint32_t* dd_first_inds,
                       const uint32_t* dd_second_inds,
                       const uint32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft);

__global__ void
computeCoulombFockSPSS(double*         mat_J,
                       const double*   s_prim_info,
                       const uint32_t  s_prim_count,
                       const double*   p_prim_info,
                       const uint32_t  p_prim_count,
                       const double*   ss_mat_D,
                       const double*   ss_mat_Q,
                       const double*   sp_mat_Q_local,
                       const uint32_t* ss_first_inds,
                       const uint32_t* ss_second_inds,
                       const uint32_t  ss_prim_pair_count,
                       const uint32_t* sp_first_inds_local,
                       const uint32_t* sp_second_inds_local,
                       const uint32_t  sp_prim_pair_count_local,
                       const double*   boys_func_table,
                       const double*   boys_func_ft);

__global__ void
computeCoulombFockSPSP(double*         mat_J,
                       const double*   s_prim_info,
                       const uint32_t  s_prim_count,
                       const double*   p_prim_info,
                       const uint32_t  p_prim_count,
                       const double*   sp_mat_D,
                       const double*   sp_mat_Q_local,
                       const double*   sp_mat_Q,
                       const uint32_t* sp_first_inds_local,
                       const uint32_t* sp_second_inds_local,
                       const uint32_t  sp_prim_pair_count_local,
                       const uint32_t* sp_first_inds,
                       const uint32_t* sp_second_inds,
                       const uint32_t  sp_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft);

__global__ void
computeCoulombFockSPSD(double*         mat_J,
                       const double*   s_prim_info,
                       const uint32_t  s_prim_count,
                       const double*   p_prim_info,
                       const uint32_t  p_prim_count,
                       const double*   d_prim_info,
                       const uint32_t  d_prim_count,
                       const double*   sd_mat_D,
                       const double*   sp_mat_Q_local,
                       const double*   sd_mat_Q,
                       const uint32_t* sp_first_inds_local,
                       const uint32_t* sp_second_inds_local,
                       const uint32_t  sp_prim_pair_count_local,
                       const uint32_t* sd_first_inds,
                       const uint32_t* sd_second_inds,
                       const uint32_t  sd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft);

__global__ void
computeCoulombFockSPPP(double*         mat_J,
                       const double*   s_prim_info,
                       const uint32_t  s_prim_count,
                       const double*   p_prim_info,
                       const uint32_t  p_prim_count,
                       const double*   pp_mat_D,
                       const double*   sp_mat_Q_local,
                       const double*   pp_mat_Q,
                       const uint32_t* sp_first_inds_local,
                       const uint32_t* sp_second_inds_local,
                       const uint32_t  sp_prim_pair_count_local,
                       const uint32_t* pp_first_inds,
                       const uint32_t* pp_second_inds,
                       const uint32_t  pp_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft);

__global__ void
computeCoulombFockSPPD(double*         mat_J,
                       const double*   s_prim_info,
                       const uint32_t  s_prim_count,
                       const double*   p_prim_info,
                       const uint32_t  p_prim_count,
                       const double*   d_prim_info,
                       const uint32_t  d_prim_count,
                       const double*   pd_mat_D,
                       const double*   sp_mat_Q_local,
                       const double*   pd_mat_Q,
                       const uint32_t* sp_first_inds_local,
                       const uint32_t* sp_second_inds_local,
                       const uint32_t  sp_prim_pair_count_local,
                       const uint32_t* pd_first_inds,
                       const uint32_t* pd_second_inds,
                       const uint32_t  pd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft);

__global__ void
computeCoulombFockSPDD(double*         mat_J,
                       const double*   s_prim_info,
                       const uint32_t  s_prim_count,
                       const double*   p_prim_info,
                       const uint32_t  p_prim_count,
                       const double*   d_prim_info,
                       const uint32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   sp_mat_Q_local,
                       const double*   dd_mat_Q,
                       const uint32_t* sp_first_inds_local,
                       const uint32_t* sp_second_inds_local,
                       const uint32_t  sp_prim_pair_count_local,
                       const uint32_t* dd_first_inds,
                       const uint32_t* dd_second_inds,
                       const uint32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft);

__global__ void
computeCoulombFockPPSS(double*         mat_J,
                       const double*   s_prim_info,
                       const uint32_t  s_prim_count,
                       const double*   p_prim_info,
                       const uint32_t  p_prim_count,
                       const double*   ss_mat_D,
                       const double*   ss_mat_Q,
                       const double*   pp_mat_Q_local,
                       const uint32_t* ss_first_inds,
                       const uint32_t* ss_second_inds,
                       const uint32_t  ss_prim_pair_count,
                       const uint32_t* pp_first_inds_local,
                       const uint32_t* pp_second_inds_local,
                       const uint32_t  pp_prim_pair_count_local,
                       const double*   boys_func_table,
                       const double*   boys_func_ft);

__global__ void
computeCoulombFockPPSP(double*         mat_J,
                       const double*   s_prim_info,
                       const uint32_t  s_prim_count,
                       const double*   p_prim_info,
                       const uint32_t  p_prim_count,
                       const double*   sp_mat_D,
                       const double*   sp_mat_Q,
                       const double*   pp_mat_Q_local,
                       const uint32_t* sp_first_inds,
                       const uint32_t* sp_second_inds,
                       const uint32_t  sp_prim_pair_count,
                       const uint32_t* pp_first_inds_local,
                       const uint32_t* pp_second_inds_local,
                       const uint32_t  pp_prim_pair_count_local,
                       const double*   boys_func_table,
                       const double*   boys_func_ft);

__global__ void
computeCoulombFockPPSD(double*         mat_J,
                       const double*   s_prim_info,
                       const uint32_t  s_prim_count,
                       const double*   p_prim_info,
                       const uint32_t  p_prim_count,
                       const double*   d_prim_info,
                       const uint32_t  d_prim_count,
                       const double*   sd_mat_D,
                       const double*   pp_mat_Q_local,
                       const double*   sd_mat_Q,
                       const uint32_t* pp_first_inds_local,
                       const uint32_t* pp_second_inds_local,
                       const uint32_t  pp_prim_pair_count_local,
                       const uint32_t* sd_first_inds,
                       const uint32_t* sd_second_inds,
                       const uint32_t  sd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft);

__global__ void
computeCoulombFockPPPP(double*         mat_J,
                       const double*   p_prim_info,
                       const uint32_t  p_prim_count,
                       const double*   pp_mat_D,
                       const double*   pp_mat_Q_local,
                       const double*   pp_mat_Q,
                       const uint32_t* pp_first_inds_local,
                       const uint32_t* pp_second_inds_local,
                       const uint32_t  pp_prim_pair_count_local,
                       const uint32_t* pp_first_inds,
                       const uint32_t* pp_second_inds,
                       const uint32_t  pp_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft);

__global__ void
computeCoulombFockPPPD(double*         mat_J,
                       const double*   p_prim_info,
                       const uint32_t  p_prim_count,
                       const double*   d_prim_info,
                       const uint32_t  d_prim_count,
                       const double*   pd_mat_D,
                       const double*   pp_mat_Q_local,
                       const double*   pd_mat_Q,
                       const uint32_t* pp_first_inds_local,
                       const uint32_t* pp_second_inds_local,
                       const uint32_t  pp_prim_pair_count_local,
                       const uint32_t* pd_first_inds,
                       const uint32_t* pd_second_inds,
                       const uint32_t  pd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft);

__global__ void
computeCoulombFockPPDD(double*         mat_J,
                       const double*   p_prim_info,
                       const uint32_t  p_prim_count,
                       const double*   d_prim_info,
                       const uint32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   pp_mat_Q_local,
                       const double*   dd_mat_Q,
                       const uint32_t* pp_first_inds_local,
                       const uint32_t* pp_second_inds_local,
                       const uint32_t  pp_prim_pair_count_local,
                       const uint32_t* dd_first_inds,
                       const uint32_t* dd_second_inds,
                       const uint32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft);

__global__ void
computeCoulombFockSDSS(double*         mat_J,
                       const double*   s_prim_info,
                       const uint32_t  s_prim_count,
                       const double*   d_prim_info,
                       const uint32_t  d_prim_count,
                       const double*   ss_mat_D,
                       const double*   sd_mat_Q_local,
                       const double*   ss_mat_Q,
                       const uint32_t* sd_first_inds_local,
                       const uint32_t* sd_second_inds_local,
                       const uint32_t  sd_prim_pair_count_local,
                       const uint32_t* ss_first_inds,
                       const uint32_t* ss_second_inds,
                       const uint32_t  ss_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft);

__global__ void
computeCoulombFockSDSP(double*         mat_J,
                       const double*   s_prim_info,
                       const uint32_t  s_prim_count,
                       const double*   p_prim_info,
                       const uint32_t  p_prim_count,
                       const double*   d_prim_info,
                       const uint32_t  d_prim_count,
                       const double*   sp_mat_D,
                       const double*   sd_mat_Q_local,
                       const double*   sp_mat_Q,
                       const uint32_t* sd_first_inds_local,
                       const uint32_t* sd_second_inds_local,
                       const uint32_t  sd_prim_pair_count_local,
                       const uint32_t* sp_first_inds,
                       const uint32_t* sp_second_inds,
                       const uint32_t  sp_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft);

__global__ void
computeCoulombFockSDSD(double*         mat_J,
                       const double*   s_prim_info,
                       const uint32_t  s_prim_count,
                       const double*   d_prim_info,
                       const uint32_t  d_prim_count,
                       const double*   sd_mat_D,
                       const double*   sd_mat_Q_local,
                       const double*   sd_mat_Q,
                       const uint32_t* sd_first_inds_local,
                       const uint32_t* sd_second_inds_local,
                       const uint32_t  sd_prim_pair_count_local,
                       const uint32_t* sd_first_inds,
                       const uint32_t* sd_second_inds,
                       const uint32_t  sd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft);

__global__ void
computeCoulombFockSDPP(double*         mat_J,
                       const double*   s_prim_info,
                       const uint32_t  s_prim_count,
                       const double*   p_prim_info,
                       const uint32_t  p_prim_count,
                       const double*   d_prim_info,
                       const uint32_t  d_prim_count,
                       const double*   pp_mat_D,
                       const double*   sd_mat_Q_local,
                       const double*   pp_mat_Q,
                       const uint32_t* sd_first_inds_local,
                       const uint32_t* sd_second_inds_local,
                       const uint32_t  sd_prim_pair_count_local,
                       const uint32_t* pp_first_inds,
                       const uint32_t* pp_second_inds,
                       const uint32_t  pp_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft);

__global__ void
computeCoulombFockSDPD(double*         mat_J,
                       const double*   s_prim_info,
                       const uint32_t  s_prim_count,
                       const double*   p_prim_info,
                       const uint32_t  p_prim_count,
                       const double*   d_prim_info,
                       const uint32_t  d_prim_count,
                       const double*   pd_mat_D,
                       const double*   sd_mat_Q_local,
                       const double*   pd_mat_Q,
                       const uint32_t* sd_first_inds_local,
                       const uint32_t* sd_second_inds_local,
                       const uint32_t  sd_prim_pair_count_local,
                       const uint32_t* pd_first_inds,
                       const uint32_t* pd_second_inds,
                       const uint32_t  pd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft);

__global__ void
computeCoulombFockSDDD(double*         mat_J,
                       const double*   s_prim_info,
                       const uint32_t  s_prim_count,
                       const double*   d_prim_info,
                       const uint32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   sd_mat_Q_local,
                       const double*   dd_mat_Q,
                       const uint32_t* sd_first_inds_local,
                       const uint32_t* sd_second_inds_local,
                       const uint32_t  sd_prim_pair_count_local,
                       const uint32_t* dd_first_inds,
                       const uint32_t* dd_second_inds,
                       const uint32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft);

__global__ void
computeCoulombFockPDSS(double*         mat_J,
                       const double*   s_prim_info,
                       const uint32_t  s_prim_count,
                       const double*   p_prim_info,
                       const uint32_t  p_prim_count,
                       const double*   d_prim_info,
                       const uint32_t  d_prim_count,
                       const double*   ss_mat_D,
                       const double*   pd_mat_Q_local,
                       const double*   ss_mat_Q,
                       const uint32_t* pd_first_inds_local,
                       const uint32_t* pd_second_inds_local,
                       const uint32_t  pd_prim_pair_count_local,
                       const uint32_t* ss_first_inds,
                       const uint32_t* ss_second_inds,
                       const uint32_t  ss_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft);

__global__ void
computeCoulombFockPDSP(double*         mat_J,
                       const double*   s_prim_info,
                       const uint32_t  s_prim_count,
                       const double*   p_prim_info,
                       const uint32_t  p_prim_count,
                       const double*   d_prim_info,
                       const uint32_t  d_prim_count,
                       const double*   sp_mat_D,
                       const double*   pd_mat_Q_local,
                       const double*   sp_mat_Q,
                       const uint32_t* pd_first_inds_local,
                       const uint32_t* pd_second_inds_local,
                       const uint32_t  pd_prim_pair_count_local,
                       const uint32_t* sp_first_inds,
                       const uint32_t* sp_second_inds,
                       const uint32_t  sp_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft);

__global__ void
computeCoulombFockPDSD(double*         mat_J,
                       const double*   s_prim_info,
                       const uint32_t  s_prim_count,
                       const double*   p_prim_info,
                       const uint32_t  p_prim_count,
                       const double*   d_prim_info,
                       const uint32_t  d_prim_count,
                       const double*   sd_mat_D,
                       const double*   pd_mat_Q_local,
                       const double*   sd_mat_Q,
                       const uint32_t* pd_first_inds_local,
                       const uint32_t* pd_second_inds_local,
                       const uint32_t  pd_prim_pair_count_local,
                       const uint32_t* sd_first_inds,
                       const uint32_t* sd_second_inds,
                       const uint32_t  sd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft);

__global__ void
computeCoulombFockPDPP(double*         mat_J,
                       const double*   p_prim_info,
                       const uint32_t  p_prim_count,
                       const double*   d_prim_info,
                       const uint32_t  d_prim_count,
                       const double*   pp_mat_D,
                       const double*   pd_mat_Q_local,
                       const double*   pp_mat_Q,
                       const uint32_t* pd_first_inds_local,
                       const uint32_t* pd_second_inds_local,
                       const uint32_t  pd_prim_pair_count_local,
                       const uint32_t* pp_first_inds,
                       const uint32_t* pp_second_inds,
                       const uint32_t  pp_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft);

__global__ void
computeCoulombFockPDPD(double*         mat_J,
                       const double*   p_prim_info,
                       const uint32_t  p_prim_count,
                       const double*   d_prim_info,
                       const uint32_t  d_prim_count,
                       const double*   pd_mat_D,
                       const double*   pd_mat_Q_local,
                       const double*   pd_mat_Q,
                       const uint32_t* pd_first_inds_local,
                       const uint32_t* pd_second_inds_local,
                       const uint32_t  pd_prim_pair_count_local,
                       const uint32_t* pd_first_inds,
                       const uint32_t* pd_second_inds,
                       const uint32_t  pd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft);

__global__ void
computeCoulombFockPDDD(double*         mat_J,
                       const double*   p_prim_info,
                       const uint32_t  p_prim_count,
                       const double*   d_prim_info,
                       const uint32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   pd_mat_Q_local,
                       const double*   dd_mat_Q,
                       const uint32_t* pd_first_inds_local,
                       const uint32_t* pd_second_inds_local,
                       const uint32_t  pd_prim_pair_count_local,
                       const uint32_t* dd_first_inds,
                       const uint32_t* dd_second_inds,
                       const uint32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft);

__global__ void
computeCoulombFockDDSS(double*         mat_J,
                       const double*   s_prim_info,
                       const uint32_t  s_prim_count,
                       const double*   d_prim_info,
                       const uint32_t  d_prim_count,
                       const double*   ss_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   ss_mat_Q,
                       const uint32_t* dd_first_inds_local,
                       const uint32_t* dd_second_inds_local,
                       const uint32_t  dd_prim_pair_count_local,
                       const uint32_t* ss_first_inds,
                       const uint32_t* ss_second_inds,
                       const uint32_t  ss_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft);

__global__ void
computeCoulombFockDDSP(double*         mat_J,
                       const double*   s_prim_info,
                       const uint32_t  s_prim_count,
                       const double*   p_prim_info,
                       const uint32_t  p_prim_count,
                       const double*   d_prim_info,
                       const uint32_t  d_prim_count,
                       const double*   sp_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   sp_mat_Q,
                       const uint32_t* dd_first_inds_local,
                       const uint32_t* dd_second_inds_local,
                       const uint32_t  dd_prim_pair_count_local,
                       const uint32_t* sp_first_inds,
                       const uint32_t* sp_second_inds,
                       const uint32_t  sp_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft);

__global__ void
computeCoulombFockDDSD(double*         mat_J,
                       const double*   s_prim_info,
                       const uint32_t  s_prim_count,
                       const double*   d_prim_info,
                       const uint32_t  d_prim_count,
                       const double*   sd_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   sd_mat_Q,
                       const uint32_t* dd_first_inds_local,
                       const uint32_t* dd_second_inds_local,
                       const uint32_t  dd_prim_pair_count_local,
                       const uint32_t* sd_first_inds,
                       const uint32_t* sd_second_inds,
                       const uint32_t  sd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft);

__global__ void
computeCoulombFockDDPP(double*         mat_J,
                       const double*   p_prim_info,
                       const uint32_t  p_prim_count,
                       const double*   d_prim_info,
                       const uint32_t  d_prim_count,
                       const double*   pp_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   pp_mat_Q,
                       const uint32_t* dd_first_inds_local,
                       const uint32_t* dd_second_inds_local,
                       const uint32_t  dd_prim_pair_count_local,
                       const uint32_t* pp_first_inds,
                       const uint32_t* pp_second_inds,
                       const uint32_t  pp_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft);

__global__ void
computeCoulombFockDDPD(double*         mat_J,
                       const double*   p_prim_info,
                       const uint32_t  p_prim_count,
                       const double*   d_prim_info,
                       const uint32_t  d_prim_count,
                       const double*   pd_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   pd_mat_Q,
                       const uint32_t* dd_first_inds_local,
                       const uint32_t* dd_second_inds_local,
                       const uint32_t  dd_prim_pair_count_local,
                       const uint32_t* pd_first_inds,
                       const uint32_t* pd_second_inds,
                       const uint32_t  pd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft);

__global__ void
computeCoulombFockDDDD(double*         mat_J,
                       const double*   d_prim_info,
                       const uint32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   dd_mat_Q,
                       const uint32_t* dd_first_inds_local,
                       const uint32_t* dd_second_inds_local,
                       const uint32_t  dd_prim_pair_count_local,
                       const uint32_t* dd_first_inds,
                       const uint32_t* dd_second_inds,
                       const uint32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft);

__global__ void computeExchangeFockSSSS(double*         mat_K,
                                        const uint32_t* pair_inds_i_for_K_ss,
                                        const uint32_t* pair_inds_k_for_K_ss,
                                        const uint32_t  pair_inds_count_for_K_ss,
                                        const double*   s_prim_info,
                                        const uint32_t* s_prim_aoinds,
                                        const uint32_t  s_prim_count,
                                        const double    max_D,
                                        const double*   mat_D_full,
                                        const double*   mat_Q_for_K,
                                        const uint32_t* density_inds_for_K,
                                        const uint32_t  naos,
                                        const double*   boys_func_table,
                                        const double*   boys_func_ft);

__global__ void computeExchangeFockSSSP(double*         mat_K,
                                        const uint32_t* pair_inds_i_for_K_ss,
                                        const uint32_t* pair_inds_k_for_K_ss,
                                        const uint32_t  pair_inds_count_for_K_ss,
                                        const double*   s_prim_info,
                                        const uint32_t* s_prim_aoinds,
                                        const uint32_t  s_prim_count,
                                        const double*   p_prim_info,
                                        const uint32_t* p_prim_aoinds,
                                        const uint32_t  p_prim_count,
                                        const double    max_D,
                                        const double*   mat_D_full_AO,
                                        const double*   mat_Q_for_K_ss,
                                        const double*   mat_Q_for_K_sp,
                                        const uint32_t* density_inds_for_K_ss,
                                        const uint32_t* density_inds_for_K_sp,
                                        const uint32_t  naos,
                                        const double*   boys_func_table,
                                        const double*   boys_func_ft);

__global__ void computeExchangeFockSPSS(double*         mat_K,
                                        const uint32_t* pair_inds_i_for_K_ss,
                                        const uint32_t* pair_inds_k_for_K_ss,
                                        const uint32_t  pair_inds_count_for_K_ss,
                                        const double*   s_prim_info,
                                        const uint32_t* s_prim_aoinds,
                                        const uint32_t  s_prim_count,
                                        const double*   p_prim_info,
                                        const uint32_t* p_prim_aoinds,
                                        const uint32_t  p_prim_count,
                                        const double    max_D,
                                        const double*   mat_D_full_AO,
                                        const double*   mat_Q_for_K_ss,
                                        const double*   mat_Q_for_K_sp,
                                        const uint32_t* density_inds_for_K_ss,
                                        const uint32_t* density_inds_for_K_sp,
                                        const uint32_t  naos,
                                        const double*   boys_func_table,
                                        const double*   boys_func_ft);

__global__ void computeExchangeFockSPSP(double*         mat_K,
                                        const uint32_t* pair_inds_i_for_K_ss,
                                        const uint32_t* pair_inds_k_for_K_ss,
                                        const uint32_t  pair_inds_count_for_K_ss,
                                        const double*   s_prim_info,
                                        const uint32_t* s_prim_aoinds,
                                        const uint32_t  s_prim_count,
                                        const double*   p_prim_info,
                                        const uint32_t* p_prim_aoinds,
                                        const uint32_t  p_prim_count,
                                        const double    max_D,
                                        const double*   mat_D_full_AO,
                                        const double*   mat_Q_for_K_sp,
                                        const uint32_t* density_inds_for_K_sp,
                                        const uint32_t  naos,
                                        const double*   boys_func_table,
                                        const double*   boys_func_ft);

__global__ void computeExchangeFockSSPS(double*         mat_K,
                                        const uint32_t* pair_inds_i_for_K_sp,
                                        const uint32_t* pair_inds_k_for_K_sp,
                                        const uint32_t  pair_inds_count_for_K_sp,
                                        const double*   s_prim_info,
                                        const uint32_t* s_prim_aoinds,
                                        const uint32_t  s_prim_count,
                                        const double*   p_prim_info,
                                        const uint32_t* p_prim_aoinds,
                                        const uint32_t  p_prim_count,
                                        const double    max_D,
                                        const double*   mat_D_full_AO,
                                        const double*   mat_Q_for_K_ss,
                                        const double*   mat_Q_for_K_ps,
                                        const uint32_t* density_inds_for_K_ss,
                                        const uint32_t* density_inds_for_K_ps,
                                        const uint32_t  naos,
                                        const double*   boys_func_table,
                                        const double*   boys_func_ft);

__global__ void computeExchangeFockSSPP(double*         mat_K,
                                        const uint32_t* pair_inds_i_for_K_sp,
                                        const uint32_t* pair_inds_k_for_K_sp,
                                        const uint32_t  pair_inds_count_for_K_sp,
                                        const double*   s_prim_info,
                                        const uint32_t* s_prim_aoinds,
                                        const uint32_t  s_prim_count,
                                        const double*   p_prim_info,
                                        const uint32_t* p_prim_aoinds,
                                        const uint32_t  p_prim_count,
                                        const double    max_D,
                                        const double*   mat_D_full_AO,
                                        const double*   mat_Q_for_K_ss,
                                        const double*   mat_Q_for_K_pp,
                                        const uint32_t* density_inds_for_K_ss,
                                        const uint32_t* density_inds_for_K_pp,
                                        const uint32_t  naos,
                                        const double*   boys_func_table,
                                        const double*   boys_func_ft);

__global__ void computeExchangeFockSPPS(double*         mat_K,
                                        const uint32_t* pair_inds_i_for_K_sp,
                                        const uint32_t* pair_inds_k_for_K_sp,
                                        const uint32_t  pair_inds_count_for_K_sp,
                                        const double*   s_prim_info,
                                        const uint32_t* s_prim_aoinds,
                                        const uint32_t  s_prim_count,
                                        const double*   p_prim_info,
                                        const uint32_t* p_prim_aoinds,
                                        const uint32_t  p_prim_count,
                                        const double    max_D,
                                        const double*   mat_D_full_AO,
                                        const double*   mat_Q_for_K_sp,
                                        const double*   mat_Q_for_K_ps,
                                        const uint32_t* density_inds_for_K_sp,
                                        const uint32_t* density_inds_for_K_ps,
                                        const uint32_t  naos,
                                        const double*   boys_func_table,
                                        const double*   boys_func_ft);

__global__ void computeExchangeFockSPPP(double*         mat_K,
                                        const uint32_t* pair_inds_i_for_K_sp,
                                        const uint32_t* pair_inds_k_for_K_sp,
                                        const uint32_t  pair_inds_count_for_K_sp,
                                        const double*   s_prim_info,
                                        const uint32_t* s_prim_aoinds,
                                        const uint32_t  s_prim_count,
                                        const double*   p_prim_info,
                                        const uint32_t* p_prim_aoinds,
                                        const uint32_t  p_prim_count,
                                        const double    max_D,
                                        const double*   mat_D_full_AO,
                                        const double*   mat_Q_for_K_sp,
                                        const double*   mat_Q_for_K_pp,
                                        const uint32_t* density_inds_for_K_sp,
                                        const uint32_t* density_inds_for_K_pp,
                                        const uint32_t  naos,
                                        const double*   boys_func_table,
                                        const double*   boys_func_ft);

__global__ void computeExchangeFockPSPS(double*         mat_K,
                                        const uint32_t* pair_inds_i_for_K_pp,
                                        const uint32_t* pair_inds_k_for_K_pp,
                                        const uint32_t  pair_inds_count_for_K_pp,
                                        const double*   s_prim_info,
                                        const uint32_t* s_prim_aoinds,
                                        const uint32_t  s_prim_count,
                                        const double*   p_prim_info,
                                        const uint32_t* p_prim_aoinds,
                                        const uint32_t  p_prim_count,
                                        const double    max_D,
                                        const double*   mat_D_full_AO,
                                        const double*   mat_Q_for_K_ps,
                                        const uint32_t* density_inds_for_K_ps,
                                        const uint32_t  naos,
                                        const double*   boys_func_table,
                                        const double*   boys_func_ft);

__global__ void computeExchangeFockPSPP(double*         mat_K,
                                        const uint32_t* pair_inds_i_for_K_pp,
                                        const uint32_t* pair_inds_k_for_K_pp,
                                        const uint32_t  pair_inds_count_for_K_pp,
                                        const double*   s_prim_info,
                                        const uint32_t* s_prim_aoinds,
                                        const uint32_t  s_prim_count,
                                        const double*   p_prim_info,
                                        const uint32_t* p_prim_aoinds,
                                        const uint32_t  p_prim_count,
                                        const double    max_D,
                                        const double*   mat_D_full_AO,
                                        const double*   mat_Q_for_K_ps,
                                        const double*   mat_Q_for_K_pp,
                                        const uint32_t* density_inds_for_K_ps,
                                        const uint32_t* density_inds_for_K_pp,
                                        const uint32_t  naos,
                                        const double*   boys_func_table,
                                        const double*   boys_func_ft);

__global__ void computeExchangeFockPPPS(double*         mat_K,
                                        const uint32_t* pair_inds_i_for_K_pp,
                                        const uint32_t* pair_inds_k_for_K_pp,
                                        const uint32_t  pair_inds_count_for_K_pp,
                                        const double*   s_prim_info,
                                        const uint32_t* s_prim_aoinds,
                                        const uint32_t  s_prim_count,
                                        const double*   p_prim_info,
                                        const uint32_t* p_prim_aoinds,
                                        const uint32_t  p_prim_count,
                                        const double    max_D,
                                        const double*   mat_D_full_AO,
                                        const double*   mat_Q_for_K_ps,
                                        const double*   mat_Q_for_K_pp,
                                        const uint32_t* density_inds_for_K_ps,
                                        const uint32_t* density_inds_for_K_pp,
                                        const uint32_t  naos,
                                        const double*   boys_func_table,
                                        const double*   boys_func_ft);

__global__ void computeExchangeFockPPPP(double*         mat_K,
                                        const uint32_t* pair_inds_i_for_K_pp,
                                        const uint32_t* pair_inds_k_for_K_pp,
                                        const uint32_t  pair_inds_count_for_K_pp,
                                        const double*   p_prim_info,
                                        const uint32_t* p_prim_aoinds,
                                        const uint32_t  p_prim_count,
                                        const double    max_D,
                                        const double*   mat_D_full_AO,
                                        const double*   mat_Q_for_K_pp,
                                        const uint32_t* density_inds_for_K_pp,
                                        const uint32_t  naos,
                                        const double*   boys_func_table,
                                        const double*   boys_func_ft);

__global__ void matmulAB(double* C, double* A, double* B, uint32_t nrows_A, uint32_t ncols_A, uint32_t ncols_B);

}  // namespace gpu

#endif
