//
//                                   VELOXCHEM
//              ----------------------------------------------------
//                          An Electronic Structure Code
//
//  SPDX-License-Identifier: BSD-3-Clause
//
//  Copyright 2018-2025 VeloxChem developers
//
//  Redistribution and use in source and binary forms, with or without modification,
//  are permitted provided that the following conditions are met:
//
//  1. Redistributions of source code must retain the above copyright notice, this
//     list of conditions and the following disclaimer.
//  2. Redistributions in binary form must reproduce the above copyright notice,
//     this list of conditions and the following disclaimer in the documentation
//     and/or other materials provided with the distribution.
//  3. Neither the name of the copyright holder nor the names of its contributors
//     may be used to endorse or promote products derived from this software without
//     specific prior written permission.
//
//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
//  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
//  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
//  DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
//  FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
//  DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
//  SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
//  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
//  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
//  OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef EriCoulomb_hpp
#define EriCoulomb_hpp

#include <cstdint>

#include "GpuConstants.hpp"

namespace gpu {  // gpu namespace

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockSSSS(double*         mat_J,
                       const double*   s_prim_info,
                       const int32_t  s_prim_count,
                       const double*   ss_mat_D,
                       const double*   ss_mat_Q_local,
                       const double*   ss_mat_Q,
                       const int32_t* ss_first_inds_local,
                       const int32_t* ss_second_inds_local,
                       const double*   ss_pair_data_local,
                       const int32_t  ss_prim_pair_count_local,
                       const int32_t* ss_first_inds,
                       const int32_t* ss_second_inds,
                       const double*   ss_pair_data,
                       const int32_t  ss_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockSSSP(double*         mat_J,
                       const double*   s_prim_info,
                       const int32_t  s_prim_count,
                       const double*   p_prim_info,
                       const int32_t  p_prim_count,
                       const double*   sp_mat_D,
                       const double*   ss_mat_Q_local,
                       const double*   sp_mat_Q,
                       const int32_t* ss_first_inds_local,
                       const int32_t* ss_second_inds_local,
                       const double*   ss_pair_data_local,
                       const int32_t  ss_prim_pair_count_local,
                       const int32_t* sp_first_inds,
                       const int32_t* sp_second_inds,
                       const double*   sp_pair_data,
                       const int32_t  sp_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockSSSD(double*         mat_J,
                       const double*   s_prim_info,
                       const int32_t  s_prim_count,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   sd_mat_D,
                       const double*   ss_mat_Q_local,
                       const double*   sd_mat_Q,
                       const int32_t* ss_first_inds_local,
                       const int32_t* ss_second_inds_local,
                       const double*   ss_pair_data_local,
                       const int32_t  ss_prim_pair_count_local,
                       const int32_t* sd_first_inds,
                       const int32_t* sd_second_inds,
                       const double*   sd_pair_data,
                       const int32_t  sd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockSSPP(double*         mat_J,
                       const double*   s_prim_info,
                       const int32_t  s_prim_count,
                       const double*   p_prim_info,
                       const int32_t  p_prim_count,
                       const double*   pp_mat_D,
                       const double*   ss_mat_Q_local,
                       const double*   pp_mat_Q,
                       const int32_t* ss_first_inds_local,
                       const int32_t* ss_second_inds_local,
                       const double*   ss_pair_data_local,
                       const int32_t  ss_prim_pair_count_local,
                       const int32_t* pp_first_inds,
                       const int32_t* pp_second_inds,
                       const double*   pp_pair_data,
                       const int32_t  pp_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockSSPD(double*         mat_J,
                       const double*   s_prim_info,
                       const int32_t  s_prim_count,
                       const double*   p_prim_info,
                       const int32_t  p_prim_count,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   pd_mat_D,
                       const double*   ss_mat_Q_local,
                       const double*   pd_mat_Q,
                       const int32_t* ss_first_inds_local,
                       const int32_t* ss_second_inds_local,
                       const double*   ss_pair_data_local,
                       const int32_t  ss_prim_pair_count_local,
                       const int32_t* pd_first_inds,
                       const int32_t* pd_second_inds,
                       const double*   pd_pair_data,
                       const int32_t  pd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockSSDD(double*         mat_J,
                       const double*   s_prim_info,
                       const int32_t  s_prim_count,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   ss_mat_Q_local,
                       const double*   dd_mat_Q,
                       const int32_t* ss_first_inds_local,
                       const int32_t* ss_second_inds_local,
                       const double*   ss_pair_data_local,
                       const int32_t  ss_prim_pair_count_local,
                       const int32_t* dd_first_inds,
                       const int32_t* dd_second_inds,
                       const double*   dd_pair_data,
                       const int32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockSPSS(double*         mat_J,
                       const double*   s_prim_info,
                       const int32_t  s_prim_count,
                       const double*   p_prim_info,
                       const int32_t  p_prim_count,
                       const double*   ss_mat_D,
                       const double*   sp_mat_Q_local,
                       const double*   ss_mat_Q,
                       const int32_t* sp_first_inds_local,
                       const int32_t* sp_second_inds_local,
                       const double*   sp_pair_data_local,
                       const int32_t  sp_prim_pair_count_local,
                       const int32_t* ss_first_inds,
                       const int32_t* ss_second_inds,
                       const double*   ss_pair_data,
                       const int32_t  ss_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockSPSP(double*         mat_J,
                       const double*   s_prim_info,
                       const int32_t  s_prim_count,
                       const double*   p_prim_info,
                       const int32_t  p_prim_count,
                       const double*   sp_mat_D,
                       const double*   sp_mat_Q_local,
                       const double*   sp_mat_Q,
                       const int32_t* sp_first_inds_local,
                       const int32_t* sp_second_inds_local,
                       const double*   sp_pair_data_local,
                       const int32_t  sp_prim_pair_count_local,
                       const int32_t* sp_first_inds,
                       const int32_t* sp_second_inds,
                       const double*   sp_pair_data,
                       const int32_t  sp_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockSPSD(double*         mat_J,
                       const double*   s_prim_info,
                       const int32_t  s_prim_count,
                       const double*   p_prim_info,
                       const int32_t  p_prim_count,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   sd_mat_D,
                       const double*   sp_mat_Q_local,
                       const double*   sd_mat_Q,
                       const int32_t* sp_first_inds_local,
                       const int32_t* sp_second_inds_local,
                       const double*   sp_pair_data_local,
                       const int32_t  sp_prim_pair_count_local,
                       const int32_t* sd_first_inds,
                       const int32_t* sd_second_inds,
                       const double*   sd_pair_data,
                       const int32_t  sd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockSPPP(double*         mat_J,
                       const double*   s_prim_info,
                       const int32_t  s_prim_count,
                       const double*   p_prim_info,
                       const int32_t  p_prim_count,
                       const double*   pp_mat_D,
                       const double*   sp_mat_Q_local,
                       const double*   pp_mat_Q,
                       const int32_t* sp_first_inds_local,
                       const int32_t* sp_second_inds_local,
                       const double*   sp_pair_data_local,
                       const int32_t  sp_prim_pair_count_local,
                       const int32_t* pp_first_inds,
                       const int32_t* pp_second_inds,
                       const double*   pp_pair_data,
                       const int32_t  pp_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockSPPD(double*         mat_J,
                       const double*   s_prim_info,
                       const int32_t  s_prim_count,
                       const double*   p_prim_info,
                       const int32_t  p_prim_count,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   pd_mat_D,
                       const double*   sp_mat_Q_local,
                       const double*   pd_mat_Q,
                       const int32_t* sp_first_inds_local,
                       const int32_t* sp_second_inds_local,
                       const double*   sp_pair_data_local,
                       const int32_t  sp_prim_pair_count_local,
                       const int32_t* pd_first_inds,
                       const int32_t* pd_second_inds,
                       const double*   pd_pair_data,
                       const int32_t  pd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockPPSS(double*         mat_J,
                       const double*   s_prim_info,
                       const int32_t  s_prim_count,
                       const double*   p_prim_info,
                       const int32_t  p_prim_count,
                       const double*   ss_mat_D,
                       const double*   pp_mat_Q_local,
                       const double*   ss_mat_Q,
                       const int32_t* pp_first_inds_local,
                       const int32_t* pp_second_inds_local,
                       const double*   pp_pair_data_local,
                       const int32_t  pp_prim_pair_count_local,
                       const int32_t* ss_first_inds,
                       const int32_t* ss_second_inds,
                       const double*   ss_pair_data,
                       const int32_t  ss_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockPPSP(double*         mat_J,
                       const double*   s_prim_info,
                       const int32_t  s_prim_count,
                       const double*   p_prim_info,
                       const int32_t  p_prim_count,
                       const double*   sp_mat_D,
                       const double*   pp_mat_Q_local,
                       const double*   sp_mat_Q,
                       const int32_t* pp_first_inds_local,
                       const int32_t* pp_second_inds_local,
                       const double*   pp_pair_data_local,
                       const int32_t  pp_prim_pair_count_local,
                       const int32_t* sp_first_inds,
                       const int32_t* sp_second_inds,
                       const double*   sp_pair_data,
                       const int32_t  sp_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockSDSS(double*         mat_J,
                       const double*   s_prim_info,
                       const int32_t  s_prim_count,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   ss_mat_D,
                       const double*   sd_mat_Q_local,
                       const double*   ss_mat_Q,
                       const int32_t* sd_first_inds_local,
                       const int32_t* sd_second_inds_local,
                       const double*   sd_pair_data_local,
                       const int32_t  sd_prim_pair_count_local,
                       const int32_t* ss_first_inds,
                       const int32_t* ss_second_inds,
                       const double*   ss_pair_data,
                       const int32_t  ss_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockSDSP(double*         mat_J,
                       const double*   s_prim_info,
                       const int32_t  s_prim_count,
                       const double*   p_prim_info,
                       const int32_t  p_prim_count,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   sp_mat_D,
                       const double*   sd_mat_Q_local,
                       const double*   sp_mat_Q,
                       const int32_t* sd_first_inds_local,
                       const int32_t* sd_second_inds_local,
                       const double*   sd_pair_data_local,
                       const int32_t  sd_prim_pair_count_local,
                       const int32_t* sp_first_inds,
                       const int32_t* sp_second_inds,
                       const double*   sp_pair_data,
                       const int32_t  sp_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockPDSS(double*         mat_J,
                       const double*   s_prim_info,
                       const int32_t  s_prim_count,
                       const double*   p_prim_info,
                       const int32_t  p_prim_count,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   ss_mat_D,
                       const double*   pd_mat_Q_local,
                       const double*   ss_mat_Q,
                       const int32_t* pd_first_inds_local,
                       const int32_t* pd_second_inds_local,
                       const double*   pd_pair_data_local,
                       const int32_t  pd_prim_pair_count_local,
                       const int32_t* ss_first_inds,
                       const int32_t* ss_second_inds,
                       const double*   ss_pair_data,
                       const int32_t  ss_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockPDSP(double*         mat_J,
                       const double*   s_prim_info,
                       const int32_t  s_prim_count,
                       const double*   p_prim_info,
                       const int32_t  p_prim_count,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   sp_mat_D,
                       const double*   pd_mat_Q_local,
                       const double*   sp_mat_Q,
                       const int32_t* pd_first_inds_local,
                       const int32_t* pd_second_inds_local,
                       const double*   pd_pair_data_local,
                       const int32_t  pd_prim_pair_count_local,
                       const int32_t* sp_first_inds,
                       const int32_t* sp_second_inds,
                       const double*   sp_pair_data,
                       const int32_t  sp_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockDDSS(double*         mat_J,
                       const double*   s_prim_info,
                       const int32_t  s_prim_count,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   ss_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   ss_mat_Q,
                       const int32_t* dd_first_inds_local,
                       const int32_t* dd_second_inds_local,
                       const double*   dd_pair_data_local,
                       const int32_t  dd_prim_pair_count_local,
                       const int32_t* ss_first_inds,
                       const int32_t* ss_second_inds,
                       const double*   ss_pair_data,
                       const int32_t  ss_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);


__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockDDPD0(double*         mat_J,
                       const double*   p_prim_info,
                       const int32_t  p_prim_count,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   pd_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   pd_mat_Q,
                       const int32_t* dd_first_inds_local,
                       const int32_t* dd_second_inds_local,
                       const double*   dd_pair_data_local,
                       const int32_t  dd_prim_pair_count_local,
                       const int32_t* pd_first_inds,
                       const int32_t* pd_second_inds,
                       const double*   pd_pair_data,
                       const int32_t  pd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockDDPD1(double*         mat_J,
                       const double*   p_prim_info,
                       const int32_t  p_prim_count,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   pd_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   pd_mat_Q,
                       const int32_t* dd_first_inds_local,
                       const int32_t* dd_second_inds_local,
                       const double*   dd_pair_data_local,
                       const int32_t  dd_prim_pair_count_local,
                       const int32_t* pd_first_inds,
                       const int32_t* pd_second_inds,
                       const double*   pd_pair_data,
                       const int32_t  pd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockDDPD2(double*         mat_J,
                       const double*   p_prim_info,
                       const int32_t  p_prim_count,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   pd_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   pd_mat_Q,
                       const int32_t* dd_first_inds_local,
                       const int32_t* dd_second_inds_local,
                       const double*   dd_pair_data_local,
                       const int32_t  dd_prim_pair_count_local,
                       const int32_t* pd_first_inds,
                       const int32_t* pd_second_inds,
                       const double*   pd_pair_data,
                       const int32_t  pd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockDDPD3(double*         mat_J,
                       const double*   p_prim_info,
                       const int32_t  p_prim_count,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   pd_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   pd_mat_Q,
                       const int32_t* dd_first_inds_local,
                       const int32_t* dd_second_inds_local,
                       const double*   dd_pair_data_local,
                       const int32_t  dd_prim_pair_count_local,
                       const int32_t* pd_first_inds,
                       const int32_t* pd_second_inds,
                       const double*   pd_pair_data,
                       const int32_t  pd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockDDPD4(double*         mat_J,
                       const double*   p_prim_info,
                       const int32_t  p_prim_count,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   pd_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   pd_mat_Q,
                       const int32_t* dd_first_inds_local,
                       const int32_t* dd_second_inds_local,
                       const double*   dd_pair_data_local,
                       const int32_t  dd_prim_pair_count_local,
                       const int32_t* pd_first_inds,
                       const int32_t* pd_second_inds,
                       const double*   pd_pair_data,
                       const int32_t  pd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockDDPD5(double*         mat_J,
                       const double*   p_prim_info,
                       const int32_t  p_prim_count,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   pd_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   pd_mat_Q,
                       const int32_t* dd_first_inds_local,
                       const int32_t* dd_second_inds_local,
                       const double*   dd_pair_data_local,
                       const int32_t  dd_prim_pair_count_local,
                       const int32_t* pd_first_inds,
                       const int32_t* pd_second_inds,
                       const double*   pd_pair_data,
                       const int32_t  pd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockDDPD6(double*         mat_J,
                       const double*   p_prim_info,
                       const int32_t  p_prim_count,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   pd_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   pd_mat_Q,
                       const int32_t* dd_first_inds_local,
                       const int32_t* dd_second_inds_local,
                       const double*   dd_pair_data_local,
                       const int32_t  dd_prim_pair_count_local,
                       const int32_t* pd_first_inds,
                       const int32_t* pd_second_inds,
                       const double*   pd_pair_data,
                       const int32_t  pd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockDDPD7(double*         mat_J,
                       const double*   p_prim_info,
                       const int32_t  p_prim_count,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   pd_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   pd_mat_Q,
                       const int32_t* dd_first_inds_local,
                       const int32_t* dd_second_inds_local,
                       const double*   dd_pair_data_local,
                       const int32_t  dd_prim_pair_count_local,
                       const int32_t* pd_first_inds,
                       const int32_t* pd_second_inds,
                       const double*   pd_pair_data,
                       const int32_t  pd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockDDPD8(double*         mat_J,
                       const double*   p_prim_info,
                       const int32_t  p_prim_count,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   pd_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   pd_mat_Q,
                       const int32_t* dd_first_inds_local,
                       const int32_t* dd_second_inds_local,
                       const double*   dd_pair_data_local,
                       const int32_t  dd_prim_pair_count_local,
                       const int32_t* pd_first_inds,
                       const int32_t* pd_second_inds,
                       const double*   pd_pair_data,
                       const int32_t  pd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockDDPD9(double*         mat_J,
                       const double*   p_prim_info,
                       const int32_t  p_prim_count,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   pd_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   pd_mat_Q,
                       const int32_t* dd_first_inds_local,
                       const int32_t* dd_second_inds_local,
                       const double*   dd_pair_data_local,
                       const int32_t  dd_prim_pair_count_local,
                       const int32_t* pd_first_inds,
                       const int32_t* pd_second_inds,
                       const double*   pd_pair_data,
                       const int32_t  pd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);


__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockDDDD0(double*         mat_J,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   dd_mat_Q,
                       const int32_t* dd_first_inds_local,
                       const int32_t* dd_second_inds_local,
                       const double*   dd_pair_data_local,
                       const int32_t  dd_prim_pair_count_local,
                       const int32_t* dd_first_inds,
                       const int32_t* dd_second_inds,
                       const double*   dd_pair_data,
                       const int32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockDDDD1(double*         mat_J,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   dd_mat_Q,
                       const int32_t* dd_first_inds_local,
                       const int32_t* dd_second_inds_local,
                       const double*   dd_pair_data_local,
                       const int32_t  dd_prim_pair_count_local,
                       const int32_t* dd_first_inds,
                       const int32_t* dd_second_inds,
                       const double*   dd_pair_data,
                       const int32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockDDDD2(double*         mat_J,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   dd_mat_Q,
                       const int32_t* dd_first_inds_local,
                       const int32_t* dd_second_inds_local,
                       const double*   dd_pair_data_local,
                       const int32_t  dd_prim_pair_count_local,
                       const int32_t* dd_first_inds,
                       const int32_t* dd_second_inds,
                       const double*   dd_pair_data,
                       const int32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockDDDD3(double*         mat_J,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   dd_mat_Q,
                       const int32_t* dd_first_inds_local,
                       const int32_t* dd_second_inds_local,
                       const double*   dd_pair_data_local,
                       const int32_t  dd_prim_pair_count_local,
                       const int32_t* dd_first_inds,
                       const int32_t* dd_second_inds,
                       const double*   dd_pair_data,
                       const int32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockDDDD4(double*         mat_J,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   dd_mat_Q,
                       const int32_t* dd_first_inds_local,
                       const int32_t* dd_second_inds_local,
                       const double*   dd_pair_data_local,
                       const int32_t  dd_prim_pair_count_local,
                       const int32_t* dd_first_inds,
                       const int32_t* dd_second_inds,
                       const double*   dd_pair_data,
                       const int32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockDDDD5(double*         mat_J,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   dd_mat_Q,
                       const int32_t* dd_first_inds_local,
                       const int32_t* dd_second_inds_local,
                       const double*   dd_pair_data_local,
                       const int32_t  dd_prim_pair_count_local,
                       const int32_t* dd_first_inds,
                       const int32_t* dd_second_inds,
                       const double*   dd_pair_data,
                       const int32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockDDDD6(double*         mat_J,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   dd_mat_Q,
                       const int32_t* dd_first_inds_local,
                       const int32_t* dd_second_inds_local,
                       const double*   dd_pair_data_local,
                       const int32_t  dd_prim_pair_count_local,
                       const int32_t* dd_first_inds,
                       const int32_t* dd_second_inds,
                       const double*   dd_pair_data,
                       const int32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockDDDD7(double*         mat_J,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   dd_mat_Q,
                       const int32_t* dd_first_inds_local,
                       const int32_t* dd_second_inds_local,
                       const double*   dd_pair_data_local,
                       const int32_t  dd_prim_pair_count_local,
                       const int32_t* dd_first_inds,
                       const int32_t* dd_second_inds,
                       const double*   dd_pair_data,
                       const int32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockDDDD8(double*         mat_J,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   dd_mat_Q,
                       const int32_t* dd_first_inds_local,
                       const int32_t* dd_second_inds_local,
                       const double*   dd_pair_data_local,
                       const int32_t  dd_prim_pair_count_local,
                       const int32_t* dd_first_inds,
                       const int32_t* dd_second_inds,
                       const double*   dd_pair_data,
                       const int32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockDDDD9(double*         mat_J,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   dd_mat_Q,
                       const int32_t* dd_first_inds_local,
                       const int32_t* dd_second_inds_local,
                       const double*   dd_pair_data_local,
                       const int32_t  dd_prim_pair_count_local,
                       const int32_t* dd_first_inds,
                       const int32_t* dd_second_inds,
                       const double*   dd_pair_data,
                       const int32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockDDDD10(double*         mat_J,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   dd_mat_Q,
                       const int32_t* dd_first_inds_local,
                       const int32_t* dd_second_inds_local,
                       const double*   dd_pair_data_local,
                       const int32_t  dd_prim_pair_count_local,
                       const int32_t* dd_first_inds,
                       const int32_t* dd_second_inds,
                       const double*   dd_pair_data,
                       const int32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockDDDD11(double*         mat_J,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   dd_mat_Q,
                       const int32_t* dd_first_inds_local,
                       const int32_t* dd_second_inds_local,
                       const double*   dd_pair_data_local,
                       const int32_t  dd_prim_pair_count_local,
                       const int32_t* dd_first_inds,
                       const int32_t* dd_second_inds,
                       const double*   dd_pair_data,
                       const int32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockDDDD12(double*         mat_J,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   dd_mat_Q,
                       const int32_t* dd_first_inds_local,
                       const int32_t* dd_second_inds_local,
                       const double*   dd_pair_data_local,
                       const int32_t  dd_prim_pair_count_local,
                       const int32_t* dd_first_inds,
                       const int32_t* dd_second_inds,
                       const double*   dd_pair_data,
                       const int32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockDDDD13(double*         mat_J,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   dd_mat_Q,
                       const int32_t* dd_first_inds_local,
                       const int32_t* dd_second_inds_local,
                       const double*   dd_pair_data_local,
                       const int32_t  dd_prim_pair_count_local,
                       const int32_t* dd_first_inds,
                       const int32_t* dd_second_inds,
                       const double*   dd_pair_data,
                       const int32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockDDDD14(double*         mat_J,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   dd_mat_Q,
                       const int32_t* dd_first_inds_local,
                       const int32_t* dd_second_inds_local,
                       const double*   dd_pair_data_local,
                       const int32_t  dd_prim_pair_count_local,
                       const int32_t* dd_first_inds,
                       const int32_t* dd_second_inds,
                       const double*   dd_pair_data,
                       const int32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockDDDD15(double*         mat_J,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   dd_mat_Q,
                       const int32_t* dd_first_inds_local,
                       const int32_t* dd_second_inds_local,
                       const double*   dd_pair_data_local,
                       const int32_t  dd_prim_pair_count_local,
                       const int32_t* dd_first_inds,
                       const int32_t* dd_second_inds,
                       const double*   dd_pair_data,
                       const int32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockDDDD16(double*         mat_J,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   dd_mat_Q,
                       const int32_t* dd_first_inds_local,
                       const int32_t* dd_second_inds_local,
                       const double*   dd_pair_data_local,
                       const int32_t  dd_prim_pair_count_local,
                       const int32_t* dd_first_inds,
                       const int32_t* dd_second_inds,
                       const double*   dd_pair_data,
                       const int32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockDDDD17(double*         mat_J,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   dd_mat_Q,
                       const int32_t* dd_first_inds_local,
                       const int32_t* dd_second_inds_local,
                       const double*   dd_pair_data_local,
                       const int32_t  dd_prim_pair_count_local,
                       const int32_t* dd_first_inds,
                       const int32_t* dd_second_inds,
                       const double*   dd_pair_data,
                       const int32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockDDDD18(double*         mat_J,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   dd_mat_Q,
                       const int32_t* dd_first_inds_local,
                       const int32_t* dd_second_inds_local,
                       const double*   dd_pair_data_local,
                       const int32_t  dd_prim_pair_count_local,
                       const int32_t* dd_first_inds,
                       const int32_t* dd_second_inds,
                       const double*   dd_pair_data,
                       const int32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockDDDD19(double*         mat_J,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   dd_mat_Q,
                       const int32_t* dd_first_inds_local,
                       const int32_t* dd_second_inds_local,
                       const double*   dd_pair_data_local,
                       const int32_t  dd_prim_pair_count_local,
                       const int32_t* dd_first_inds,
                       const int32_t* dd_second_inds,
                       const double*   dd_pair_data,
                       const int32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockDDDD20(double*         mat_J,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   dd_mat_Q,
                       const int32_t* dd_first_inds_local,
                       const int32_t* dd_second_inds_local,
                       const double*   dd_pair_data_local,
                       const int32_t  dd_prim_pair_count_local,
                       const int32_t* dd_first_inds,
                       const int32_t* dd_second_inds,
                       const double*   dd_pair_data,
                       const int32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockDDDD21(double*         mat_J,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   dd_mat_Q,
                       const int32_t* dd_first_inds_local,
                       const int32_t* dd_second_inds_local,
                       const double*   dd_pair_data_local,
                       const int32_t  dd_prim_pair_count_local,
                       const int32_t* dd_first_inds,
                       const int32_t* dd_second_inds,
                       const double*   dd_pair_data,
                       const int32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockDDDD22(double*         mat_J,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   dd_mat_Q,
                       const int32_t* dd_first_inds_local,
                       const int32_t* dd_second_inds_local,
                       const double*   dd_pair_data_local,
                       const int32_t  dd_prim_pair_count_local,
                       const int32_t* dd_first_inds,
                       const int32_t* dd_second_inds,
                       const double*   dd_pair_data,
                       const int32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockDDDD23(double*         mat_J,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   dd_mat_Q,
                       const int32_t* dd_first_inds_local,
                       const int32_t* dd_second_inds_local,
                       const double*   dd_pair_data_local,
                       const int32_t  dd_prim_pair_count_local,
                       const int32_t* dd_first_inds,
                       const int32_t* dd_second_inds,
                       const double*   dd_pair_data,
                       const int32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockDDDD24(double*         mat_J,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   dd_mat_Q,
                       const int32_t* dd_first_inds_local,
                       const int32_t* dd_second_inds_local,
                       const double*   dd_pair_data_local,
                       const int32_t  dd_prim_pair_count_local,
                       const int32_t* dd_first_inds,
                       const int32_t* dd_second_inds,
                       const double*   dd_pair_data,
                       const int32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockDDDD25(double*         mat_J,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   dd_mat_Q,
                       const int32_t* dd_first_inds_local,
                       const int32_t* dd_second_inds_local,
                       const double*   dd_pair_data_local,
                       const int32_t  dd_prim_pair_count_local,
                       const int32_t* dd_first_inds,
                       const int32_t* dd_second_inds,
                       const double*   dd_pair_data,
                       const int32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockDDDD26(double*         mat_J,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   dd_mat_Q,
                       const int32_t* dd_first_inds_local,
                       const int32_t* dd_second_inds_local,
                       const double*   dd_pair_data_local,
                       const int32_t  dd_prim_pair_count_local,
                       const int32_t* dd_first_inds,
                       const int32_t* dd_second_inds,
                       const double*   dd_pair_data,
                       const int32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockDDDD27(double*         mat_J,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   dd_mat_Q,
                       const int32_t* dd_first_inds_local,
                       const int32_t* dd_second_inds_local,
                       const double*   dd_pair_data_local,
                       const int32_t  dd_prim_pair_count_local,
                       const int32_t* dd_first_inds,
                       const int32_t* dd_second_inds,
                       const double*   dd_pair_data,
                       const int32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockDDDD28(double*         mat_J,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   dd_mat_Q,
                       const int32_t* dd_first_inds_local,
                       const int32_t* dd_second_inds_local,
                       const double*   dd_pair_data_local,
                       const int32_t  dd_prim_pair_count_local,
                       const int32_t* dd_first_inds,
                       const int32_t* dd_second_inds,
                       const double*   dd_pair_data,
                       const int32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockDDDD29(double*         mat_J,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   dd_mat_Q,
                       const int32_t* dd_first_inds_local,
                       const int32_t* dd_second_inds_local,
                       const double*   dd_pair_data_local,
                       const int32_t  dd_prim_pair_count_local,
                       const int32_t* dd_first_inds,
                       const int32_t* dd_second_inds,
                       const double*   dd_pair_data,
                       const int32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockDDPP(double*         mat_J,
                       const double*   p_prim_info,
                       const int32_t  p_prim_count,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   pp_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   pp_mat_Q,
                       const int32_t* dd_first_inds_local,
                       const int32_t* dd_second_inds_local,
                       const double*   dd_pair_data_local,
                       const int32_t  dd_prim_pair_count_local,
                       const int32_t* pp_first_inds,
                       const int32_t* pp_second_inds,
                       const double*   pp_pair_data,
                       const int32_t  pp_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);


__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockDDSD(double*         mat_J,
                       const double*   s_prim_info,
                       const int32_t  s_prim_count,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   sd_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   sd_mat_Q,
                       const int32_t* dd_first_inds_local,
                       const int32_t* dd_second_inds_local,
                       const double*   dd_pair_data_local,
                       const int32_t  dd_prim_pair_count_local,
                       const int32_t* sd_first_inds,
                       const int32_t* sd_second_inds,
                       const double*   sd_pair_data,
                       const int32_t  sd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);


__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockDDSP(double*         mat_J,
                       const double*   s_prim_info,
                       const int32_t  s_prim_count,
                       const double*   p_prim_info,
                       const int32_t  p_prim_count,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   sp_mat_D,
                       const double*   dd_mat_Q_local,
                       const double*   sp_mat_Q,
                       const int32_t* dd_first_inds_local,
                       const int32_t* dd_second_inds_local,
                       const double*   dd_pair_data_local,
                       const int32_t  dd_prim_pair_count_local,
                       const int32_t* sp_first_inds,
                       const int32_t* sp_second_inds,
                       const double*   sp_pair_data,
                       const int32_t  sp_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);


__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockPDDD0(double*         mat_J,
                       const double*   p_prim_info,
                       const int32_t  p_prim_count,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   pd_mat_Q_local,
                       const double*   dd_mat_Q,
                       const int32_t* pd_first_inds_local,
                       const int32_t* pd_second_inds_local,
                       const double*   pd_pair_data_local,
                       const int32_t  pd_prim_pair_count_local,
                       const int32_t* dd_first_inds,
                       const int32_t* dd_second_inds,
                       const double*   dd_pair_data,
                       const int32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockPDDD1(double*         mat_J,
                       const double*   p_prim_info,
                       const int32_t  p_prim_count,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   pd_mat_Q_local,
                       const double*   dd_mat_Q,
                       const int32_t* pd_first_inds_local,
                       const int32_t* pd_second_inds_local,
                       const double*   pd_pair_data_local,
                       const int32_t  pd_prim_pair_count_local,
                       const int32_t* dd_first_inds,
                       const int32_t* dd_second_inds,
                       const double*   dd_pair_data,
                       const int32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockPDDD2(double*         mat_J,
                       const double*   p_prim_info,
                       const int32_t  p_prim_count,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   pd_mat_Q_local,
                       const double*   dd_mat_Q,
                       const int32_t* pd_first_inds_local,
                       const int32_t* pd_second_inds_local,
                       const double*   pd_pair_data_local,
                       const int32_t  pd_prim_pair_count_local,
                       const int32_t* dd_first_inds,
                       const int32_t* dd_second_inds,
                       const double*   dd_pair_data,
                       const int32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockPDDD3(double*         mat_J,
                       const double*   p_prim_info,
                       const int32_t  p_prim_count,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   pd_mat_Q_local,
                       const double*   dd_mat_Q,
                       const int32_t* pd_first_inds_local,
                       const int32_t* pd_second_inds_local,
                       const double*   pd_pair_data_local,
                       const int32_t  pd_prim_pair_count_local,
                       const int32_t* dd_first_inds,
                       const int32_t* dd_second_inds,
                       const double*   dd_pair_data,
                       const int32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockPDDD4(double*         mat_J,
                       const double*   p_prim_info,
                       const int32_t  p_prim_count,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   pd_mat_Q_local,
                       const double*   dd_mat_Q,
                       const int32_t* pd_first_inds_local,
                       const int32_t* pd_second_inds_local,
                       const double*   pd_pair_data_local,
                       const int32_t  pd_prim_pair_count_local,
                       const int32_t* dd_first_inds,
                       const int32_t* dd_second_inds,
                       const double*   dd_pair_data,
                       const int32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockPDDD5(double*         mat_J,
                       const double*   p_prim_info,
                       const int32_t  p_prim_count,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   pd_mat_Q_local,
                       const double*   dd_mat_Q,
                       const int32_t* pd_first_inds_local,
                       const int32_t* pd_second_inds_local,
                       const double*   pd_pair_data_local,
                       const int32_t  pd_prim_pair_count_local,
                       const int32_t* dd_first_inds,
                       const int32_t* dd_second_inds,
                       const double*   dd_pair_data,
                       const int32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockPDDD6(double*         mat_J,
                       const double*   p_prim_info,
                       const int32_t  p_prim_count,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   pd_mat_Q_local,
                       const double*   dd_mat_Q,
                       const int32_t* pd_first_inds_local,
                       const int32_t* pd_second_inds_local,
                       const double*   pd_pair_data_local,
                       const int32_t  pd_prim_pair_count_local,
                       const int32_t* dd_first_inds,
                       const int32_t* dd_second_inds,
                       const double*   dd_pair_data,
                       const int32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockPDPD(double*         mat_J,
                       const double*   p_prim_info,
                       const int32_t  p_prim_count,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   pd_mat_D,
                       const double*   pd_mat_Q_local,
                       const double*   pd_mat_Q,
                       const int32_t* pd_first_inds_local,
                       const int32_t* pd_second_inds_local,
                       const double*   pd_pair_data_local,
                       const int32_t  pd_prim_pair_count_local,
                       const int32_t* pd_first_inds,
                       const int32_t* pd_second_inds,
                       const double*   pd_pair_data,
                       const int32_t  pd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);


__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockPDPP(double*         mat_J,
                       const double*   p_prim_info,
                       const int32_t  p_prim_count,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   pp_mat_D,
                       const double*   pd_mat_Q_local,
                       const double*   pp_mat_Q,
                       const int32_t* pd_first_inds_local,
                       const int32_t* pd_second_inds_local,
                       const double*   pd_pair_data_local,
                       const int32_t  pd_prim_pair_count_local,
                       const int32_t* pp_first_inds,
                       const int32_t* pp_second_inds,
                       const double*   pp_pair_data,
                       const int32_t  pp_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);


__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockPDSD(double*         mat_J,
                       const double*   s_prim_info,
                       const int32_t  s_prim_count,
                       const double*   p_prim_info,
                       const int32_t  p_prim_count,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   sd_mat_D,
                       const double*   pd_mat_Q_local,
                       const double*   sd_mat_Q,
                       const int32_t* pd_first_inds_local,
                       const int32_t* pd_second_inds_local,
                       const double*   pd_pair_data_local,
                       const int32_t  pd_prim_pair_count_local,
                       const int32_t* sd_first_inds,
                       const int32_t* sd_second_inds,
                       const double*   sd_pair_data,
                       const int32_t  sd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);


__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockSDDD(double*         mat_J,
                       const double*   s_prim_info,
                       const int32_t  s_prim_count,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   sd_mat_Q_local,
                       const double*   dd_mat_Q,
                       const int32_t* sd_first_inds_local,
                       const int32_t* sd_second_inds_local,
                       const double*   sd_pair_data_local,
                       const int32_t  sd_prim_pair_count_local,
                       const int32_t* dd_first_inds,
                       const int32_t* dd_second_inds,
                       const double*   dd_pair_data,
                       const int32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);


__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockSDPD(double*         mat_J,
                       const double*   s_prim_info,
                       const int32_t  s_prim_count,
                       const double*   p_prim_info,
                       const int32_t  p_prim_count,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   pd_mat_D,
                       const double*   sd_mat_Q_local,
                       const double*   pd_mat_Q,
                       const int32_t* sd_first_inds_local,
                       const int32_t* sd_second_inds_local,
                       const double*   sd_pair_data_local,
                       const int32_t  sd_prim_pair_count_local,
                       const int32_t* pd_first_inds,
                       const int32_t* pd_second_inds,
                       const double*   pd_pair_data,
                       const int32_t  pd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);


__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockSDPP(double*         mat_J,
                       const double*   s_prim_info,
                       const int32_t  s_prim_count,
                       const double*   p_prim_info,
                       const int32_t  p_prim_count,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   pp_mat_D,
                       const double*   sd_mat_Q_local,
                       const double*   pp_mat_Q,
                       const int32_t* sd_first_inds_local,
                       const int32_t* sd_second_inds_local,
                       const double*   sd_pair_data_local,
                       const int32_t  sd_prim_pair_count_local,
                       const int32_t* pp_first_inds,
                       const int32_t* pp_second_inds,
                       const double*   pp_pair_data,
                       const int32_t  pp_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockSDSD(double*         mat_J,
                       const double*   s_prim_info,
                       const int32_t  s_prim_count,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   sd_mat_D,
                       const double*   sd_mat_Q_local,
                       const double*   sd_mat_Q,
                       const int32_t* sd_first_inds_local,
                       const int32_t* sd_second_inds_local,
                       const double*   sd_pair_data_local,
                       const int32_t  sd_prim_pair_count_local,
                       const int32_t* sd_first_inds,
                       const int32_t* sd_second_inds,
                       const double*   sd_pair_data,
                       const int32_t  sd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);


__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockPPDD(double*         mat_J,
                       const double*   p_prim_info,
                       const int32_t  p_prim_count,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   pp_mat_Q_local,
                       const double*   dd_mat_Q,
                       const int32_t* pp_first_inds_local,
                       const int32_t* pp_second_inds_local,
                       const double*   pp_pair_data_local,
                       const int32_t  pp_prim_pair_count_local,
                       const int32_t* dd_first_inds,
                       const int32_t* dd_second_inds,
                       const double*   dd_pair_data,
                       const int32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);


__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockPPPD(double*         mat_J,
                       const double*   p_prim_info,
                       const int32_t  p_prim_count,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   pd_mat_D,
                       const double*   pp_mat_Q_local,
                       const double*   pd_mat_Q,
                       const int32_t* pp_first_inds_local,
                       const int32_t* pp_second_inds_local,
                       const double*   pp_pair_data_local,
                       const int32_t  pp_prim_pair_count_local,
                       const int32_t* pd_first_inds,
                       const int32_t* pd_second_inds,
                       const double*   pd_pair_data,
                       const int32_t  pd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);


__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockPPPP(double*         mat_J,
                       const double*   p_prim_info,
                       const int32_t  p_prim_count,
                       const double*   pp_mat_D,
                       const double*   pp_mat_Q_local,
                       const double*   pp_mat_Q,
                       const int32_t* pp_first_inds_local,
                       const int32_t* pp_second_inds_local,
                       const double*   pp_pair_data_local,
                       const int32_t  pp_prim_pair_count_local,
                       const int32_t* pp_first_inds,
                       const int32_t* pp_second_inds,
                       const double*   pp_pair_data,
                       const int32_t  pp_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);

__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockPPSD(double*         mat_J,
                       const double*   s_prim_info,
                       const int32_t  s_prim_count,
                       const double*   p_prim_info,
                       const int32_t  p_prim_count,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   sd_mat_D,
                       const double*   pp_mat_Q_local,
                       const double*   sd_mat_Q,
                       const int32_t* pp_first_inds_local,
                       const int32_t* pp_second_inds_local,
                       const double*   pp_pair_data_local,
                       const int32_t  pp_prim_pair_count_local,
                       const int32_t* sd_first_inds,
                       const int32_t* sd_second_inds,
                       const double*   sd_pair_data,
                       const int32_t  sd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);


__global__ void __launch_bounds__(TILE_SIZE_J)
computeCoulombFockSPDD(double*         mat_J,
                       const double*   s_prim_info,
                       const int32_t  s_prim_count,
                       const double*   p_prim_info,
                       const int32_t  p_prim_count,
                       const double*   d_prim_info,
                       const int32_t  d_prim_count,
                       const double*   dd_mat_D,
                       const double*   sp_mat_Q_local,
                       const double*   dd_mat_Q,
                       const int32_t* sp_first_inds_local,
                       const int32_t* sp_second_inds_local,
                       const double*   sp_pair_data_local,
                       const int32_t  sp_prim_pair_count_local,
                       const int32_t* dd_first_inds,
                       const int32_t* dd_second_inds,
                       const double*   dd_pair_data,
                       const int32_t  dd_prim_pair_count,
                       const double*   boys_func_table,
                       const double*   boys_func_ft,
                       const double    eri_threshold);


}  // namespace gpu

#endif
