name: build

on:
  push:
    branches:
      - master
      - multipsi_newcore
      - embedding_test
      - c_pcm
      - dft-update
      - hessian-update
      - ri-test
      - rijk-test
      - tddft_vibanalysis_test
      - tddft_grad_test
      - feature-test
      - merge-test
      - restart-test

jobs:
  vlx_ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l -e -o pipefail {0}

    container:
      image: ghcr.io/veloxchem/meta-vlx/vlx-ci_gnu:sha-ffcf0d3

    env:
      VLX_NUM_BUILD_JOBS: "4"
      OMPI_ALLOW_RUN_AS_ROOT: "1"
      OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: "1"

    steps:
      - name: checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: build and test
        run: |
          echo "=== System Info ==="
          uname -a
          free -m
          df -h
          ulimit -a
          ulimit -s unlimited
          lscpu | egrep 'Thread|Core|Socket|^CPU\('
          echo "=== Replace Ubuntu 24.04 mpich with openmpi ==="
          apt-get update -qq
          apt-get purge -y -qq mpich libmpich12 libmpich-dev
          apt-get install -y -qq --no-install-recommends openmpi-bin libopenmpi-dev
          apt-get autoremove -y -qq
          which mpicc mpiexec mpicc.openmpi mpiexec.openmpi
          mpicc.openmpi --showme:version
          mpiexec.openmpi --version | head -2
          echo "=== GNU Compiler ==="
          gcc --version
          g++ --version
          echo "=== Python ==="
          which python
          python -V
          echo "=== Python venv ==="
          python -m venv --clear venv
          source venv/bin/activate
          which python
          python -V
          echo "=== Python dependencies ==="
          python -m pip install --upgrade pip setuptools wheel
          CC=gcc MPICC=mpicc.openmpi python -m pip install --no-cache-dir mpi4py --no-binary=mpi4py
          echo "=== MPI sanity check ==="
          mpiexec.openmpi -n 2 python -c "from mpi4py import MPI; size = MPI.COMM_WORLD.Get_size(); assert size == 2, size"
          CC=gcc CXX=g++ python -m pip install MDAnalysis
          git config --global --add safe.directory $PWD
          git clone -b 3.4.0 https://gitlab.com/libeigen/eigen.git
          git clone -b boost-1.90.0 https://github.com/boostorg/math.git boost-math
          cd eigen && test "$(git rev-parse HEAD)" = "3147391d946bb4b6c68edd901f2add6ac1f31f8c" && cd ..
          cd boost-math && test "$(git rev-parse HEAD)" = "e0fcd19f7227d81391770ea46015acc3c80af810" && cd ..
          export EIGEN_INCLUDE_DIR=$(pwd)/eigen
          export BOOST_INCLUDE_DIR=$(pwd)/boost-math/include
          CXX=g++ python -m pip install git+https://github.com/VeloxChem/PyFraME.git
          python -m pip install dftd4
          python -m pip install openmm rdkit pymbar
          echo "=== VeloxChem build ==="
          export CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH:/usr/local
          SKBUILD_CONFIGURE_OPTIONS="-DCMAKE_CXX_COMPILER=g++ -DVLX_USE_MATHLIB=ON -DVLX_MATH_LIBRARY=/usr/lib/x86_64-linux-gnu/openblas-openmp/libopenblas.so" \
            python -m pip install -v .[test,qmmm]
          echo "=== VeloxChem test ==="
          python -c "import veloxchem; print(veloxchem.__version__)"
          OMP_NUM_THREADS=2 mpiexec.openmpi -n 2 python -m pytest --capture=no --log-cli-level=INFO \
            -m "solvers" --durations=10
          OMP_NUM_THREADS=4 python -m pytest --cov=veloxchem --capture=no --log-cli-level=INFO \
            -m "not timeconsuming" --durations=10
          git clone https://github.com/VeloxChem/vlx-extra-tests.git
          OMP_NUM_THREADS=4 python -m pytest --capture=no --log-cli-level=INFO vlx-extra-tests/tests
